/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EconomyHistoryResponseDataInner
 */
class EconomyHistoryResponseDataInnerTest {
    private final EconomyHistoryResponseDataInner model = new EconomyHistoryResponseDataInner();

    /**
     * Model tests for EconomyHistoryResponseDataInner
     */
    @Test
    void testEconomyHistoryResponseDataInner() {
        // TODO: test EconomyHistoryResponseDataInner
    }

    /**
     * Test the property 'type'
     */
    @Test
    void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'desc'
     */
    @Test
    void descTest() {
        // TODO: test desc
    }

    /**
     * Test the property 'datetime'
     */
    @Test
    void datetimeTest() {
        // TODO: test datetime
    }

    /**
     * Test the property 'balanceBefore'
     */
    @Test
    void balanceBeforeTest() {
        // TODO: test balanceBefore
    }

    /**
     * Test the property 'amount'
     */
    @Test
    void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'balanceAfter'
     */
    @Test
    void balanceAfterTest() {
        // TODO: test balanceAfter
    }

}
