/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for History500OBRResponseManagersInnerManager
 */
class History500OBRResponseManagersInnerManagerTest {
    private final History500OBRResponseManagersInnerManager model = new History500OBRResponseManagersInnerManager();

    /**
     * Model tests for History500OBRResponseManagersInnerManager
     */
    @Test
    void testHistory500OBRResponseManagersInnerManager() {
        // TODO: test History500OBRResponseManagersInnerManager
    }

    /**
     * Test the property 'fName'
     */
    @Test
    void fNameTest() {
        // TODO: test fName
    }

    /**
     * Test the property 'lName'
     */
    @Test
    void lNameTest() {
        // TODO: test lName
    }

    /**
     * Test the property 'idm'
     */
    @Test
    void idmTest() {
        // TODO: test idm
    }

    /**
     * Test the property 'champs'
     */
    @Test
    void champsTest() {
        // TODO: test champs
    }

    /**
     * Test the property 'color'
     */
    @Test
    void colorTest() {
        // TODO: test color
    }

}
