/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.jlobato.gpro.model.NegOverviewResponseCarSpotsInner;
import org.jlobato.gpro.model.NegOverviewResponseCommsInner;
import org.jlobato.gpro.model.NegOverviewResponseOngNegsInner;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for NegOverviewResponse
 */
class NegOverviewResponseTest {
    private final NegOverviewResponse model = new NegOverviewResponse();

    /**
     * Model tests for NegOverviewResponse
     */
    @Test
    void testNegOverviewResponse() {
        // TODO: test NegOverviewResponse
    }

    /**
     * Test the property 'loadingDataState'
     */
    @Test
    void loadingDataStateTest() {
        // TODO: test loadingDataState
    }

    /**
     * Test the property 'carSpots'
     */
    @Test
    void carSpotsTest() {
        // TODO: test carSpots
    }

    /**
     * Test the property 'carSpotsTaken'
     */
    @Test
    void carSpotsTakenTest() {
        // TODO: test carSpotsTaken
    }

    /**
     * Test the property 'ongNegs'
     */
    @Test
    void ongNegsTest() {
        // TODO: test ongNegs
    }

    /**
     * Test the property 'comms'
     */
    @Test
    void commsTest() {
        // TODO: test comms
    }

    /**
     * Test the property 'negPrioUpdated'
     */
    @Test
    void negPrioUpdatedTest() {
        // TODO: test negPrioUpdated
    }

    /**
     * Test the property 'updateInProgress'
     */
    @Test
    void updateInProgressTest() {
        // TODO: test updateInProgress
    }

    /**
     * Test the property 'raceInProgress'
     */
    @Test
    void raceInProgressTest() {
        // TODO: test raceInProgress
    }

    /**
     * Test the property 'errorMsg'
     */
    @Test
    void errorMsgTest() {
        // TODO: test errorMsg
    }

    /**
     * Test the property 'apiRequestsRemaining'
     */
    @Test
    void apiRequestsRemainingTest() {
        // TODO: test apiRequestsRemaining
    }

}
