/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.jlobato.gpro.model.SnFHistoryResponseDataGraphAccessibility;
import org.jlobato.gpro.model.SnFHistoryResponseDataGraphChart;
import org.jlobato.gpro.model.SnFHistoryResponseDataGraphCredits;
import org.jlobato.gpro.model.SnFHistoryResponseDataGraphLegend;
import org.jlobato.gpro.model.SnFHistoryResponseDataGraphPlotOptions;
import org.jlobato.gpro.model.SnFHistoryResponseDataGraphSeriesInner;
import org.jlobato.gpro.model.SnFHistoryResponseDataGraphSubtitle;
import org.jlobato.gpro.model.SnFHistoryResponseDataGraphTitle;
import org.jlobato.gpro.model.SnFHistoryResponseDataGraphTooltip;
import org.jlobato.gpro.model.SnFHistoryResponseDataGraphYAxis;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SnFHistoryResponseDataGraph
 */
class SnFHistoryResponseDataGraphTest {
    private final SnFHistoryResponseDataGraph model = new SnFHistoryResponseDataGraph();

    /**
     * Model tests for SnFHistoryResponseDataGraph
     */
    @Test
    void testSnFHistoryResponseDataGraph() {
        // TODO: test SnFHistoryResponseDataGraph
    }

    /**
     * Test the property 'chart'
     */
    @Test
    void chartTest() {
        // TODO: test chart
    }

    /**
     * Test the property 'accessibility'
     */
    @Test
    void accessibilityTest() {
        // TODO: test accessibility
    }

    /**
     * Test the property 'title'
     */
    @Test
    void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'subtitle'
     */
    @Test
    void subtitleTest() {
        // TODO: test subtitle
    }

    /**
     * Test the property 'plotOptions'
     */
    @Test
    void plotOptionsTest() {
        // TODO: test plotOptions
    }

    /**
     * Test the property 'yAxis'
     */
    @Test
    void yAxisTest() {
        // TODO: test yAxis
    }

    /**
     * Test the property 'xAxis'
     */
    @Test
    void xAxisTest() {
        // TODO: test xAxis
    }

    /**
     * Test the property 'legend'
     */
    @Test
    void legendTest() {
        // TODO: test legend
    }

    /**
     * Test the property 'credits'
     */
    @Test
    void creditsTest() {
        // TODO: test credits
    }

    /**
     * Test the property 'tooltip'
     */
    @Test
    void tooltipTest() {
        // TODO: test tooltip
    }

    /**
     * Test the property 'series'
     */
    @Test
    void seriesTest() {
        // TODO: test series
    }

}
