/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.jlobato.gpro.model.SnFHistoryResponseDataGraphYAxisLabels;
import org.jlobato.gpro.model.StandingsResponseDataGraphYAxisTitle;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for StandingsResponseDataGraphYAxis
 */
class StandingsResponseDataGraphYAxisTest {
    private final StandingsResponseDataGraphYAxis model = new StandingsResponseDataGraphYAxis();

    /**
     * Model tests for StandingsResponseDataGraphYAxis
     */
    @Test
    void testStandingsResponseDataGraphYAxis() {
        // TODO: test StandingsResponseDataGraphYAxis
    }

    /**
     * Test the property 'reversed'
     */
    @Test
    void reversedTest() {
        // TODO: test reversed
    }

    /**
     * Test the property 'max'
     */
    @Test
    void maxTest() {
        // TODO: test max
    }

    /**
     * Test the property 'min'
     */
    @Test
    void minTest() {
        // TODO: test min
    }

    /**
     * Test the property 'startOnTick'
     */
    @Test
    void startOnTickTest() {
        // TODO: test startOnTick
    }

    /**
     * Test the property 'tickInterval'
     */
    @Test
    void tickIntervalTest() {
        // TODO: test tickInterval
    }

    /**
     * Test the property 'showFirstLabel'
     */
    @Test
    void showFirstLabelTest() {
        // TODO: test showFirstLabel
    }

    /**
     * Test the property 'showLastLabel'
     */
    @Test
    void showLastLabelTest() {
        // TODO: test showLastLabel
    }

    /**
     * Test the property 'gridLineColor'
     */
    @Test
    void gridLineColorTest() {
        // TODO: test gridLineColor
    }

    /**
     * Test the property 'labels'
     */
    @Test
    void labelsTest() {
        // TODO: test labels
    }

    /**
     * Test the property 'lineColor'
     */
    @Test
    void lineColorTest() {
        // TODO: test lineColor
    }

    /**
     * Test the property 'minorTickInterval'
     */
    @Test
    void minorTickIntervalTest() {
        // TODO: test minorTickInterval
    }

    /**
     * Test the property 'tickColor'
     */
    @Test
    void tickColorTest() {
        // TODO: test tickColor
    }

    /**
     * Test the property 'tickWidth'
     */
    @Test
    void tickWidthTest() {
        // TODO: test tickWidth
    }

    /**
     * Test the property 'title'
     */
    @Test
    void titleTest() {
        // TODO: test title
    }

}
