/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.jlobato.gpro.model.TrackProfileResponseQualRecord;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TrackProfileResponse
 */
class TrackProfileResponseTest {
    private final TrackProfileResponse model = new TrackProfileResponse();

    /**
     * Model tests for TrackProfileResponse
     */
    @Test
    void testTrackProfileResponse() {
        // TODO: test TrackProfileResponse
    }

    /**
     * Test the property 'loadingDataState'
     */
    @Test
    void loadingDataStateTest() {
        // TODO: test loadingDataState
    }

    /**
     * Test the property 'trackNotFoundNote'
     */
    @Test
    void trackNotFoundNoteTest() {
        // TODO: test trackNotFoundNote
    }

    /**
     * Test the property 'location'
     */
    @Test
    void locationTest() {
        // TODO: test location
    }

    /**
     * Test the property 'trackName'
     */
    @Test
    void trackNameTest() {
        // TODO: test trackName
    }

    /**
     * Test the property 'trackImage'
     */
    @Test
    void trackImageTest() {
        // TODO: test trackImage
    }

    /**
     * Test the property 'date'
     */
    @Test
    void dateTest() {
        // TODO: test date
    }

    /**
     * Test the property 'power'
     */
    @Test
    void powerTest() {
        // TODO: test power
    }

    /**
     * Test the property 'accel'
     */
    @Test
    void accelTest() {
        // TODO: test accel
    }

    /**
     * Test the property 'handl'
     */
    @Test
    void handlTest() {
        // TODO: test handl
    }

    /**
     * Test the property 'raceDistance'
     */
    @Test
    void raceDistanceTest() {
        // TODO: test raceDistance
    }

    /**
     * Test the property 'laps'
     */
    @Test
    void lapsTest() {
        // TODO: test laps
    }

    /**
     * Test the property 'downforce'
     */
    @Test
    void downforceTest() {
        // TODO: test downforce
    }

    /**
     * Test the property 'lapDistance'
     */
    @Test
    void lapDistanceTest() {
        // TODO: test lapDistance
    }

    /**
     * Test the property 'overtaking'
     */
    @Test
    void overtakingTest() {
        // TODO: test overtaking
    }

    /**
     * Test the property 'avgSpeed'
     */
    @Test
    void avgSpeedTest() {
        // TODO: test avgSpeed
    }

    /**
     * Test the property 'suspRigidity'
     */
    @Test
    void suspRigidityTest() {
        // TODO: test suspRigidity
    }

    /**
     * Test the property 'gpsHeld'
     */
    @Test
    void gpsHeldTest() {
        // TODO: test gpsHeld
    }

    /**
     * Test the property 'fuelConsumption'
     */
    @Test
    void fuelConsumptionTest() {
        // TODO: test fuelConsumption
    }

    /**
     * Test the property 'nbTurns'
     */
    @Test
    void nbTurnsTest() {
        // TODO: test nbTurns
    }

    /**
     * Test the property 'tyreWear'
     */
    @Test
    void tyreWearTest() {
        // TODO: test tyreWear
    }

    /**
     * Test the property 'timeInOutPits'
     */
    @Test
    void timeInOutPitsTest() {
        // TODO: test timeInOutPits
    }

    /**
     * Test the property 'gripLevel'
     */
    @Test
    void gripLevelTest() {
        // TODO: test gripLevel
    }

    /**
     * Test the property 'category'
     */
    @Test
    void categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'qualRecord'
     */
    @Test
    void qualRecordTest() {
        // TODO: test qualRecord
    }

    /**
     * Test the property 'raceRecord'
     */
    @Test
    void raceRecordTest() {
        // TODO: test raceRecord
    }

    /**
     * Test the property 'qualRecordWet'
     */
    @Test
    void qualRecordWetTest() {
        // TODO: test qualRecordWet
    }

    /**
     * Test the property 'raceRecordWet'
     */
    @Test
    void raceRecordWetTest() {
        // TODO: test raceRecordWet
    }

    /**
     * Test the property 'achievWin'
     */
    @Test
    void achievWinTest() {
        // TODO: test achievWin
    }

    /**
     * Test the property 'achievFL'
     */
    @Test
    void achievFLTest() {
        // TODO: test achievFL
    }

    /**
     * Test the property 'achievPole'
     */
    @Test
    void achievPoleTest() {
        // TODO: test achievPole
    }

    /**
     * Test the property 'rpoints'
     */
    @Test
    void rpointsTest() {
        // TODO: test rpoints
    }

    /**
     * Test the property 'rpodiums'
     */
    @Test
    void rpodiumsTest() {
        // TODO: test rpodiums
    }

    /**
     * Test the property 'rwins'
     */
    @Test
    void rwinsTest() {
        // TODO: test rwins
    }

    /**
     * Test the property 'rpoles'
     */
    @Test
    void rpolesTest() {
        // TODO: test rpoles
    }

    /**
     * Test the property 'rfLs'
     */
    @Test
    void rfLsTest() {
        // TODO: test rfLs
    }

    /**
     * Test the property 'rraces'
     */
    @Test
    void rracesTest() {
        // TODO: test rraces
    }

    /**
     * Test the property 'apoints'
     */
    @Test
    void apointsTest() {
        // TODO: test apoints
    }

    /**
     * Test the property 'apodiums'
     */
    @Test
    void apodiumsTest() {
        // TODO: test apodiums
    }

    /**
     * Test the property 'awins'
     */
    @Test
    void awinsTest() {
        // TODO: test awins
    }

    /**
     * Test the property 'apoles'
     */
    @Test
    void apolesTest() {
        // TODO: test apoles
    }

    /**
     * Test the property 'afLs'
     */
    @Test
    void afLsTest() {
        // TODO: test afLs
    }

    /**
     * Test the property 'araces'
     */
    @Test
    void aracesTest() {
        // TODO: test araces
    }

    /**
     * Test the property 'ppoints'
     */
    @Test
    void ppointsTest() {
        // TODO: test ppoints
    }

    /**
     * Test the property 'ppodiums'
     */
    @Test
    void ppodiumsTest() {
        // TODO: test ppodiums
    }

    /**
     * Test the property 'pwins'
     */
    @Test
    void pwinsTest() {
        // TODO: test pwins
    }

    /**
     * Test the property 'ppoles'
     */
    @Test
    void ppolesTest() {
        // TODO: test ppoles
    }

    /**
     * Test the property 'pfLs'
     */
    @Test
    void pfLsTest() {
        // TODO: test pfLs
    }

    /**
     * Test the property 'praces'
     */
    @Test
    void pracesTest() {
        // TODO: test praces
    }

    /**
     * Test the property 'mpoints'
     */
    @Test
    void mpointsTest() {
        // TODO: test mpoints
    }

    /**
     * Test the property 'mpodiums'
     */
    @Test
    void mpodiumsTest() {
        // TODO: test mpodiums
    }

    /**
     * Test the property 'mwins'
     */
    @Test
    void mwinsTest() {
        // TODO: test mwins
    }

    /**
     * Test the property 'mpoles'
     */
    @Test
    void mpolesTest() {
        // TODO: test mpoles
    }

    /**
     * Test the property 'mfLs'
     */
    @Test
    void mfLsTest() {
        // TODO: test mfLs
    }

    /**
     * Test the property 'mraces'
     */
    @Test
    void mracesTest() {
        // TODO: test mraces
    }

    /**
     * Test the property 'epoints'
     */
    @Test
    void epointsTest() {
        // TODO: test epoints
    }

    /**
     * Test the property 'epodiums'
     */
    @Test
    void epodiumsTest() {
        // TODO: test epodiums
    }

    /**
     * Test the property 'ewins'
     */
    @Test
    void ewinsTest() {
        // TODO: test ewins
    }

    /**
     * Test the property 'epoles'
     */
    @Test
    void epolesTest() {
        // TODO: test epoles
    }

    /**
     * Test the property 'efLs'
     */
    @Test
    void efLsTest() {
        // TODO: test efLs
    }

    /**
     * Test the property 'eraces'
     */
    @Test
    void eracesTest() {
        // TODO: test eraces
    }

    /**
     * Test the property 'tpoints'
     */
    @Test
    void tpointsTest() {
        // TODO: test tpoints
    }

    /**
     * Test the property 'tpodiums'
     */
    @Test
    void tpodiumsTest() {
        // TODO: test tpodiums
    }

    /**
     * Test the property 'twins'
     */
    @Test
    void twinsTest() {
        // TODO: test twins
    }

    /**
     * Test the property 'tpoles'
     */
    @Test
    void tpolesTest() {
        // TODO: test tpoles
    }

    /**
     * Test the property 'tfLs'
     */
    @Test
    void tfLsTest() {
        // TODO: test tfLs
    }

    /**
     * Test the property 'traces'
     */
    @Test
    void tracesTest() {
        // TODO: test traces
    }

    /**
     * Test the property 'trackDesc'
     */
    @Test
    void trackDescTest() {
        // TODO: test trackDesc
    }

    /**
     * Test the property 'hideTrackDesc'
     */
    @Test
    void hideTrackDescTest() {
        // TODO: test hideTrackDesc
    }

    /**
     * Test the property 'apiRequestsRemaining'
     */
    @Test
    void apiRequestsRemainingTest() {
        // TODO: test apiRequestsRemaining
    }

}
