/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.jlobato.gpro.model.CarResponseChassisOptionsInnerValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CarResponseChassisOptionsInner
 */
class CarResponseChassisOptionsInnerTest {
    private final CarResponseChassisOptionsInner model = new CarResponseChassisOptionsInner();

    /**
     * Model tests for CarResponseChassisOptionsInner
     */
    @Test
    void testCarResponseChassisOptionsInner() {
        // TODO: test CarResponseChassisOptionsInner
    }

    /**
     * Test the property 'value'
     */
    @Test
    void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'newLvl'
     */
    @Test
    void newLvlTest() {
        // TODO: test newLvl
    }

    /**
     * Test the property 'newWear'
     */
    @Test
    void newWearTest() {
        // TODO: test newWear
    }

    /**
     * Test the property 'disabled'
     */
    @Test
    void disabledTest() {
        // TODO: test disabled
    }

    /**
     * Test the property 'text'
     */
    @Test
    void textTest() {
        // TODO: test text
    }

}
