/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.jlobato.gpro.model.EconomyHistoryGraphResponseDataGraphYAxisLabels;
import org.jlobato.gpro.model.EconomyHistoryGraphResponseDataGraphYAxisPlotLinesInner;
import org.jlobato.gpro.model.SnFHistoryResponseDataGraphTitle;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EconomyHistoryGraphResponseDataGraphYAxis
 */
class EconomyHistoryGraphResponseDataGraphYAxisTest {
    private final EconomyHistoryGraphResponseDataGraphYAxis model = new EconomyHistoryGraphResponseDataGraphYAxis();

    /**
     * Model tests for EconomyHistoryGraphResponseDataGraphYAxis
     */
    @Test
    void testEconomyHistoryGraphResponseDataGraphYAxis() {
        // TODO: test EconomyHistoryGraphResponseDataGraphYAxis
    }

    /**
     * Test the property 'title'
     */
    @Test
    void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'labels'
     */
    @Test
    void labelsTest() {
        // TODO: test labels
    }

    /**
     * Test the property 'plotLines'
     */
    @Test
    void plotLinesTest() {
        // TODO: test plotLines
    }

}
