/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.jlobato.gpro.model.EconomyHistoryESGraphResponse;
import org.jlobato.gpro.model.EconomyHistoryESGraphResponseDataGraph;
import org.jlobato.gpro.model.EconomyHistoryGraphResponse;
import org.jlobato.gpro.model.EconomyHistoryResponse;
import org.jlobato.gpro.model.EconomyHistoryResponseDataInner;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetEconomyHistory200Response
 */
class GetEconomyHistory200ResponseTest {
    private final GetEconomyHistory200Response model = new GetEconomyHistory200Response();

    /**
     * Model tests for GetEconomyHistory200Response
     */
    @Test
    void testGetEconomyHistory200Response() {
        // TODO: test GetEconomyHistory200Response
    }

    /**
     * Test the property 'loadingDataState'
     */
    @Test
    void loadingDataStateTest() {
        // TODO: test loadingDataState
    }

    /**
     * Test the property 'curPage'
     */
    @Test
    void curPageTest() {
        // TODO: test curPage
    }

    /**
     * Test the property 'totPages'
     */
    @Test
    void totPagesTest() {
        // TODO: test totPages
    }

    /**
     * Test the property 'data'
     */
    @Test
    void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'apiRequestsRemaining'
     */
    @Test
    void apiRequestsRemainingTest() {
        // TODO: test apiRequestsRemaining
    }

    /**
     * Test the property 'dataGraph'
     */
    @Test
    void dataGraphTest() {
        // TODO: test dataGraph
    }

}
