/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.jlobato.gpro.model.LoggedOut;
import org.jlobato.gpro.model.TrackEOS;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetTrackProfile401Response
 */
class GetTrackProfile401ResponseTest {
    private final GetTrackProfile401Response model = new GetTrackProfile401Response();

    /**
     * Model tests for GetTrackProfile401Response
     */
    @Test
    void testGetTrackProfile401Response() {
        // TODO: test GetTrackProfile401Response
    }

    /**
     * Test the property 'loggedOut'
     */
    @Test
    void loggedOutTest() {
        // TODO: test loggedOut
    }

    /**
     * Test the property 'loadingDataState'
     */
    @Test
    void loadingDataStateTest() {
        // TODO: test loadingDataState
    }

    /**
     * Test the property 'trackNotFoundNote'
     */
    @Test
    void trackNotFoundNoteTest() {
        // TODO: test trackNotFoundNote
    }

}
