/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.jlobato.gpro.model.HistoryCalendarResponseManagersInnerWinner;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for HistoryCalendarResponseManagersInner
 */
class HistoryCalendarResponseManagersInnerTest {
    private final HistoryCalendarResponseManagersInner model = new HistoryCalendarResponseManagersInner();

    /**
     * Model tests for HistoryCalendarResponseManagersInner
     */
    @Test
    void testHistoryCalendarResponseManagersInner() {
        // TODO: test HistoryCalendarResponseManagersInner
    }

    /**
     * Test the property 'winner'
     */
    @Test
    void winnerTest() {
        // TODO: test winner
    }

    /**
     * Test the property 'eventType'
     */
    @Test
    void eventTypeTest() {
        // TODO: test eventType
    }

    /**
     * Test the property 'pos'
     */
    @Test
    void posTest() {
        // TODO: test pos
    }

    /**
     * Test the property 'trackName'
     */
    @Test
    void trackNameTest() {
        // TODO: test trackName
    }

    /**
     * Test the property 'natCode'
     */
    @Test
    void natCodeTest() {
        // TODO: test natCode
    }

    /**
     * Test the property 'isTestTrack'
     */
    @Test
    void isTestTrackTest() {
        // TODO: test isTestTrack
    }

    /**
     * Test the property 'dateEvent'
     */
    @Test
    void dateEventTest() {
        // TODO: test dateEvent
    }

    /**
     * Test the property 'trackId'
     */
    @Test
    void trackIdTest() {
        // TODO: test trackId
    }

}
