/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.jlobato.gpro.model.CalendarResponseGroupsInner;
import org.jlobato.gpro.model.History500OBRResponseSectionsInner;
import org.jlobato.gpro.model.HistoryCalendarResponseManagersInner;
import org.jlobato.gpro.model.HistoryGroupCupResponseCupDataInner;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for HistoryGroupCupResponse
 */
class HistoryGroupCupResponseTest {
    private final HistoryGroupCupResponse model = new HistoryGroupCupResponse();

    /**
     * Model tests for HistoryGroupCupResponse
     */
    @Test
    void testHistoryGroupCupResponse() {
        // TODO: test HistoryGroupCupResponse
    }

    /**
     * Test the property 'loadingDataState'
     */
    @Test
    void loadingDataStateTest() {
        // TODO: test loadingDataState
    }

    /**
     * Test the property 'sections'
     */
    @Test
    void sectionsTest() {
        // TODO: test sections
    }

    /**
     * Test the property 'group'
     */
    @Test
    void groupTest() {
        // TODO: test group
    }

    /**
     * Test the property 'requestedSeason'
     */
    @Test
    void requestedSeasonTest() {
        // TODO: test requestedSeason
    }

    /**
     * Test the property 'season'
     */
    @Test
    void seasonTest() {
        // TODO: test season
    }

    /**
     * Test the property 'title'
     */
    @Test
    void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'statsType'
     */
    @Test
    void statsTypeTest() {
        // TODO: test statsType
    }

    /**
     * Test the property 'errorText'
     */
    @Test
    void errorTextTest() {
        // TODO: test errorText
    }

    /**
     * Test the property 'cupData'
     */
    @Test
    void cupDataTest() {
        // TODO: test cupData
    }

    /**
     * Test the property 'managers'
     */
    @Test
    void managersTest() {
        // TODO: test managers
    }

    /**
     * Test the property 'groups'
     */
    @Test
    void groupsTest() {
        // TODO: test groups
    }

}
