/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for LastTransfersResponseDriverTransfersInner
 */
class LastTransfersResponseDriverTransfersInnerTest {
    private final LastTransfersResponseDriverTransfersInner model = new LastTransfersResponseDriverTransfersInner();

    /**
     * Model tests for LastTransfersResponseDriverTransfersInner
     */
    @Test
    void testLastTransfersResponseDriverTransfersInner() {
        // TODO: test LastTransfersResponseDriverTransfersInner
    }

    /**
     * Test the property 'idx'
     */
    @Test
    void idxTest() {
        // TODO: test idx
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'natCode'
     */
    @Test
    void natCodeTest() {
        // TODO: test natCode
    }

    /**
     * Test the property 'IDM'
     */
    @Test
    void IDMTest() {
        // TODO: test IDM
    }

    /**
     * Test the property 'champs'
     */
    @Test
    void champsTest() {
        // TODO: test champs
    }

    /**
     * Test the property 'groupId'
     */
    @Test
    void groupIdTest() {
        // TODO: test groupId
    }

    /**
     * Test the property 'groupIdShort'
     */
    @Test
    void groupIdShortTest() {
        // TODO: test groupIdShort
    }

    /**
     * Test the property 'groupOrderId'
     */
    @Test
    void groupOrderIdTest() {
        // TODO: test groupOrderId
    }

    /**
     * Test the property 'staffId'
     */
    @Test
    void staffIdTest() {
        // TODO: test staffId
    }

    /**
     * Test the property 'staffName'
     */
    @Test
    void staffNameTest() {
        // TODO: test staffName
    }

    /**
     * Test the property 'staffColor'
     */
    @Test
    void staffColorTest() {
        // TODO: test staffColor
    }

    /**
     * Test the property 'races'
     */
    @Test
    void racesTest() {
        // TODO: test races
    }

    /**
     * Test the property 'salary'
     */
    @Test
    void salaryTest() {
        // TODO: test salary
    }

}
