/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RaceSummaryResponseManagersInner
 */
class RaceSummaryResponseManagersInnerTest {
    private final RaceSummaryResponseManagersInner model = new RaceSummaryResponseManagersInner();

    /**
     * Model tests for RaceSummaryResponseManagersInner
     */
    @Test
    void testRaceSummaryResponseManagersInner() {
        // TODO: test RaceSummaryResponseManagersInner
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'idx'
     */
    @Test
    void idxTest() {
        // TODO: test idx
    }

    /**
     * Test the property 'pos'
     */
    @Test
    void posTest() {
        // TODO: test pos
    }

    /**
     * Test the property 'progress'
     */
    @Test
    void progressTest() {
        // TODO: test progress
    }

    /**
     * Test the property 'tyre'
     */
    @Test
    void tyreTest() {
        // TODO: test tyre
    }

    /**
     * Test the property 'natCode'
     */
    @Test
    void natCodeTest() {
        // TODO: test natCode
    }

    /**
     * Test the property 'IDM'
     */
    @Test
    void IDMTest() {
        // TODO: test IDM
    }

    /**
     * Test the property 'raceTime'
     */
    @Test
    void raceTimeTest() {
        // TODO: test raceTime
    }

    /**
     * Test the property 'lapsCompleted'
     */
    @Test
    void lapsCompletedTest() {
        // TODO: test lapsCompleted
    }

    /**
     * Test the property 'pitStops'
     */
    @Test
    void pitStopsTest() {
        // TODO: test pitStops
    }

    /**
     * Test the property 'bestLapTime'
     */
    @Test
    void bestLapTimeTest() {
        // TODO: test bestLapTime
    }

    /**
     * Test the property 'bestLapTimeRaw'
     */
    @Test
    void bestLapTimeRawTest() {
        // TODO: test bestLapTimeRaw
    }

    /**
     * Test the property 'bestLapColor'
     */
    @Test
    void bestLapColorTest() {
        // TODO: test bestLapColor
    }

    /**
     * Test the property 'avgSpeed'
     */
    @Test
    void avgSpeedTest() {
        // TODO: test avgSpeed
    }

    /**
     * Test the property 'bestPitTime'
     */
    @Test
    void bestPitTimeTest() {
        // TODO: test bestPitTime
    }

    /**
     * Test the property 'bestPitColor'
     */
    @Test
    void bestPitColorTest() {
        // TODO: test bestPitColor
    }

    /**
     * Test the property 'champs'
     */
    @Test
    void champsTest() {
        // TODO: test champs
    }

    /**
     * Test the property 'classified'
     */
    @Test
    void classifiedTest() {
        // TODO: test classified
    }

    /**
     * Test the property 'firstNotClassified'
     */
    @Test
    void firstNotClassifiedTest() {
        // TODO: test firstNotClassified
    }

}
