/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.jlobato.gpro.model.StandingsResponseDataGraphRangeSelectorButtonThemeStates;
import org.jlobato.gpro.model.StandingsResponseDataGraphRangeSelectorButtonThemeStyle;
import org.jlobato.gpro.model.StandingsResponseDataGraphScrollbarBarBackgroundColor;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for StandingsResponseDataGraphRangeSelectorButtonTheme
 */
class StandingsResponseDataGraphRangeSelectorButtonThemeTest {
    private final StandingsResponseDataGraphRangeSelectorButtonTheme model = new StandingsResponseDataGraphRangeSelectorButtonTheme();

    /**
     * Model tests for StandingsResponseDataGraphRangeSelectorButtonTheme
     */
    @Test
    void testStandingsResponseDataGraphRangeSelectorButtonTheme() {
        // TODO: test StandingsResponseDataGraphRangeSelectorButtonTheme
    }

    /**
     * Test the property 'fill'
     */
    @Test
    void fillTest() {
        // TODO: test fill
    }

    /**
     * Test the property 'stroke'
     */
    @Test
    void strokeTest() {
        // TODO: test stroke
    }

    /**
     * Test the property 'style'
     */
    @Test
    void styleTest() {
        // TODO: test style
    }

    /**
     * Test the property 'states'
     */
    @Test
    void statesTest() {
        // TODO: test states
    }

}
