/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.jlobato.gpro.model.EconomyHistoryGraphResponseDataGraph;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * EconomyHistoryGraphResponse
 */
@JsonPropertyOrder({
  EconomyHistoryGraphResponse.JSON_PROPERTY_LOADING_DATA_STATE,
  EconomyHistoryGraphResponse.JSON_PROPERTY_CUR_PAGE,
  EconomyHistoryGraphResponse.JSON_PROPERTY_TOT_PAGES,
  EconomyHistoryGraphResponse.JSON_PROPERTY_DATA_GRAPH,
  EconomyHistoryGraphResponse.JSON_PROPERTY_API_REQUESTS_REMAINING
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class EconomyHistoryGraphResponse {
  public static final String JSON_PROPERTY_LOADING_DATA_STATE = "loadingDataState";
  @jakarta.annotation.Nullable
  private Integer loadingDataState;

  public static final String JSON_PROPERTY_CUR_PAGE = "curPage";
  @jakarta.annotation.Nullable
  private Integer curPage;

  public static final String JSON_PROPERTY_TOT_PAGES = "totPages";
  @jakarta.annotation.Nullable
  private Integer totPages;

  public static final String JSON_PROPERTY_DATA_GRAPH = "dataGraph";
  @jakarta.annotation.Nullable
  private EconomyHistoryGraphResponseDataGraph dataGraph;

  public static final String JSON_PROPERTY_API_REQUESTS_REMAINING = "apiRequestsRemaining";
  @jakarta.annotation.Nullable
  private Integer apiRequestsRemaining;

  public EconomyHistoryGraphResponse() {
  }

  public EconomyHistoryGraphResponse loadingDataState(@jakarta.annotation.Nullable Integer loadingDataState) {
    
    this.loadingDataState = loadingDataState;
    return this;
  }

  /**
   * Get loadingDataState
   * @return loadingDataState
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOADING_DATA_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getLoadingDataState() {
    return loadingDataState;
  }


  @JsonProperty(JSON_PROPERTY_LOADING_DATA_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLoadingDataState(@jakarta.annotation.Nullable Integer loadingDataState) {
    this.loadingDataState = loadingDataState;
  }

  public EconomyHistoryGraphResponse curPage(@jakarta.annotation.Nullable Integer curPage) {
    
    this.curPage = curPage;
    return this;
  }

  /**
   * Get curPage
   * @return curPage
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CUR_PAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCurPage() {
    return curPage;
  }


  @JsonProperty(JSON_PROPERTY_CUR_PAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurPage(@jakarta.annotation.Nullable Integer curPage) {
    this.curPage = curPage;
  }

  public EconomyHistoryGraphResponse totPages(@jakarta.annotation.Nullable Integer totPages) {
    
    this.totPages = totPages;
    return this;
  }

  /**
   * Get totPages
   * @return totPages
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOT_PAGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTotPages() {
    return totPages;
  }


  @JsonProperty(JSON_PROPERTY_TOT_PAGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotPages(@jakarta.annotation.Nullable Integer totPages) {
    this.totPages = totPages;
  }

  public EconomyHistoryGraphResponse dataGraph(@jakarta.annotation.Nullable EconomyHistoryGraphResponseDataGraph dataGraph) {
    
    this.dataGraph = dataGraph;
    return this;
  }

  /**
   * Get dataGraph
   * @return dataGraph
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATA_GRAPH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EconomyHistoryGraphResponseDataGraph getDataGraph() {
    return dataGraph;
  }


  @JsonProperty(JSON_PROPERTY_DATA_GRAPH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDataGraph(@jakarta.annotation.Nullable EconomyHistoryGraphResponseDataGraph dataGraph) {
    this.dataGraph = dataGraph;
  }

  public EconomyHistoryGraphResponse apiRequestsRemaining(@jakarta.annotation.Nullable Integer apiRequestsRemaining) {
    
    this.apiRequestsRemaining = apiRequestsRemaining;
    return this;
  }

  /**
   * Get apiRequestsRemaining
   * @return apiRequestsRemaining
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_API_REQUESTS_REMAINING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getApiRequestsRemaining() {
    return apiRequestsRemaining;
  }


  @JsonProperty(JSON_PROPERTY_API_REQUESTS_REMAINING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApiRequestsRemaining(@jakarta.annotation.Nullable Integer apiRequestsRemaining) {
    this.apiRequestsRemaining = apiRequestsRemaining;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EconomyHistoryGraphResponse economyHistoryGraphResponse = (EconomyHistoryGraphResponse) o;
    return Objects.equals(this.loadingDataState, economyHistoryGraphResponse.loadingDataState) &&
        Objects.equals(this.curPage, economyHistoryGraphResponse.curPage) &&
        Objects.equals(this.totPages, economyHistoryGraphResponse.totPages) &&
        Objects.equals(this.dataGraph, economyHistoryGraphResponse.dataGraph) &&
        Objects.equals(this.apiRequestsRemaining, economyHistoryGraphResponse.apiRequestsRemaining);
  }

  @Override
  public int hashCode() {
    return Objects.hash(loadingDataState, curPage, totPages, dataGraph, apiRequestsRemaining);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EconomyHistoryGraphResponse {\n");
    sb.append("    loadingDataState: ").append(toIndentedString(loadingDataState)).append("\n");
    sb.append("    curPage: ").append(toIndentedString(curPage)).append("\n");
    sb.append("    totPages: ").append(toIndentedString(totPages)).append("\n");
    sb.append("    dataGraph: ").append(toIndentedString(dataGraph)).append("\n");
    sb.append("    apiRequestsRemaining: ").append(toIndentedString(apiRequestsRemaining)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

