/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.jlobato.gpro.model.EconomyHistoryESGraphResponseDataGraphPlotOptionsPieDataLabelsStyle;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * EconomyHistoryESGraphResponseDataGraphPlotOptionsPieDataLabels
 */
@JsonPropertyOrder({
  EconomyHistoryESGraphResponseDataGraphPlotOptionsPieDataLabels.JSON_PROPERTY_ENABLED,
  EconomyHistoryESGraphResponseDataGraphPlotOptionsPieDataLabels.JSON_PROPERTY_FORMAT,
  EconomyHistoryESGraphResponseDataGraphPlotOptionsPieDataLabels.JSON_PROPERTY_STYLE,
  EconomyHistoryESGraphResponseDataGraphPlotOptionsPieDataLabels.JSON_PROPERTY_CONNECTOR_COLOR
})
@JsonTypeName("EconomyHistoryESGraphResponse_dataGraph_plotOptions_pie_dataLabels")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class EconomyHistoryESGraphResponseDataGraphPlotOptionsPieDataLabels {
  public static final String JSON_PROPERTY_ENABLED = "enabled";
  @jakarta.annotation.Nullable
  private Integer enabled;

  public static final String JSON_PROPERTY_FORMAT = "format";
  @jakarta.annotation.Nullable
  private String format;

  public static final String JSON_PROPERTY_STYLE = "style";
  @jakarta.annotation.Nullable
  private EconomyHistoryESGraphResponseDataGraphPlotOptionsPieDataLabelsStyle style;

  public static final String JSON_PROPERTY_CONNECTOR_COLOR = "connectorColor";
  @jakarta.annotation.Nullable
  private String connectorColor;

  public EconomyHistoryESGraphResponseDataGraphPlotOptionsPieDataLabels() {
  }

  public EconomyHistoryESGraphResponseDataGraphPlotOptionsPieDataLabels enabled(@jakarta.annotation.Nullable Integer enabled) {
    
    this.enabled = enabled;
    return this;
  }

  /**
   * Get enabled
   * @return enabled
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getEnabled() {
    return enabled;
  }


  @JsonProperty(JSON_PROPERTY_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnabled(@jakarta.annotation.Nullable Integer enabled) {
    this.enabled = enabled;
  }

  public EconomyHistoryESGraphResponseDataGraphPlotOptionsPieDataLabels format(@jakarta.annotation.Nullable String format) {
    
    this.format = format;
    return this;
  }

  /**
   * Get format
   * @return format
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FORMAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFormat() {
    return format;
  }


  @JsonProperty(JSON_PROPERTY_FORMAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFormat(@jakarta.annotation.Nullable String format) {
    this.format = format;
  }

  public EconomyHistoryESGraphResponseDataGraphPlotOptionsPieDataLabels style(@jakarta.annotation.Nullable EconomyHistoryESGraphResponseDataGraphPlotOptionsPieDataLabelsStyle style) {
    
    this.style = style;
    return this;
  }

  /**
   * Get style
   * @return style
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STYLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EconomyHistoryESGraphResponseDataGraphPlotOptionsPieDataLabelsStyle getStyle() {
    return style;
  }


  @JsonProperty(JSON_PROPERTY_STYLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStyle(@jakarta.annotation.Nullable EconomyHistoryESGraphResponseDataGraphPlotOptionsPieDataLabelsStyle style) {
    this.style = style;
  }

  public EconomyHistoryESGraphResponseDataGraphPlotOptionsPieDataLabels connectorColor(@jakarta.annotation.Nullable String connectorColor) {
    
    this.connectorColor = connectorColor;
    return this;
  }

  /**
   * Get connectorColor
   * @return connectorColor
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONNECTOR_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getConnectorColor() {
    return connectorColor;
  }


  @JsonProperty(JSON_PROPERTY_CONNECTOR_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConnectorColor(@jakarta.annotation.Nullable String connectorColor) {
    this.connectorColor = connectorColor;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EconomyHistoryESGraphResponseDataGraphPlotOptionsPieDataLabels economyHistoryESGraphResponseDataGraphPlotOptionsPieDataLabels = (EconomyHistoryESGraphResponseDataGraphPlotOptionsPieDataLabels) o;
    return Objects.equals(this.enabled, economyHistoryESGraphResponseDataGraphPlotOptionsPieDataLabels.enabled) &&
        Objects.equals(this.format, economyHistoryESGraphResponseDataGraphPlotOptionsPieDataLabels.format) &&
        Objects.equals(this.style, economyHistoryESGraphResponseDataGraphPlotOptionsPieDataLabels.style) &&
        Objects.equals(this.connectorColor, economyHistoryESGraphResponseDataGraphPlotOptionsPieDataLabels.connectorColor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enabled, format, style, connectorColor);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EconomyHistoryESGraphResponseDataGraphPlotOptionsPieDataLabels {\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("    style: ").append(toIndentedString(style)).append("\n");
    sb.append("    connectorColor: ").append(toIndentedString(connectorColor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

