/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.jlobato.gpro.model.CalendarResponseGroupsInner;
import org.jlobato.gpro.model.History500OBRResponseManagersInner;
import org.jlobato.gpro.model.History500OBRResponseSectionsInner;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * History500OBRResponse
 */
@JsonPropertyOrder({
  History500OBRResponse.JSON_PROPERTY_LOADING_DATA_STATE,
  History500OBRResponse.JSON_PROPERTY_SECTIONS,
  History500OBRResponse.JSON_PROPERTY_GROUP,
  History500OBRResponse.JSON_PROPERTY_REQUESTED_SEASON,
  History500OBRResponse.JSON_PROPERTY_SEASON,
  History500OBRResponse.JSON_PROPERTY_TITLE,
  History500OBRResponse.JSON_PROPERTY_STATS_TYPE,
  History500OBRResponse.JSON_PROPERTY_MANAGERS,
  History500OBRResponse.JSON_PROPERTY_GROUPS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class History500OBRResponse {
  public static final String JSON_PROPERTY_LOADING_DATA_STATE = "loadingDataState";
  @jakarta.annotation.Nullable
  private String loadingDataState;

  public static final String JSON_PROPERTY_SECTIONS = "sections";
  @jakarta.annotation.Nullable
  private List<History500OBRResponseSectionsInner> sections = new ArrayList<>();

  public static final String JSON_PROPERTY_GROUP = "group";
  @jakarta.annotation.Nullable
  private String group;

  public static final String JSON_PROPERTY_REQUESTED_SEASON = "requestedSeason";
  @jakarta.annotation.Nullable
  private Integer requestedSeason;

  public static final String JSON_PROPERTY_SEASON = "season";
  @jakarta.annotation.Nullable
  private Integer season;

  public static final String JSON_PROPERTY_TITLE = "title";
  @jakarta.annotation.Nullable
  private String title;

  public static final String JSON_PROPERTY_STATS_TYPE = "statsType";
  @jakarta.annotation.Nullable
  private String statsType;

  public static final String JSON_PROPERTY_MANAGERS = "managers";
  @jakarta.annotation.Nullable
  private List<History500OBRResponseManagersInner> managers = new ArrayList<>();

  public static final String JSON_PROPERTY_GROUPS = "groups";
  @jakarta.annotation.Nullable
  private List<CalendarResponseGroupsInner> groups = new ArrayList<>();

  public History500OBRResponse() {
  }

  public History500OBRResponse loadingDataState(@jakarta.annotation.Nullable String loadingDataState) {
    
    this.loadingDataState = loadingDataState;
    return this;
  }

  /**
   * Get loadingDataState
   * @return loadingDataState
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOADING_DATA_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLoadingDataState() {
    return loadingDataState;
  }


  @JsonProperty(JSON_PROPERTY_LOADING_DATA_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLoadingDataState(@jakarta.annotation.Nullable String loadingDataState) {
    this.loadingDataState = loadingDataState;
  }

  public History500OBRResponse sections(@jakarta.annotation.Nullable List<History500OBRResponseSectionsInner> sections) {
    
    this.sections = sections;
    return this;
  }

  public History500OBRResponse addSectionsItem(History500OBRResponseSectionsInner sectionsItem) {
    if (this.sections == null) {
      this.sections = new ArrayList<>();
    }
    this.sections.add(sectionsItem);
    return this;
  }

  /**
   * Get sections
   * @return sections
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SECTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<History500OBRResponseSectionsInner> getSections() {
    return sections;
  }


  @JsonProperty(JSON_PROPERTY_SECTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSections(@jakarta.annotation.Nullable List<History500OBRResponseSectionsInner> sections) {
    this.sections = sections;
  }

  public History500OBRResponse group(@jakarta.annotation.Nullable String group) {
    
    this.group = group;
    return this;
  }

  /**
   * Get group
   * @return group
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GROUP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGroup() {
    return group;
  }


  @JsonProperty(JSON_PROPERTY_GROUP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGroup(@jakarta.annotation.Nullable String group) {
    this.group = group;
  }

  public History500OBRResponse requestedSeason(@jakarta.annotation.Nullable Integer requestedSeason) {
    
    this.requestedSeason = requestedSeason;
    return this;
  }

  /**
   * Get requestedSeason
   * @return requestedSeason
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REQUESTED_SEASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRequestedSeason() {
    return requestedSeason;
  }


  @JsonProperty(JSON_PROPERTY_REQUESTED_SEASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRequestedSeason(@jakarta.annotation.Nullable Integer requestedSeason) {
    this.requestedSeason = requestedSeason;
  }

  public History500OBRResponse season(@jakarta.annotation.Nullable Integer season) {
    
    this.season = season;
    return this;
  }

  /**
   * Get season
   * @return season
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSeason() {
    return season;
  }


  @JsonProperty(JSON_PROPERTY_SEASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeason(@jakarta.annotation.Nullable Integer season) {
    this.season = season;
  }

  public History500OBRResponse title(@jakarta.annotation.Nullable String title) {
    
    this.title = title;
    return this;
  }

  /**
   * Get title
   * @return title
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTitle() {
    return title;
  }


  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTitle(@jakarta.annotation.Nullable String title) {
    this.title = title;
  }

  public History500OBRResponse statsType(@jakarta.annotation.Nullable String statsType) {
    
    this.statsType = statsType;
    return this;
  }

  /**
   * Get statsType
   * @return statsType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATS_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatsType() {
    return statsType;
  }


  @JsonProperty(JSON_PROPERTY_STATS_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatsType(@jakarta.annotation.Nullable String statsType) {
    this.statsType = statsType;
  }

  public History500OBRResponse managers(@jakarta.annotation.Nullable List<History500OBRResponseManagersInner> managers) {
    
    this.managers = managers;
    return this;
  }

  public History500OBRResponse addManagersItem(History500OBRResponseManagersInner managersItem) {
    if (this.managers == null) {
      this.managers = new ArrayList<>();
    }
    this.managers.add(managersItem);
    return this;
  }

  /**
   * Get managers
   * @return managers
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MANAGERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<History500OBRResponseManagersInner> getManagers() {
    return managers;
  }


  @JsonProperty(JSON_PROPERTY_MANAGERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManagers(@jakarta.annotation.Nullable List<History500OBRResponseManagersInner> managers) {
    this.managers = managers;
  }

  public History500OBRResponse groups(@jakarta.annotation.Nullable List<CalendarResponseGroupsInner> groups) {
    
    this.groups = groups;
    return this;
  }

  public History500OBRResponse addGroupsItem(CalendarResponseGroupsInner groupsItem) {
    if (this.groups == null) {
      this.groups = new ArrayList<>();
    }
    this.groups.add(groupsItem);
    return this;
  }

  /**
   * Get groups
   * @return groups
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GROUPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CalendarResponseGroupsInner> getGroups() {
    return groups;
  }


  @JsonProperty(JSON_PROPERTY_GROUPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGroups(@jakarta.annotation.Nullable List<CalendarResponseGroupsInner> groups) {
    this.groups = groups;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    History500OBRResponse history500OBRResponse = (History500OBRResponse) o;
    return Objects.equals(this.loadingDataState, history500OBRResponse.loadingDataState) &&
        Objects.equals(this.sections, history500OBRResponse.sections) &&
        Objects.equals(this.group, history500OBRResponse.group) &&
        Objects.equals(this.requestedSeason, history500OBRResponse.requestedSeason) &&
        Objects.equals(this.season, history500OBRResponse.season) &&
        Objects.equals(this.title, history500OBRResponse.title) &&
        Objects.equals(this.statsType, history500OBRResponse.statsType) &&
        Objects.equals(this.managers, history500OBRResponse.managers) &&
        Objects.equals(this.groups, history500OBRResponse.groups);
  }

  @Override
  public int hashCode() {
    return Objects.hash(loadingDataState, sections, group, requestedSeason, season, title, statsType, managers, groups);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class History500OBRResponse {\n");
    sb.append("    loadingDataState: ").append(toIndentedString(loadingDataState)).append("\n");
    sb.append("    sections: ").append(toIndentedString(sections)).append("\n");
    sb.append("    group: ").append(toIndentedString(group)).append("\n");
    sb.append("    requestedSeason: ").append(toIndentedString(requestedSeason)).append("\n");
    sb.append("    season: ").append(toIndentedString(season)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    statsType: ").append(toIndentedString(statsType)).append("\n");
    sb.append("    managers: ").append(toIndentedString(managers)).append("\n");
    sb.append("    groups: ").append(toIndentedString(groups)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

