/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.jlobato.gpro.model.HistoryGroupStandingsResponseManagersInnerResultsInner;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * HistoryGroupStandingsResponseManagersInner
 */
@JsonPropertyOrder({
  HistoryGroupStandingsResponseManagersInner.JSON_PROPERTY_NAME,
  HistoryGroupStandingsResponseManagersInner.JSON_PROPERTY_POS,
  HistoryGroupStandingsResponseManagersInner.JSON_PROPERTY_BG_COLOR,
  HistoryGroupStandingsResponseManagersInner.JSON_PROPERTY_MAN_ARROW,
  HistoryGroupStandingsResponseManagersInner.JSON_PROPERTY_MAN_POS_CHANGE,
  HistoryGroupStandingsResponseManagersInner.JSON_PROPERTY_TYRES,
  HistoryGroupStandingsResponseManagersInner.JSON_PROPERTY_NAT,
  HistoryGroupStandingsResponseManagersInner.JSON_PROPERTY_NAT_CODE,
  HistoryGroupStandingsResponseManagersInner.JSON_PROPERTY_I_D_M,
  HistoryGroupStandingsResponseManagersInner.JSON_PROPERTY_CHAMPS,
  HistoryGroupStandingsResponseManagersInner.JSON_PROPERTY_CASH,
  HistoryGroupStandingsResponseManagersInner.JSON_PROPERTY_RETIRED,
  HistoryGroupStandingsResponseManagersInner.JSON_PROPERTY_WENT_ROOKIE,
  HistoryGroupStandingsResponseManagersInner.JSON_PROPERTY_DID_SOFT_RESET,
  HistoryGroupStandingsResponseManagersInner.JSON_PROPERTY_RESULTS,
  HistoryGroupStandingsResponseManagersInner.JSON_PROPERTY_PTS
})
@JsonTypeName("HistoryGroupStandingsResponse_managers_inner")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class HistoryGroupStandingsResponseManagersInner {
  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_POS = "pos";
  @jakarta.annotation.Nullable
  private String pos;

  public static final String JSON_PROPERTY_BG_COLOR = "bgColor";
  @jakarta.annotation.Nullable
  private String bgColor;

  public static final String JSON_PROPERTY_MAN_ARROW = "manArrow";
  @jakarta.annotation.Nullable
  private String manArrow;

  public static final String JSON_PROPERTY_MAN_POS_CHANGE = "manPosChange";
  @jakarta.annotation.Nullable
  private String manPosChange;

  public static final String JSON_PROPERTY_TYRES = "tyres";
  @jakarta.annotation.Nullable
  private String tyres;

  public static final String JSON_PROPERTY_NAT = "nat";
  @jakarta.annotation.Nullable
  private String nat;

  public static final String JSON_PROPERTY_NAT_CODE = "natCode";
  @jakarta.annotation.Nullable
  private String natCode;

  public static final String JSON_PROPERTY_I_D_M = "IDM";
  @jakarta.annotation.Nullable
  private Integer IDM;

  public static final String JSON_PROPERTY_CHAMPS = "champs";
  @jakarta.annotation.Nullable
  private Integer champs;

  public static final String JSON_PROPERTY_CASH = "cash";
  @jakarta.annotation.Nullable
  private Integer cash;

  public static final String JSON_PROPERTY_RETIRED = "retired";
  @jakarta.annotation.Nullable
  private Integer retired;

  public static final String JSON_PROPERTY_WENT_ROOKIE = "wentRookie";
  @jakarta.annotation.Nullable
  private Integer wentRookie;

  public static final String JSON_PROPERTY_DID_SOFT_RESET = "didSoftReset";
  @jakarta.annotation.Nullable
  private Integer didSoftReset;

  public static final String JSON_PROPERTY_RESULTS = "results";
  @jakarta.annotation.Nullable
  private List<HistoryGroupStandingsResponseManagersInnerResultsInner> results = new ArrayList<>();

  public static final String JSON_PROPERTY_PTS = "pts";
  @jakarta.annotation.Nullable
  private String pts;

  public HistoryGroupStandingsResponseManagersInner() {
  }

  public HistoryGroupStandingsResponseManagersInner name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  public HistoryGroupStandingsResponseManagersInner pos(@jakarta.annotation.Nullable String pos) {
    
    this.pos = pos;
    return this;
  }

  /**
   * Get pos
   * @return pos
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPos() {
    return pos;
  }


  @JsonProperty(JSON_PROPERTY_POS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPos(@jakarta.annotation.Nullable String pos) {
    this.pos = pos;
  }

  public HistoryGroupStandingsResponseManagersInner bgColor(@jakarta.annotation.Nullable String bgColor) {
    
    this.bgColor = bgColor;
    return this;
  }

  /**
   * Get bgColor
   * @return bgColor
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BG_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBgColor() {
    return bgColor;
  }


  @JsonProperty(JSON_PROPERTY_BG_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBgColor(@jakarta.annotation.Nullable String bgColor) {
    this.bgColor = bgColor;
  }

  public HistoryGroupStandingsResponseManagersInner manArrow(@jakarta.annotation.Nullable String manArrow) {
    
    this.manArrow = manArrow;
    return this;
  }

  /**
   * Get manArrow
   * @return manArrow
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MAN_ARROW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getManArrow() {
    return manArrow;
  }


  @JsonProperty(JSON_PROPERTY_MAN_ARROW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManArrow(@jakarta.annotation.Nullable String manArrow) {
    this.manArrow = manArrow;
  }

  public HistoryGroupStandingsResponseManagersInner manPosChange(@jakarta.annotation.Nullable String manPosChange) {
    
    this.manPosChange = manPosChange;
    return this;
  }

  /**
   * Get manPosChange
   * @return manPosChange
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MAN_POS_CHANGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getManPosChange() {
    return manPosChange;
  }


  @JsonProperty(JSON_PROPERTY_MAN_POS_CHANGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManPosChange(@jakarta.annotation.Nullable String manPosChange) {
    this.manPosChange = manPosChange;
  }

  public HistoryGroupStandingsResponseManagersInner tyres(@jakarta.annotation.Nullable String tyres) {
    
    this.tyres = tyres;
    return this;
  }

  /**
   * Get tyres
   * @return tyres
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYRES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTyres() {
    return tyres;
  }


  @JsonProperty(JSON_PROPERTY_TYRES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTyres(@jakarta.annotation.Nullable String tyres) {
    this.tyres = tyres;
  }

  public HistoryGroupStandingsResponseManagersInner nat(@jakarta.annotation.Nullable String nat) {
    
    this.nat = nat;
    return this;
  }

  /**
   * Get nat
   * @return nat
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNat() {
    return nat;
  }


  @JsonProperty(JSON_PROPERTY_NAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNat(@jakarta.annotation.Nullable String nat) {
    this.nat = nat;
  }

  public HistoryGroupStandingsResponseManagersInner natCode(@jakarta.annotation.Nullable String natCode) {
    
    this.natCode = natCode;
    return this;
  }

  /**
   * Get natCode
   * @return natCode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNatCode() {
    return natCode;
  }


  @JsonProperty(JSON_PROPERTY_NAT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNatCode(@jakarta.annotation.Nullable String natCode) {
    this.natCode = natCode;
  }

  public HistoryGroupStandingsResponseManagersInner IDM(@jakarta.annotation.Nullable Integer IDM) {
    
    this.IDM = IDM;
    return this;
  }

  /**
   * Get IDM
   * @return IDM
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_I_D_M)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getIDM() {
    return IDM;
  }


  @JsonProperty(JSON_PROPERTY_I_D_M)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIDM(@jakarta.annotation.Nullable Integer IDM) {
    this.IDM = IDM;
  }

  public HistoryGroupStandingsResponseManagersInner champs(@jakarta.annotation.Nullable Integer champs) {
    
    this.champs = champs;
    return this;
  }

  /**
   * Get champs
   * @return champs
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHAMPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getChamps() {
    return champs;
  }


  @JsonProperty(JSON_PROPERTY_CHAMPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChamps(@jakarta.annotation.Nullable Integer champs) {
    this.champs = champs;
  }

  public HistoryGroupStandingsResponseManagersInner cash(@jakarta.annotation.Nullable Integer cash) {
    
    this.cash = cash;
    return this;
  }

  /**
   * Get cash
   * @return cash
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCash() {
    return cash;
  }


  @JsonProperty(JSON_PROPERTY_CASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCash(@jakarta.annotation.Nullable Integer cash) {
    this.cash = cash;
  }

  public HistoryGroupStandingsResponseManagersInner retired(@jakarta.annotation.Nullable Integer retired) {
    
    this.retired = retired;
    return this;
  }

  /**
   * Get retired
   * @return retired
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RETIRED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRetired() {
    return retired;
  }


  @JsonProperty(JSON_PROPERTY_RETIRED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRetired(@jakarta.annotation.Nullable Integer retired) {
    this.retired = retired;
  }

  public HistoryGroupStandingsResponseManagersInner wentRookie(@jakarta.annotation.Nullable Integer wentRookie) {
    
    this.wentRookie = wentRookie;
    return this;
  }

  /**
   * Get wentRookie
   * @return wentRookie
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WENT_ROOKIE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getWentRookie() {
    return wentRookie;
  }


  @JsonProperty(JSON_PROPERTY_WENT_ROOKIE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWentRookie(@jakarta.annotation.Nullable Integer wentRookie) {
    this.wentRookie = wentRookie;
  }

  public HistoryGroupStandingsResponseManagersInner didSoftReset(@jakarta.annotation.Nullable Integer didSoftReset) {
    
    this.didSoftReset = didSoftReset;
    return this;
  }

  /**
   * Get didSoftReset
   * @return didSoftReset
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DID_SOFT_RESET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getDidSoftReset() {
    return didSoftReset;
  }


  @JsonProperty(JSON_PROPERTY_DID_SOFT_RESET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDidSoftReset(@jakarta.annotation.Nullable Integer didSoftReset) {
    this.didSoftReset = didSoftReset;
  }

  public HistoryGroupStandingsResponseManagersInner results(@jakarta.annotation.Nullable List<HistoryGroupStandingsResponseManagersInnerResultsInner> results) {
    
    this.results = results;
    return this;
  }

  public HistoryGroupStandingsResponseManagersInner addResultsItem(HistoryGroupStandingsResponseManagersInnerResultsInner resultsItem) {
    if (this.results == null) {
      this.results = new ArrayList<>();
    }
    this.results.add(resultsItem);
    return this;
  }

  /**
   * Get results
   * @return results
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESULTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<HistoryGroupStandingsResponseManagersInnerResultsInner> getResults() {
    return results;
  }


  @JsonProperty(JSON_PROPERTY_RESULTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResults(@jakarta.annotation.Nullable List<HistoryGroupStandingsResponseManagersInnerResultsInner> results) {
    this.results = results;
  }

  public HistoryGroupStandingsResponseManagersInner pts(@jakarta.annotation.Nullable String pts) {
    
    this.pts = pts;
    return this;
  }

  /**
   * Get pts
   * @return pts
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPts() {
    return pts;
  }


  @JsonProperty(JSON_PROPERTY_PTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPts(@jakarta.annotation.Nullable String pts) {
    this.pts = pts;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HistoryGroupStandingsResponseManagersInner historyGroupStandingsResponseManagersInner = (HistoryGroupStandingsResponseManagersInner) o;
    return Objects.equals(this.name, historyGroupStandingsResponseManagersInner.name) &&
        Objects.equals(this.pos, historyGroupStandingsResponseManagersInner.pos) &&
        Objects.equals(this.bgColor, historyGroupStandingsResponseManagersInner.bgColor) &&
        Objects.equals(this.manArrow, historyGroupStandingsResponseManagersInner.manArrow) &&
        Objects.equals(this.manPosChange, historyGroupStandingsResponseManagersInner.manPosChange) &&
        Objects.equals(this.tyres, historyGroupStandingsResponseManagersInner.tyres) &&
        Objects.equals(this.nat, historyGroupStandingsResponseManagersInner.nat) &&
        Objects.equals(this.natCode, historyGroupStandingsResponseManagersInner.natCode) &&
        Objects.equals(this.IDM, historyGroupStandingsResponseManagersInner.IDM) &&
        Objects.equals(this.champs, historyGroupStandingsResponseManagersInner.champs) &&
        Objects.equals(this.cash, historyGroupStandingsResponseManagersInner.cash) &&
        Objects.equals(this.retired, historyGroupStandingsResponseManagersInner.retired) &&
        Objects.equals(this.wentRookie, historyGroupStandingsResponseManagersInner.wentRookie) &&
        Objects.equals(this.didSoftReset, historyGroupStandingsResponseManagersInner.didSoftReset) &&
        Objects.equals(this.results, historyGroupStandingsResponseManagersInner.results) &&
        Objects.equals(this.pts, historyGroupStandingsResponseManagersInner.pts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, pos, bgColor, manArrow, manPosChange, tyres, nat, natCode, IDM, champs, cash, retired, wentRookie, didSoftReset, results, pts);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HistoryGroupStandingsResponseManagersInner {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    pos: ").append(toIndentedString(pos)).append("\n");
    sb.append("    bgColor: ").append(toIndentedString(bgColor)).append("\n");
    sb.append("    manArrow: ").append(toIndentedString(manArrow)).append("\n");
    sb.append("    manPosChange: ").append(toIndentedString(manPosChange)).append("\n");
    sb.append("    tyres: ").append(toIndentedString(tyres)).append("\n");
    sb.append("    nat: ").append(toIndentedString(nat)).append("\n");
    sb.append("    natCode: ").append(toIndentedString(natCode)).append("\n");
    sb.append("    IDM: ").append(toIndentedString(IDM)).append("\n");
    sb.append("    champs: ").append(toIndentedString(champs)).append("\n");
    sb.append("    cash: ").append(toIndentedString(cash)).append("\n");
    sb.append("    retired: ").append(toIndentedString(retired)).append("\n");
    sb.append("    wentRookie: ").append(toIndentedString(wentRookie)).append("\n");
    sb.append("    didSoftReset: ").append(toIndentedString(didSoftReset)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("    pts: ").append(toIndentedString(pts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

