/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.jlobato.gpro.model.HistoryCalendarResponseManagersInnerWinner;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * HistoryCalendarResponseManagersInner
 */
@JsonPropertyOrder({
  HistoryCalendarResponseManagersInner.JSON_PROPERTY_WINNER,
  HistoryCalendarResponseManagersInner.JSON_PROPERTY_EVENT_TYPE,
  HistoryCalendarResponseManagersInner.JSON_PROPERTY_POS,
  HistoryCalendarResponseManagersInner.JSON_PROPERTY_TRACK_NAME,
  HistoryCalendarResponseManagersInner.JSON_PROPERTY_NAT_CODE,
  HistoryCalendarResponseManagersInner.JSON_PROPERTY_IS_TEST_TRACK,
  HistoryCalendarResponseManagersInner.JSON_PROPERTY_DATE_EVENT,
  HistoryCalendarResponseManagersInner.JSON_PROPERTY_TRACK_ID
})
@JsonTypeName("HistoryCalendarResponse_managers_inner")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class HistoryCalendarResponseManagersInner {
  public static final String JSON_PROPERTY_WINNER = "winner";
  @jakarta.annotation.Nullable
  private HistoryCalendarResponseManagersInnerWinner winner;

  public static final String JSON_PROPERTY_EVENT_TYPE = "eventType";
  @jakarta.annotation.Nullable
  private String eventType;

  public static final String JSON_PROPERTY_POS = "pos";
  @jakarta.annotation.Nullable
  private String pos;

  public static final String JSON_PROPERTY_TRACK_NAME = "trackName";
  @jakarta.annotation.Nullable
  private String trackName;

  public static final String JSON_PROPERTY_NAT_CODE = "natCode";
  @jakarta.annotation.Nullable
  private String natCode;

  public static final String JSON_PROPERTY_IS_TEST_TRACK = "isTestTrack";
  @jakarta.annotation.Nullable
  private Integer isTestTrack;

  public static final String JSON_PROPERTY_DATE_EVENT = "dateEvent";
  @jakarta.annotation.Nullable
  private String dateEvent;

  public static final String JSON_PROPERTY_TRACK_ID = "trackId";
  @jakarta.annotation.Nullable
  private String trackId;

  public HistoryCalendarResponseManagersInner() {
  }

  public HistoryCalendarResponseManagersInner winner(@jakarta.annotation.Nullable HistoryCalendarResponseManagersInnerWinner winner) {
    
    this.winner = winner;
    return this;
  }

  /**
   * Get winner
   * @return winner
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WINNER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public HistoryCalendarResponseManagersInnerWinner getWinner() {
    return winner;
  }


  @JsonProperty(JSON_PROPERTY_WINNER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWinner(@jakarta.annotation.Nullable HistoryCalendarResponseManagersInnerWinner winner) {
    this.winner = winner;
  }

  public HistoryCalendarResponseManagersInner eventType(@jakarta.annotation.Nullable String eventType) {
    
    this.eventType = eventType;
    return this;
  }

  /**
   * Get eventType
   * @return eventType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEventType() {
    return eventType;
  }


  @JsonProperty(JSON_PROPERTY_EVENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEventType(@jakarta.annotation.Nullable String eventType) {
    this.eventType = eventType;
  }

  public HistoryCalendarResponseManagersInner pos(@jakarta.annotation.Nullable String pos) {
    
    this.pos = pos;
    return this;
  }

  /**
   * Get pos
   * @return pos
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPos() {
    return pos;
  }


  @JsonProperty(JSON_PROPERTY_POS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPos(@jakarta.annotation.Nullable String pos) {
    this.pos = pos;
  }

  public HistoryCalendarResponseManagersInner trackName(@jakarta.annotation.Nullable String trackName) {
    
    this.trackName = trackName;
    return this;
  }

  /**
   * Get trackName
   * @return trackName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRACK_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTrackName() {
    return trackName;
  }


  @JsonProperty(JSON_PROPERTY_TRACK_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrackName(@jakarta.annotation.Nullable String trackName) {
    this.trackName = trackName;
  }

  public HistoryCalendarResponseManagersInner natCode(@jakarta.annotation.Nullable String natCode) {
    
    this.natCode = natCode;
    return this;
  }

  /**
   * Get natCode
   * @return natCode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNatCode() {
    return natCode;
  }


  @JsonProperty(JSON_PROPERTY_NAT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNatCode(@jakarta.annotation.Nullable String natCode) {
    this.natCode = natCode;
  }

  public HistoryCalendarResponseManagersInner isTestTrack(@jakarta.annotation.Nullable Integer isTestTrack) {
    
    this.isTestTrack = isTestTrack;
    return this;
  }

  /**
   * Get isTestTrack
   * @return isTestTrack
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_TEST_TRACK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getIsTestTrack() {
    return isTestTrack;
  }


  @JsonProperty(JSON_PROPERTY_IS_TEST_TRACK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsTestTrack(@jakarta.annotation.Nullable Integer isTestTrack) {
    this.isTestTrack = isTestTrack;
  }

  public HistoryCalendarResponseManagersInner dateEvent(@jakarta.annotation.Nullable String dateEvent) {
    
    this.dateEvent = dateEvent;
    return this;
  }

  /**
   * Get dateEvent
   * @return dateEvent
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATE_EVENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDateEvent() {
    return dateEvent;
  }


  @JsonProperty(JSON_PROPERTY_DATE_EVENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDateEvent(@jakarta.annotation.Nullable String dateEvent) {
    this.dateEvent = dateEvent;
  }

  public HistoryCalendarResponseManagersInner trackId(@jakarta.annotation.Nullable String trackId) {
    
    this.trackId = trackId;
    return this;
  }

  /**
   * Get trackId
   * @return trackId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRACK_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTrackId() {
    return trackId;
  }


  @JsonProperty(JSON_PROPERTY_TRACK_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrackId(@jakarta.annotation.Nullable String trackId) {
    this.trackId = trackId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HistoryCalendarResponseManagersInner historyCalendarResponseManagersInner = (HistoryCalendarResponseManagersInner) o;
    return Objects.equals(this.winner, historyCalendarResponseManagersInner.winner) &&
        Objects.equals(this.eventType, historyCalendarResponseManagersInner.eventType) &&
        Objects.equals(this.pos, historyCalendarResponseManagersInner.pos) &&
        Objects.equals(this.trackName, historyCalendarResponseManagersInner.trackName) &&
        Objects.equals(this.natCode, historyCalendarResponseManagersInner.natCode) &&
        Objects.equals(this.isTestTrack, historyCalendarResponseManagersInner.isTestTrack) &&
        Objects.equals(this.dateEvent, historyCalendarResponseManagersInner.dateEvent) &&
        Objects.equals(this.trackId, historyCalendarResponseManagersInner.trackId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(winner, eventType, pos, trackName, natCode, isTestTrack, dateEvent, trackId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HistoryCalendarResponseManagersInner {\n");
    sb.append("    winner: ").append(toIndentedString(winner)).append("\n");
    sb.append("    eventType: ").append(toIndentedString(eventType)).append("\n");
    sb.append("    pos: ").append(toIndentedString(pos)).append("\n");
    sb.append("    trackName: ").append(toIndentedString(trackName)).append("\n");
    sb.append("    natCode: ").append(toIndentedString(natCode)).append("\n");
    sb.append("    isTestTrack: ").append(toIndentedString(isTestTrack)).append("\n");
    sb.append("    dateEvent: ").append(toIndentedString(dateEvent)).append("\n");
    sb.append("    trackId: ").append(toIndentedString(trackId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

