/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * LastTransfersResponseDriverTransfersInner
 */
@JsonPropertyOrder({
  LastTransfersResponseDriverTransfersInner.JSON_PROPERTY_IDX,
  LastTransfersResponseDriverTransfersInner.JSON_PROPERTY_NAME,
  LastTransfersResponseDriverTransfersInner.JSON_PROPERTY_NAT_CODE,
  LastTransfersResponseDriverTransfersInner.JSON_PROPERTY_I_D_M,
  LastTransfersResponseDriverTransfersInner.JSON_PROPERTY_CHAMPS,
  LastTransfersResponseDriverTransfersInner.JSON_PROPERTY_GROUP_ID,
  LastTransfersResponseDriverTransfersInner.JSON_PROPERTY_GROUP_ID_SHORT,
  LastTransfersResponseDriverTransfersInner.JSON_PROPERTY_GROUP_ORDER_ID,
  LastTransfersResponseDriverTransfersInner.JSON_PROPERTY_STAFF_ID,
  LastTransfersResponseDriverTransfersInner.JSON_PROPERTY_STAFF_NAME,
  LastTransfersResponseDriverTransfersInner.JSON_PROPERTY_STAFF_COLOR,
  LastTransfersResponseDriverTransfersInner.JSON_PROPERTY_RACES,
  LastTransfersResponseDriverTransfersInner.JSON_PROPERTY_SALARY
})
@JsonTypeName("LastTransfersResponse_driverTransfers_inner")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class LastTransfersResponseDriverTransfersInner {
  public static final String JSON_PROPERTY_IDX = "idx";
  @jakarta.annotation.Nullable
  private String idx;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_NAT_CODE = "natCode";
  @jakarta.annotation.Nullable
  private String natCode;

  public static final String JSON_PROPERTY_I_D_M = "IDM";
  @jakarta.annotation.Nullable
  private Integer IDM;

  public static final String JSON_PROPERTY_CHAMPS = "champs";
  @jakarta.annotation.Nullable
  private String champs;

  public static final String JSON_PROPERTY_GROUP_ID = "groupId";
  @jakarta.annotation.Nullable
  private String groupId;

  public static final String JSON_PROPERTY_GROUP_ID_SHORT = "groupIdShort";
  @jakarta.annotation.Nullable
  private String groupIdShort;

  public static final String JSON_PROPERTY_GROUP_ORDER_ID = "groupOrderId";
  @jakarta.annotation.Nullable
  private String groupOrderId;

  public static final String JSON_PROPERTY_STAFF_ID = "staffId";
  @jakarta.annotation.Nullable
  private String staffId;

  public static final String JSON_PROPERTY_STAFF_NAME = "staffName";
  @jakarta.annotation.Nullable
  private String staffName;

  public static final String JSON_PROPERTY_STAFF_COLOR = "staffColor";
  @jakarta.annotation.Nullable
  private String staffColor;

  public static final String JSON_PROPERTY_RACES = "races";
  @jakarta.annotation.Nullable
  private String races;

  public static final String JSON_PROPERTY_SALARY = "salary";
  @jakarta.annotation.Nullable
  private String salary;

  public LastTransfersResponseDriverTransfersInner() {
  }

  public LastTransfersResponseDriverTransfersInner idx(@jakarta.annotation.Nullable String idx) {
    
    this.idx = idx;
    return this;
  }

  /**
   * Get idx
   * @return idx
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IDX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIdx() {
    return idx;
  }


  @JsonProperty(JSON_PROPERTY_IDX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdx(@jakarta.annotation.Nullable String idx) {
    this.idx = idx;
  }

  public LastTransfersResponseDriverTransfersInner name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  public LastTransfersResponseDriverTransfersInner natCode(@jakarta.annotation.Nullable String natCode) {
    
    this.natCode = natCode;
    return this;
  }

  /**
   * Get natCode
   * @return natCode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNatCode() {
    return natCode;
  }


  @JsonProperty(JSON_PROPERTY_NAT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNatCode(@jakarta.annotation.Nullable String natCode) {
    this.natCode = natCode;
  }

  public LastTransfersResponseDriverTransfersInner IDM(@jakarta.annotation.Nullable Integer IDM) {
    
    this.IDM = IDM;
    return this;
  }

  /**
   * Get IDM
   * @return IDM
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_I_D_M)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getIDM() {
    return IDM;
  }


  @JsonProperty(JSON_PROPERTY_I_D_M)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIDM(@jakarta.annotation.Nullable Integer IDM) {
    this.IDM = IDM;
  }

  public LastTransfersResponseDriverTransfersInner champs(@jakarta.annotation.Nullable String champs) {
    
    this.champs = champs;
    return this;
  }

  /**
   * Get champs
   * @return champs
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHAMPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getChamps() {
    return champs;
  }


  @JsonProperty(JSON_PROPERTY_CHAMPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChamps(@jakarta.annotation.Nullable String champs) {
    this.champs = champs;
  }

  public LastTransfersResponseDriverTransfersInner groupId(@jakarta.annotation.Nullable String groupId) {
    
    this.groupId = groupId;
    return this;
  }

  /**
   * Get groupId
   * @return groupId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GROUP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGroupId() {
    return groupId;
  }


  @JsonProperty(JSON_PROPERTY_GROUP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGroupId(@jakarta.annotation.Nullable String groupId) {
    this.groupId = groupId;
  }

  public LastTransfersResponseDriverTransfersInner groupIdShort(@jakarta.annotation.Nullable String groupIdShort) {
    
    this.groupIdShort = groupIdShort;
    return this;
  }

  /**
   * Get groupIdShort
   * @return groupIdShort
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GROUP_ID_SHORT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGroupIdShort() {
    return groupIdShort;
  }


  @JsonProperty(JSON_PROPERTY_GROUP_ID_SHORT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGroupIdShort(@jakarta.annotation.Nullable String groupIdShort) {
    this.groupIdShort = groupIdShort;
  }

  public LastTransfersResponseDriverTransfersInner groupOrderId(@jakarta.annotation.Nullable String groupOrderId) {
    
    this.groupOrderId = groupOrderId;
    return this;
  }

  /**
   * Get groupOrderId
   * @return groupOrderId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GROUP_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGroupOrderId() {
    return groupOrderId;
  }


  @JsonProperty(JSON_PROPERTY_GROUP_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGroupOrderId(@jakarta.annotation.Nullable String groupOrderId) {
    this.groupOrderId = groupOrderId;
  }

  public LastTransfersResponseDriverTransfersInner staffId(@jakarta.annotation.Nullable String staffId) {
    
    this.staffId = staffId;
    return this;
  }

  /**
   * Get staffId
   * @return staffId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STAFF_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStaffId() {
    return staffId;
  }


  @JsonProperty(JSON_PROPERTY_STAFF_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStaffId(@jakarta.annotation.Nullable String staffId) {
    this.staffId = staffId;
  }

  public LastTransfersResponseDriverTransfersInner staffName(@jakarta.annotation.Nullable String staffName) {
    
    this.staffName = staffName;
    return this;
  }

  /**
   * Get staffName
   * @return staffName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STAFF_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStaffName() {
    return staffName;
  }


  @JsonProperty(JSON_PROPERTY_STAFF_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStaffName(@jakarta.annotation.Nullable String staffName) {
    this.staffName = staffName;
  }

  public LastTransfersResponseDriverTransfersInner staffColor(@jakarta.annotation.Nullable String staffColor) {
    
    this.staffColor = staffColor;
    return this;
  }

  /**
   * Get staffColor
   * @return staffColor
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STAFF_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStaffColor() {
    return staffColor;
  }


  @JsonProperty(JSON_PROPERTY_STAFF_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStaffColor(@jakarta.annotation.Nullable String staffColor) {
    this.staffColor = staffColor;
  }

  public LastTransfersResponseDriverTransfersInner races(@jakarta.annotation.Nullable String races) {
    
    this.races = races;
    return this;
  }

  /**
   * Get races
   * @return races
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RACES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRaces() {
    return races;
  }


  @JsonProperty(JSON_PROPERTY_RACES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRaces(@jakarta.annotation.Nullable String races) {
    this.races = races;
  }

  public LastTransfersResponseDriverTransfersInner salary(@jakarta.annotation.Nullable String salary) {
    
    this.salary = salary;
    return this;
  }

  /**
   * Get salary
   * @return salary
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SALARY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSalary() {
    return salary;
  }


  @JsonProperty(JSON_PROPERTY_SALARY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSalary(@jakarta.annotation.Nullable String salary) {
    this.salary = salary;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LastTransfersResponseDriverTransfersInner lastTransfersResponseDriverTransfersInner = (LastTransfersResponseDriverTransfersInner) o;
    return Objects.equals(this.idx, lastTransfersResponseDriverTransfersInner.idx) &&
        Objects.equals(this.name, lastTransfersResponseDriverTransfersInner.name) &&
        Objects.equals(this.natCode, lastTransfersResponseDriverTransfersInner.natCode) &&
        Objects.equals(this.IDM, lastTransfersResponseDriverTransfersInner.IDM) &&
        Objects.equals(this.champs, lastTransfersResponseDriverTransfersInner.champs) &&
        Objects.equals(this.groupId, lastTransfersResponseDriverTransfersInner.groupId) &&
        Objects.equals(this.groupIdShort, lastTransfersResponseDriverTransfersInner.groupIdShort) &&
        Objects.equals(this.groupOrderId, lastTransfersResponseDriverTransfersInner.groupOrderId) &&
        Objects.equals(this.staffId, lastTransfersResponseDriverTransfersInner.staffId) &&
        Objects.equals(this.staffName, lastTransfersResponseDriverTransfersInner.staffName) &&
        Objects.equals(this.staffColor, lastTransfersResponseDriverTransfersInner.staffColor) &&
        Objects.equals(this.races, lastTransfersResponseDriverTransfersInner.races) &&
        Objects.equals(this.salary, lastTransfersResponseDriverTransfersInner.salary);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idx, name, natCode, IDM, champs, groupId, groupIdShort, groupOrderId, staffId, staffName, staffColor, races, salary);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LastTransfersResponseDriverTransfersInner {\n");
    sb.append("    idx: ").append(toIndentedString(idx)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    natCode: ").append(toIndentedString(natCode)).append("\n");
    sb.append("    IDM: ").append(toIndentedString(IDM)).append("\n");
    sb.append("    champs: ").append(toIndentedString(champs)).append("\n");
    sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
    sb.append("    groupIdShort: ").append(toIndentedString(groupIdShort)).append("\n");
    sb.append("    groupOrderId: ").append(toIndentedString(groupOrderId)).append("\n");
    sb.append("    staffId: ").append(toIndentedString(staffId)).append("\n");
    sb.append("    staffName: ").append(toIndentedString(staffName)).append("\n");
    sb.append("    staffColor: ").append(toIndentedString(staffColor)).append("\n");
    sb.append("    races: ").append(toIndentedString(races)).append("\n");
    sb.append("    salary: ").append(toIndentedString(salary)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

