/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PracticeResponseQ1LapData
 */
@JsonPropertyOrder({
  PracticeResponseQ1LapData.JSON_PROPERTY_LAP_TIME,
  PracticeResponseQ1LapData.JSON_PROPERTY_SET_F_WING,
  PracticeResponseQ1LapData.JSON_PROPERTY_SET_R_WING,
  PracticeResponseQ1LapData.JSON_PROPERTY_SET_ENG,
  PracticeResponseQ1LapData.JSON_PROPERTY_SET_BRA,
  PracticeResponseQ1LapData.JSON_PROPERTY_SET_GEAR,
  PracticeResponseQ1LapData.JSON_PROPERTY_SET_SUSP,
  PracticeResponseQ1LapData.JSON_PROPERTY_SET_TYRES,
  PracticeResponseQ1LapData.JSON_PROPERTY_SET_RISK,
  PracticeResponseQ1LapData.JSON_PROPERTY_Q1_POS,
  PracticeResponseQ1LapData.JSON_PROPERTY_Q1_GAP
})
@JsonTypeName("PracticeResponse_q1LapData")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class PracticeResponseQ1LapData {
  public static final String JSON_PROPERTY_LAP_TIME = "lapTime";
  @jakarta.annotation.Nullable
  private String lapTime;

  public static final String JSON_PROPERTY_SET_F_WING = "setFWing";
  @jakarta.annotation.Nullable
  private String setFWing;

  public static final String JSON_PROPERTY_SET_R_WING = "setRWing";
  @jakarta.annotation.Nullable
  private String setRWing;

  public static final String JSON_PROPERTY_SET_ENG = "setEng";
  @jakarta.annotation.Nullable
  private String setEng;

  public static final String JSON_PROPERTY_SET_BRA = "setBra";
  @jakarta.annotation.Nullable
  private String setBra;

  public static final String JSON_PROPERTY_SET_GEAR = "setGear";
  @jakarta.annotation.Nullable
  private String setGear;

  public static final String JSON_PROPERTY_SET_SUSP = "setSusp";
  @jakarta.annotation.Nullable
  private String setSusp;

  public static final String JSON_PROPERTY_SET_TYRES = "setTyres";
  @jakarta.annotation.Nullable
  private String setTyres;

  public static final String JSON_PROPERTY_SET_RISK = "setRisk";
  @jakarta.annotation.Nullable
  private String setRisk;

  public static final String JSON_PROPERTY_Q1_POS = "q1Pos";
  @jakarta.annotation.Nullable
  private String q1Pos;

  public static final String JSON_PROPERTY_Q1_GAP = "q1Gap";
  @jakarta.annotation.Nullable
  private String q1Gap;

  public PracticeResponseQ1LapData() {
  }

  public PracticeResponseQ1LapData lapTime(@jakarta.annotation.Nullable String lapTime) {
    
    this.lapTime = lapTime;
    return this;
  }

  /**
   * Get lapTime
   * @return lapTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAP_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLapTime() {
    return lapTime;
  }


  @JsonProperty(JSON_PROPERTY_LAP_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLapTime(@jakarta.annotation.Nullable String lapTime) {
    this.lapTime = lapTime;
  }

  public PracticeResponseQ1LapData setFWing(@jakarta.annotation.Nullable String setFWing) {
    
    this.setFWing = setFWing;
    return this;
  }

  /**
   * Get setFWing
   * @return setFWing
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SET_F_WING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSetFWing() {
    return setFWing;
  }


  @JsonProperty(JSON_PROPERTY_SET_F_WING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSetFWing(@jakarta.annotation.Nullable String setFWing) {
    this.setFWing = setFWing;
  }

  public PracticeResponseQ1LapData setRWing(@jakarta.annotation.Nullable String setRWing) {
    
    this.setRWing = setRWing;
    return this;
  }

  /**
   * Get setRWing
   * @return setRWing
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SET_R_WING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSetRWing() {
    return setRWing;
  }


  @JsonProperty(JSON_PROPERTY_SET_R_WING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSetRWing(@jakarta.annotation.Nullable String setRWing) {
    this.setRWing = setRWing;
  }

  public PracticeResponseQ1LapData setEng(@jakarta.annotation.Nullable String setEng) {
    
    this.setEng = setEng;
    return this;
  }

  /**
   * Get setEng
   * @return setEng
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SET_ENG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSetEng() {
    return setEng;
  }


  @JsonProperty(JSON_PROPERTY_SET_ENG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSetEng(@jakarta.annotation.Nullable String setEng) {
    this.setEng = setEng;
  }

  public PracticeResponseQ1LapData setBra(@jakarta.annotation.Nullable String setBra) {
    
    this.setBra = setBra;
    return this;
  }

  /**
   * Get setBra
   * @return setBra
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SET_BRA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSetBra() {
    return setBra;
  }


  @JsonProperty(JSON_PROPERTY_SET_BRA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSetBra(@jakarta.annotation.Nullable String setBra) {
    this.setBra = setBra;
  }

  public PracticeResponseQ1LapData setGear(@jakarta.annotation.Nullable String setGear) {
    
    this.setGear = setGear;
    return this;
  }

  /**
   * Get setGear
   * @return setGear
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SET_GEAR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSetGear() {
    return setGear;
  }


  @JsonProperty(JSON_PROPERTY_SET_GEAR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSetGear(@jakarta.annotation.Nullable String setGear) {
    this.setGear = setGear;
  }

  public PracticeResponseQ1LapData setSusp(@jakarta.annotation.Nullable String setSusp) {
    
    this.setSusp = setSusp;
    return this;
  }

  /**
   * Get setSusp
   * @return setSusp
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SET_SUSP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSetSusp() {
    return setSusp;
  }


  @JsonProperty(JSON_PROPERTY_SET_SUSP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSetSusp(@jakarta.annotation.Nullable String setSusp) {
    this.setSusp = setSusp;
  }

  public PracticeResponseQ1LapData setTyres(@jakarta.annotation.Nullable String setTyres) {
    
    this.setTyres = setTyres;
    return this;
  }

  /**
   * Get setTyres
   * @return setTyres
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SET_TYRES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSetTyres() {
    return setTyres;
  }


  @JsonProperty(JSON_PROPERTY_SET_TYRES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSetTyres(@jakarta.annotation.Nullable String setTyres) {
    this.setTyres = setTyres;
  }

  public PracticeResponseQ1LapData setRisk(@jakarta.annotation.Nullable String setRisk) {
    
    this.setRisk = setRisk;
    return this;
  }

  /**
   * Get setRisk
   * @return setRisk
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SET_RISK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSetRisk() {
    return setRisk;
  }


  @JsonProperty(JSON_PROPERTY_SET_RISK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSetRisk(@jakarta.annotation.Nullable String setRisk) {
    this.setRisk = setRisk;
  }

  public PracticeResponseQ1LapData q1Pos(@jakarta.annotation.Nullable String q1Pos) {
    
    this.q1Pos = q1Pos;
    return this;
  }

  /**
   * Get q1Pos
   * @return q1Pos
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_Q1_POS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getQ1Pos() {
    return q1Pos;
  }


  @JsonProperty(JSON_PROPERTY_Q1_POS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQ1Pos(@jakarta.annotation.Nullable String q1Pos) {
    this.q1Pos = q1Pos;
  }

  public PracticeResponseQ1LapData q1Gap(@jakarta.annotation.Nullable String q1Gap) {
    
    this.q1Gap = q1Gap;
    return this;
  }

  /**
   * Get q1Gap
   * @return q1Gap
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_Q1_GAP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getQ1Gap() {
    return q1Gap;
  }


  @JsonProperty(JSON_PROPERTY_Q1_GAP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQ1Gap(@jakarta.annotation.Nullable String q1Gap) {
    this.q1Gap = q1Gap;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PracticeResponseQ1LapData practiceResponseQ1LapData = (PracticeResponseQ1LapData) o;
    return Objects.equals(this.lapTime, practiceResponseQ1LapData.lapTime) &&
        Objects.equals(this.setFWing, practiceResponseQ1LapData.setFWing) &&
        Objects.equals(this.setRWing, practiceResponseQ1LapData.setRWing) &&
        Objects.equals(this.setEng, practiceResponseQ1LapData.setEng) &&
        Objects.equals(this.setBra, practiceResponseQ1LapData.setBra) &&
        Objects.equals(this.setGear, practiceResponseQ1LapData.setGear) &&
        Objects.equals(this.setSusp, practiceResponseQ1LapData.setSusp) &&
        Objects.equals(this.setTyres, practiceResponseQ1LapData.setTyres) &&
        Objects.equals(this.setRisk, practiceResponseQ1LapData.setRisk) &&
        Objects.equals(this.q1Pos, practiceResponseQ1LapData.q1Pos) &&
        Objects.equals(this.q1Gap, practiceResponseQ1LapData.q1Gap);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lapTime, setFWing, setRWing, setEng, setBra, setGear, setSusp, setTyres, setRisk, q1Pos, q1Gap);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PracticeResponseQ1LapData {\n");
    sb.append("    lapTime: ").append(toIndentedString(lapTime)).append("\n");
    sb.append("    setFWing: ").append(toIndentedString(setFWing)).append("\n");
    sb.append("    setRWing: ").append(toIndentedString(setRWing)).append("\n");
    sb.append("    setEng: ").append(toIndentedString(setEng)).append("\n");
    sb.append("    setBra: ").append(toIndentedString(setBra)).append("\n");
    sb.append("    setGear: ").append(toIndentedString(setGear)).append("\n");
    sb.append("    setSusp: ").append(toIndentedString(setSusp)).append("\n");
    sb.append("    setTyres: ").append(toIndentedString(setTyres)).append("\n");
    sb.append("    setRisk: ").append(toIndentedString(setRisk)).append("\n");
    sb.append("    q1Pos: ").append(toIndentedString(q1Pos)).append("\n");
    sb.append("    q1Gap: ").append(toIndentedString(q1Gap)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

