/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RaceAnalysisResponseQ1Energy
 */
@JsonPropertyOrder({
  RaceAnalysisResponseQ1Energy.JSON_PROPERTY_FROM,
  RaceAnalysisResponseQ1Energy.JSON_PROPERTY_TO
})
@JsonTypeName("RaceAnalysisResponse_q1Energy")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class RaceAnalysisResponseQ1Energy {
  public static final String JSON_PROPERTY_FROM = "from";
  @jakarta.annotation.Nullable
  private Integer from;

  public static final String JSON_PROPERTY_TO = "to";
  @jakarta.annotation.Nullable
  private Integer to;

  public RaceAnalysisResponseQ1Energy() {
  }

  public RaceAnalysisResponseQ1Energy from(@jakarta.annotation.Nullable Integer from) {
    
    this.from = from;
    return this;
  }

  /**
   * Get from
   * @return from
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FROM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFrom() {
    return from;
  }


  @JsonProperty(JSON_PROPERTY_FROM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFrom(@jakarta.annotation.Nullable Integer from) {
    this.from = from;
  }

  public RaceAnalysisResponseQ1Energy to(@jakarta.annotation.Nullable Integer to) {
    
    this.to = to;
    return this;
  }

  /**
   * Get to
   * @return to
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTo() {
    return to;
  }


  @JsonProperty(JSON_PROPERTY_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTo(@jakarta.annotation.Nullable Integer to) {
    this.to = to;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RaceAnalysisResponseQ1Energy raceAnalysisResponseQ1Energy = (RaceAnalysisResponseQ1Energy) o;
    return Objects.equals(this.from, raceAnalysisResponseQ1Energy.from) &&
        Objects.equals(this.to, raceAnalysisResponseQ1Energy.to);
  }

  @Override
  public int hashCode() {
    return Objects.hash(from, to);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RaceAnalysisResponseQ1Energy {\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

