/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RaceAnalysisResponseLapsInnerEventsInner
 */
@JsonPropertyOrder({
  RaceAnalysisResponseLapsInnerEventsInner.JSON_PROPERTY_EVENT,
  RaceAnalysisResponseLapsInnerEventsInner.JSON_PROPERTY_EVENT_COLOR
})
@JsonTypeName("RaceAnalysisResponse_laps_inner_events_inner")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class RaceAnalysisResponseLapsInnerEventsInner {
  public static final String JSON_PROPERTY_EVENT = "event";
  @jakarta.annotation.Nullable
  private String event;

  public static final String JSON_PROPERTY_EVENT_COLOR = "eventColor";
  @jakarta.annotation.Nullable
  private String eventColor;

  public RaceAnalysisResponseLapsInnerEventsInner() {
  }

  public RaceAnalysisResponseLapsInnerEventsInner event(@jakarta.annotation.Nullable String event) {
    
    this.event = event;
    return this;
  }

  /**
   * Get event
   * @return event
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEvent() {
    return event;
  }


  @JsonProperty(JSON_PROPERTY_EVENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEvent(@jakarta.annotation.Nullable String event) {
    this.event = event;
  }

  public RaceAnalysisResponseLapsInnerEventsInner eventColor(@jakarta.annotation.Nullable String eventColor) {
    
    this.eventColor = eventColor;
    return this;
  }

  /**
   * Get eventColor
   * @return eventColor
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVENT_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEventColor() {
    return eventColor;
  }


  @JsonProperty(JSON_PROPERTY_EVENT_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEventColor(@jakarta.annotation.Nullable String eventColor) {
    this.eventColor = eventColor;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RaceAnalysisResponseLapsInnerEventsInner raceAnalysisResponseLapsInnerEventsInner = (RaceAnalysisResponseLapsInnerEventsInner) o;
    return Objects.equals(this.event, raceAnalysisResponseLapsInnerEventsInner.event) &&
        Objects.equals(this.eventColor, raceAnalysisResponseLapsInnerEventsInner.eventColor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(event, eventColor);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RaceAnalysisResponseLapsInnerEventsInner {\n");
    sb.append("    event: ").append(toIndentedString(event)).append("\n");
    sb.append("    eventColor: ").append(toIndentedString(eventColor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

