/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.jlobato.gpro.model.SnFHistoryResponseDataGraphYAxisLabels;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SnFHistoryResponseDataGraphYAxis
 */
@JsonPropertyOrder({
  SnFHistoryResponseDataGraphYAxis.JSON_PROPERTY_LABELS,
  SnFHistoryResponseDataGraphYAxis.JSON_PROPERTY_TITLE
})
@JsonTypeName("SnFHistoryResponse_dataGraph_yAxis")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class SnFHistoryResponseDataGraphYAxis {
  public static final String JSON_PROPERTY_LABELS = "labels";
  @jakarta.annotation.Nullable
  private SnFHistoryResponseDataGraphYAxisLabels labels;

  public static final String JSON_PROPERTY_TITLE = "title";
  @jakarta.annotation.Nullable
  private Integer title;

  public SnFHistoryResponseDataGraphYAxis() {
  }

  public SnFHistoryResponseDataGraphYAxis labels(@jakarta.annotation.Nullable SnFHistoryResponseDataGraphYAxisLabels labels) {
    
    this.labels = labels;
    return this;
  }

  /**
   * Get labels
   * @return labels
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LABELS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SnFHistoryResponseDataGraphYAxisLabels getLabels() {
    return labels;
  }


  @JsonProperty(JSON_PROPERTY_LABELS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLabels(@jakarta.annotation.Nullable SnFHistoryResponseDataGraphYAxisLabels labels) {
    this.labels = labels;
  }

  public SnFHistoryResponseDataGraphYAxis title(@jakarta.annotation.Nullable Integer title) {
    
    this.title = title;
    return this;
  }

  /**
   * Get title
   * @return title
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTitle() {
    return title;
  }


  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTitle(@jakarta.annotation.Nullable Integer title) {
    this.title = title;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SnFHistoryResponseDataGraphYAxis snFHistoryResponseDataGraphYAxis = (SnFHistoryResponseDataGraphYAxis) o;
    return Objects.equals(this.labels, snFHistoryResponseDataGraphYAxis.labels) &&
        Objects.equals(this.title, snFHistoryResponseDataGraphYAxis.title);
  }

  @Override
  public int hashCode() {
    return Objects.hash(labels, title);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SnFHistoryResponseDataGraphYAxis {\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

