/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.jlobato.gpro.model.StandingsResponseDataGraphChartBackgroundColor;
import org.jlobato.gpro.model.StandingsResponseDataGraphScrollbarBarBackgroundColor;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * StandingsResponseDataGraphScrollbar
 */
@JsonPropertyOrder({
  StandingsResponseDataGraphScrollbar.JSON_PROPERTY_BAR_BACKGROUND_COLOR,
  StandingsResponseDataGraphScrollbar.JSON_PROPERTY_BAR_BORDER_COLOR,
  StandingsResponseDataGraphScrollbar.JSON_PROPERTY_BUTTON_ARROW_COLOR,
  StandingsResponseDataGraphScrollbar.JSON_PROPERTY_BUTTON_BACKGROUND_COLOR,
  StandingsResponseDataGraphScrollbar.JSON_PROPERTY_BUTTON_BORDER_COLOR,
  StandingsResponseDataGraphScrollbar.JSON_PROPERTY_RIFLE_COLOR,
  StandingsResponseDataGraphScrollbar.JSON_PROPERTY_TRACK_BACKGROUND_COLOR,
  StandingsResponseDataGraphScrollbar.JSON_PROPERTY_TRACK_BORDER_COLOR
})
@JsonTypeName("StandingsResponse_dataGraph_scrollbar")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class StandingsResponseDataGraphScrollbar {
  public static final String JSON_PROPERTY_BAR_BACKGROUND_COLOR = "barBackgroundColor";
  @jakarta.annotation.Nullable
  private StandingsResponseDataGraphScrollbarBarBackgroundColor barBackgroundColor;

  public static final String JSON_PROPERTY_BAR_BORDER_COLOR = "barBorderColor";
  @jakarta.annotation.Nullable
  private String barBorderColor;

  public static final String JSON_PROPERTY_BUTTON_ARROW_COLOR = "buttonArrowColor";
  @jakarta.annotation.Nullable
  private String buttonArrowColor;

  public static final String JSON_PROPERTY_BUTTON_BACKGROUND_COLOR = "buttonBackgroundColor";
  @jakarta.annotation.Nullable
  private StandingsResponseDataGraphScrollbarBarBackgroundColor buttonBackgroundColor;

  public static final String JSON_PROPERTY_BUTTON_BORDER_COLOR = "buttonBorderColor";
  @jakarta.annotation.Nullable
  private String buttonBorderColor;

  public static final String JSON_PROPERTY_RIFLE_COLOR = "rifleColor";
  @jakarta.annotation.Nullable
  private String rifleColor;

  public static final String JSON_PROPERTY_TRACK_BACKGROUND_COLOR = "trackBackgroundColor";
  @jakarta.annotation.Nullable
  private StandingsResponseDataGraphChartBackgroundColor trackBackgroundColor;

  public static final String JSON_PROPERTY_TRACK_BORDER_COLOR = "trackBorderColor";
  @jakarta.annotation.Nullable
  private String trackBorderColor;

  public StandingsResponseDataGraphScrollbar() {
  }

  public StandingsResponseDataGraphScrollbar barBackgroundColor(@jakarta.annotation.Nullable StandingsResponseDataGraphScrollbarBarBackgroundColor barBackgroundColor) {
    
    this.barBackgroundColor = barBackgroundColor;
    return this;
  }

  /**
   * Get barBackgroundColor
   * @return barBackgroundColor
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BAR_BACKGROUND_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StandingsResponseDataGraphScrollbarBarBackgroundColor getBarBackgroundColor() {
    return barBackgroundColor;
  }


  @JsonProperty(JSON_PROPERTY_BAR_BACKGROUND_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBarBackgroundColor(@jakarta.annotation.Nullable StandingsResponseDataGraphScrollbarBarBackgroundColor barBackgroundColor) {
    this.barBackgroundColor = barBackgroundColor;
  }

  public StandingsResponseDataGraphScrollbar barBorderColor(@jakarta.annotation.Nullable String barBorderColor) {
    
    this.barBorderColor = barBorderColor;
    return this;
  }

  /**
   * Get barBorderColor
   * @return barBorderColor
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BAR_BORDER_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBarBorderColor() {
    return barBorderColor;
  }


  @JsonProperty(JSON_PROPERTY_BAR_BORDER_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBarBorderColor(@jakarta.annotation.Nullable String barBorderColor) {
    this.barBorderColor = barBorderColor;
  }

  public StandingsResponseDataGraphScrollbar buttonArrowColor(@jakarta.annotation.Nullable String buttonArrowColor) {
    
    this.buttonArrowColor = buttonArrowColor;
    return this;
  }

  /**
   * Get buttonArrowColor
   * @return buttonArrowColor
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BUTTON_ARROW_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getButtonArrowColor() {
    return buttonArrowColor;
  }


  @JsonProperty(JSON_PROPERTY_BUTTON_ARROW_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setButtonArrowColor(@jakarta.annotation.Nullable String buttonArrowColor) {
    this.buttonArrowColor = buttonArrowColor;
  }

  public StandingsResponseDataGraphScrollbar buttonBackgroundColor(@jakarta.annotation.Nullable StandingsResponseDataGraphScrollbarBarBackgroundColor buttonBackgroundColor) {
    
    this.buttonBackgroundColor = buttonBackgroundColor;
    return this;
  }

  /**
   * Get buttonBackgroundColor
   * @return buttonBackgroundColor
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BUTTON_BACKGROUND_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StandingsResponseDataGraphScrollbarBarBackgroundColor getButtonBackgroundColor() {
    return buttonBackgroundColor;
  }


  @JsonProperty(JSON_PROPERTY_BUTTON_BACKGROUND_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setButtonBackgroundColor(@jakarta.annotation.Nullable StandingsResponseDataGraphScrollbarBarBackgroundColor buttonBackgroundColor) {
    this.buttonBackgroundColor = buttonBackgroundColor;
  }

  public StandingsResponseDataGraphScrollbar buttonBorderColor(@jakarta.annotation.Nullable String buttonBorderColor) {
    
    this.buttonBorderColor = buttonBorderColor;
    return this;
  }

  /**
   * Get buttonBorderColor
   * @return buttonBorderColor
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BUTTON_BORDER_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getButtonBorderColor() {
    return buttonBorderColor;
  }


  @JsonProperty(JSON_PROPERTY_BUTTON_BORDER_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setButtonBorderColor(@jakarta.annotation.Nullable String buttonBorderColor) {
    this.buttonBorderColor = buttonBorderColor;
  }

  public StandingsResponseDataGraphScrollbar rifleColor(@jakarta.annotation.Nullable String rifleColor) {
    
    this.rifleColor = rifleColor;
    return this;
  }

  /**
   * Get rifleColor
   * @return rifleColor
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RIFLE_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRifleColor() {
    return rifleColor;
  }


  @JsonProperty(JSON_PROPERTY_RIFLE_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRifleColor(@jakarta.annotation.Nullable String rifleColor) {
    this.rifleColor = rifleColor;
  }

  public StandingsResponseDataGraphScrollbar trackBackgroundColor(@jakarta.annotation.Nullable StandingsResponseDataGraphChartBackgroundColor trackBackgroundColor) {
    
    this.trackBackgroundColor = trackBackgroundColor;
    return this;
  }

  /**
   * Get trackBackgroundColor
   * @return trackBackgroundColor
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRACK_BACKGROUND_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StandingsResponseDataGraphChartBackgroundColor getTrackBackgroundColor() {
    return trackBackgroundColor;
  }


  @JsonProperty(JSON_PROPERTY_TRACK_BACKGROUND_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrackBackgroundColor(@jakarta.annotation.Nullable StandingsResponseDataGraphChartBackgroundColor trackBackgroundColor) {
    this.trackBackgroundColor = trackBackgroundColor;
  }

  public StandingsResponseDataGraphScrollbar trackBorderColor(@jakarta.annotation.Nullable String trackBorderColor) {
    
    this.trackBorderColor = trackBorderColor;
    return this;
  }

  /**
   * Get trackBorderColor
   * @return trackBorderColor
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRACK_BORDER_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTrackBorderColor() {
    return trackBorderColor;
  }


  @JsonProperty(JSON_PROPERTY_TRACK_BORDER_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrackBorderColor(@jakarta.annotation.Nullable String trackBorderColor) {
    this.trackBorderColor = trackBorderColor;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StandingsResponseDataGraphScrollbar standingsResponseDataGraphScrollbar = (StandingsResponseDataGraphScrollbar) o;
    return Objects.equals(this.barBackgroundColor, standingsResponseDataGraphScrollbar.barBackgroundColor) &&
        Objects.equals(this.barBorderColor, standingsResponseDataGraphScrollbar.barBorderColor) &&
        Objects.equals(this.buttonArrowColor, standingsResponseDataGraphScrollbar.buttonArrowColor) &&
        Objects.equals(this.buttonBackgroundColor, standingsResponseDataGraphScrollbar.buttonBackgroundColor) &&
        Objects.equals(this.buttonBorderColor, standingsResponseDataGraphScrollbar.buttonBorderColor) &&
        Objects.equals(this.rifleColor, standingsResponseDataGraphScrollbar.rifleColor) &&
        Objects.equals(this.trackBackgroundColor, standingsResponseDataGraphScrollbar.trackBackgroundColor) &&
        Objects.equals(this.trackBorderColor, standingsResponseDataGraphScrollbar.trackBorderColor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(barBackgroundColor, barBorderColor, buttonArrowColor, buttonBackgroundColor, buttonBorderColor, rifleColor, trackBackgroundColor, trackBorderColor);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StandingsResponseDataGraphScrollbar {\n");
    sb.append("    barBackgroundColor: ").append(toIndentedString(barBackgroundColor)).append("\n");
    sb.append("    barBorderColor: ").append(toIndentedString(barBorderColor)).append("\n");
    sb.append("    buttonArrowColor: ").append(toIndentedString(buttonArrowColor)).append("\n");
    sb.append("    buttonBackgroundColor: ").append(toIndentedString(buttonBackgroundColor)).append("\n");
    sb.append("    buttonBorderColor: ").append(toIndentedString(buttonBorderColor)).append("\n");
    sb.append("    rifleColor: ").append(toIndentedString(rifleColor)).append("\n");
    sb.append("    trackBackgroundColor: ").append(toIndentedString(trackBackgroundColor)).append("\n");
    sb.append("    trackBorderColor: ").append(toIndentedString(trackBorderColor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

