/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * StandingsResponseDataGraphPlotOptionsSeriesStatesHover
 */
@JsonPropertyOrder({
  StandingsResponseDataGraphPlotOptionsSeriesStatesHover.JSON_PROPERTY_LINE_WIDTH_PLUS
})
@JsonTypeName("StandingsResponse_dataGraph_plotOptions_series_states_hover")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class StandingsResponseDataGraphPlotOptionsSeriesStatesHover {
  public static final String JSON_PROPERTY_LINE_WIDTH_PLUS = "lineWidthPlus";
  @jakarta.annotation.Nullable
  private Integer lineWidthPlus;

  public StandingsResponseDataGraphPlotOptionsSeriesStatesHover() {
  }

  public StandingsResponseDataGraphPlotOptionsSeriesStatesHover lineWidthPlus(@jakarta.annotation.Nullable Integer lineWidthPlus) {
    
    this.lineWidthPlus = lineWidthPlus;
    return this;
  }

  /**
   * Get lineWidthPlus
   * @return lineWidthPlus
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LINE_WIDTH_PLUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getLineWidthPlus() {
    return lineWidthPlus;
  }


  @JsonProperty(JSON_PROPERTY_LINE_WIDTH_PLUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLineWidthPlus(@jakarta.annotation.Nullable Integer lineWidthPlus) {
    this.lineWidthPlus = lineWidthPlus;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StandingsResponseDataGraphPlotOptionsSeriesStatesHover standingsResponseDataGraphPlotOptionsSeriesStatesHover = (StandingsResponseDataGraphPlotOptionsSeriesStatesHover) o;
    return Objects.equals(this.lineWidthPlus, standingsResponseDataGraphPlotOptionsSeriesStatesHover.lineWidthPlus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lineWidthPlus);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StandingsResponseDataGraphPlotOptionsSeriesStatesHover {\n");
    sb.append("    lineWidthPlus: ").append(toIndentedString(lineWidthPlus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

