/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * StandingsResponseDataGraphNavigatorSeries
 */
@JsonPropertyOrder({
  StandingsResponseDataGraphNavigatorSeries.JSON_PROPERTY_COLOR,
  StandingsResponseDataGraphNavigatorSeries.JSON_PROPERTY_LINE_COLOR
})
@JsonTypeName("StandingsResponse_dataGraph_navigator_series")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class StandingsResponseDataGraphNavigatorSeries {
  public static final String JSON_PROPERTY_COLOR = "color";
  @jakarta.annotation.Nullable
  private String color;

  public static final String JSON_PROPERTY_LINE_COLOR = "lineColor";
  @jakarta.annotation.Nullable
  private String lineColor;

  public StandingsResponseDataGraphNavigatorSeries() {
  }

  public StandingsResponseDataGraphNavigatorSeries color(@jakarta.annotation.Nullable String color) {
    
    this.color = color;
    return this;
  }

  /**
   * Get color
   * @return color
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getColor() {
    return color;
  }


  @JsonProperty(JSON_PROPERTY_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setColor(@jakarta.annotation.Nullable String color) {
    this.color = color;
  }

  public StandingsResponseDataGraphNavigatorSeries lineColor(@jakarta.annotation.Nullable String lineColor) {
    
    this.lineColor = lineColor;
    return this;
  }

  /**
   * Get lineColor
   * @return lineColor
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LINE_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLineColor() {
    return lineColor;
  }


  @JsonProperty(JSON_PROPERTY_LINE_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLineColor(@jakarta.annotation.Nullable String lineColor) {
    this.lineColor = lineColor;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StandingsResponseDataGraphNavigatorSeries standingsResponseDataGraphNavigatorSeries = (StandingsResponseDataGraphNavigatorSeries) o;
    return Objects.equals(this.color, standingsResponseDataGraphNavigatorSeries.color) &&
        Objects.equals(this.lineColor, standingsResponseDataGraphNavigatorSeries.lineColor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(color, lineColor);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StandingsResponseDataGraphNavigatorSeries {\n");
    sb.append("    color: ").append(toIndentedString(color)).append("\n");
    sb.append("    lineColor: ").append(toIndentedString(lineColor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

