/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.jlobato.gpro.model.AvailDriversResponseConRangesInner;
import org.jlobato.gpro.model.AvailDriversResponseOA;
import org.jlobato.gpro.model.AvailTDsResponseTdsInner;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * AvailTDsResponse
 */
@JsonPropertyOrder({
  AvailTDsResponse.JSON_PROPERTY_LOADING_DATA_STATE,
  AvailTDsResponse.JSON_PROPERTY_TDS,
  AvailTDsResponse.JSON_PROPERTY_O_A,
  AvailTDsResponse.JSON_PROPERTY_FILTER1,
  AvailTDsResponse.JSON_PROPERTY_FILTER2,
  AvailTDsResponse.JSON_PROPERTY_FILTER3,
  AvailTDsResponse.JSON_PROPERTY_FILTER1_RANGE,
  AvailTDsResponse.JSON_PROPERTY_FILTER2_RANGE,
  AvailTDsResponse.JSON_PROPERTY_FILTER3_RANGE,
  AvailTDsResponse.JSON_PROPERTY_SORT_PARAM,
  AvailTDsResponse.JSON_PROPERTY_RANGES,
  AvailTDsResponse.JSON_PROPERTY_LEA_RANGES,
  AvailTDsResponse.JSON_PROPERTY_MEC_RANGES,
  AvailTDsResponse.JSON_PROPERTY_ELE_RANGES,
  AvailTDsResponse.JSON_PROPERTY_EXP_RANGES,
  AvailTDsResponse.JSON_PROPERTY_AER_RANGES,
  AvailTDsResponse.JSON_PROPERTY_PIT_RANGES,
  AvailTDsResponse.JSON_PROPERTY_MOT_RANGES,
  AvailTDsResponse.JSON_PROPERTY_AGE_RANGES,
  AvailTDsResponse.JSON_PROPERTY_MINSAL_RANGES,
  AvailTDsResponse.JSON_PROPERTY_OFF_RANGES,
  AvailTDsResponse.JSON_PROPERTY_SHOW_ALERT_S_L,
  AvailTDsResponse.JSON_PROPERTY_PAGE_COUNT,
  AvailTDsResponse.JSON_PROPERTY_PAGE_SIZE,
  AvailTDsResponse.JSON_PROPERTY_PAGE_INDEX,
  AvailTDsResponse.JSON_PROPERTY_API_REQUESTS_REMAINING
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class AvailTDsResponse {
  public static final String JSON_PROPERTY_LOADING_DATA_STATE = "loadingDataState";
  @jakarta.annotation.Nullable
  private String loadingDataState;

  public static final String JSON_PROPERTY_TDS = "tds";
  @jakarta.annotation.Nullable
  private List<AvailTDsResponseTdsInner> tds = new ArrayList<>();

  public static final String JSON_PROPERTY_O_A = "OA";
  @jakarta.annotation.Nullable
  private AvailDriversResponseOA OA;

  public static final String JSON_PROPERTY_FILTER1 = "filter1";
  @jakarta.annotation.Nullable
  private String filter1;

  public static final String JSON_PROPERTY_FILTER2 = "filter2";
  @jakarta.annotation.Nullable
  private String filter2;

  public static final String JSON_PROPERTY_FILTER3 = "filter3";
  @jakarta.annotation.Nullable
  private String filter3;

  public static final String JSON_PROPERTY_FILTER1_RANGE = "filter1Range";
  @jakarta.annotation.Nullable
  private String filter1Range;

  public static final String JSON_PROPERTY_FILTER2_RANGE = "filter2Range";
  @jakarta.annotation.Nullable
  private String filter2Range;

  public static final String JSON_PROPERTY_FILTER3_RANGE = "filter3Range";
  @jakarta.annotation.Nullable
  private String filter3Range;

  public static final String JSON_PROPERTY_SORT_PARAM = "sortParam";
  @jakarta.annotation.Nullable
  private String sortParam;

  public static final String JSON_PROPERTY_RANGES = "Ranges";
  @jakarta.annotation.Nullable
  private List<String> ranges = new ArrayList<>();

  public static final String JSON_PROPERTY_LEA_RANGES = "leaRanges";
  @jakarta.annotation.Nullable
  private List<AvailDriversResponseConRangesInner> leaRanges = new ArrayList<>();

  public static final String JSON_PROPERTY_MEC_RANGES = "mecRanges";
  @jakarta.annotation.Nullable
  private List<AvailDriversResponseConRangesInner> mecRanges = new ArrayList<>();

  public static final String JSON_PROPERTY_ELE_RANGES = "eleRanges";
  @jakarta.annotation.Nullable
  private List<AvailDriversResponseConRangesInner> eleRanges = new ArrayList<>();

  public static final String JSON_PROPERTY_EXP_RANGES = "expRanges";
  @jakarta.annotation.Nullable
  private List<AvailDriversResponseConRangesInner> expRanges = new ArrayList<>();

  public static final String JSON_PROPERTY_AER_RANGES = "aerRanges";
  @jakarta.annotation.Nullable
  private List<AvailDriversResponseConRangesInner> aerRanges = new ArrayList<>();

  public static final String JSON_PROPERTY_PIT_RANGES = "pitRanges";
  @jakarta.annotation.Nullable
  private List<AvailDriversResponseConRangesInner> pitRanges = new ArrayList<>();

  public static final String JSON_PROPERTY_MOT_RANGES = "motRanges";
  @jakarta.annotation.Nullable
  private List<AvailDriversResponseConRangesInner> motRanges = new ArrayList<>();

  public static final String JSON_PROPERTY_AGE_RANGES = "ageRanges";
  @jakarta.annotation.Nullable
  private List<AvailDriversResponseConRangesInner> ageRanges = new ArrayList<>();

  public static final String JSON_PROPERTY_MINSAL_RANGES = "minsalRanges";
  @jakarta.annotation.Nullable
  private List<AvailDriversResponseConRangesInner> minsalRanges = new ArrayList<>();

  public static final String JSON_PROPERTY_OFF_RANGES = "offRanges";
  @jakarta.annotation.Nullable
  private List<AvailDriversResponseConRangesInner> offRanges = new ArrayList<>();

  public static final String JSON_PROPERTY_SHOW_ALERT_S_L = "showAlertSL";
  @jakarta.annotation.Nullable
  private Boolean showAlertSL;

  public static final String JSON_PROPERTY_PAGE_COUNT = "pageCount";
  @jakarta.annotation.Nullable
  private Integer pageCount;

  public static final String JSON_PROPERTY_PAGE_SIZE = "pageSize";
  @jakarta.annotation.Nullable
  private String pageSize;

  public static final String JSON_PROPERTY_PAGE_INDEX = "pageIndex";
  @jakarta.annotation.Nullable
  private Integer pageIndex;

  public static final String JSON_PROPERTY_API_REQUESTS_REMAINING = "apiRequestsRemaining";
  @jakarta.annotation.Nullable
  private Integer apiRequestsRemaining;

  public AvailTDsResponse() {
  }

  public AvailTDsResponse loadingDataState(@jakarta.annotation.Nullable String loadingDataState) {
    
    this.loadingDataState = loadingDataState;
    return this;
  }

  /**
   * Get loadingDataState
   * @return loadingDataState
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOADING_DATA_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLoadingDataState() {
    return loadingDataState;
  }


  @JsonProperty(JSON_PROPERTY_LOADING_DATA_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLoadingDataState(@jakarta.annotation.Nullable String loadingDataState) {
    this.loadingDataState = loadingDataState;
  }

  public AvailTDsResponse tds(@jakarta.annotation.Nullable List<AvailTDsResponseTdsInner> tds) {
    
    this.tds = tds;
    return this;
  }

  public AvailTDsResponse addTdsItem(AvailTDsResponseTdsInner tdsItem) {
    if (this.tds == null) {
      this.tds = new ArrayList<>();
    }
    this.tds.add(tdsItem);
    return this;
  }

  /**
   * Get tds
   * @return tds
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<AvailTDsResponseTdsInner> getTds() {
    return tds;
  }


  @JsonProperty(JSON_PROPERTY_TDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTds(@jakarta.annotation.Nullable List<AvailTDsResponseTdsInner> tds) {
    this.tds = tds;
  }

  public AvailTDsResponse OA(@jakarta.annotation.Nullable AvailDriversResponseOA OA) {
    
    this.OA = OA;
    return this;
  }

  /**
   * Get OA
   * @return OA
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_O_A)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AvailDriversResponseOA getOA() {
    return OA;
  }


  @JsonProperty(JSON_PROPERTY_O_A)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOA(@jakarta.annotation.Nullable AvailDriversResponseOA OA) {
    this.OA = OA;
  }

  public AvailTDsResponse filter1(@jakarta.annotation.Nullable String filter1) {
    
    this.filter1 = filter1;
    return this;
  }

  /**
   * Get filter1
   * @return filter1
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FILTER1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFilter1() {
    return filter1;
  }


  @JsonProperty(JSON_PROPERTY_FILTER1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFilter1(@jakarta.annotation.Nullable String filter1) {
    this.filter1 = filter1;
  }

  public AvailTDsResponse filter2(@jakarta.annotation.Nullable String filter2) {
    
    this.filter2 = filter2;
    return this;
  }

  /**
   * Get filter2
   * @return filter2
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FILTER2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFilter2() {
    return filter2;
  }


  @JsonProperty(JSON_PROPERTY_FILTER2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFilter2(@jakarta.annotation.Nullable String filter2) {
    this.filter2 = filter2;
  }

  public AvailTDsResponse filter3(@jakarta.annotation.Nullable String filter3) {
    
    this.filter3 = filter3;
    return this;
  }

  /**
   * Get filter3
   * @return filter3
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FILTER3)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFilter3() {
    return filter3;
  }


  @JsonProperty(JSON_PROPERTY_FILTER3)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFilter3(@jakarta.annotation.Nullable String filter3) {
    this.filter3 = filter3;
  }

  public AvailTDsResponse filter1Range(@jakarta.annotation.Nullable String filter1Range) {
    
    this.filter1Range = filter1Range;
    return this;
  }

  /**
   * Get filter1Range
   * @return filter1Range
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FILTER1_RANGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFilter1Range() {
    return filter1Range;
  }


  @JsonProperty(JSON_PROPERTY_FILTER1_RANGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFilter1Range(@jakarta.annotation.Nullable String filter1Range) {
    this.filter1Range = filter1Range;
  }

  public AvailTDsResponse filter2Range(@jakarta.annotation.Nullable String filter2Range) {
    
    this.filter2Range = filter2Range;
    return this;
  }

  /**
   * Get filter2Range
   * @return filter2Range
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FILTER2_RANGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFilter2Range() {
    return filter2Range;
  }


  @JsonProperty(JSON_PROPERTY_FILTER2_RANGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFilter2Range(@jakarta.annotation.Nullable String filter2Range) {
    this.filter2Range = filter2Range;
  }

  public AvailTDsResponse filter3Range(@jakarta.annotation.Nullable String filter3Range) {
    
    this.filter3Range = filter3Range;
    return this;
  }

  /**
   * Get filter3Range
   * @return filter3Range
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FILTER3_RANGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFilter3Range() {
    return filter3Range;
  }


  @JsonProperty(JSON_PROPERTY_FILTER3_RANGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFilter3Range(@jakarta.annotation.Nullable String filter3Range) {
    this.filter3Range = filter3Range;
  }

  public AvailTDsResponse sortParam(@jakarta.annotation.Nullable String sortParam) {
    
    this.sortParam = sortParam;
    return this;
  }

  /**
   * Get sortParam
   * @return sortParam
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SORT_PARAM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSortParam() {
    return sortParam;
  }


  @JsonProperty(JSON_PROPERTY_SORT_PARAM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSortParam(@jakarta.annotation.Nullable String sortParam) {
    this.sortParam = sortParam;
  }

  public AvailTDsResponse ranges(@jakarta.annotation.Nullable List<String> ranges) {
    
    this.ranges = ranges;
    return this;
  }

  public AvailTDsResponse addRangesItem(String rangesItem) {
    if (this.ranges == null) {
      this.ranges = new ArrayList<>();
    }
    this.ranges.add(rangesItem);
    return this;
  }

  /**
   * Get ranges
   * @return ranges
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RANGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getRanges() {
    return ranges;
  }


  @JsonProperty(JSON_PROPERTY_RANGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRanges(@jakarta.annotation.Nullable List<String> ranges) {
    this.ranges = ranges;
  }

  public AvailTDsResponse leaRanges(@jakarta.annotation.Nullable List<AvailDriversResponseConRangesInner> leaRanges) {
    
    this.leaRanges = leaRanges;
    return this;
  }

  public AvailTDsResponse addLeaRangesItem(AvailDriversResponseConRangesInner leaRangesItem) {
    if (this.leaRanges == null) {
      this.leaRanges = new ArrayList<>();
    }
    this.leaRanges.add(leaRangesItem);
    return this;
  }

  /**
   * Get leaRanges
   * @return leaRanges
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LEA_RANGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<AvailDriversResponseConRangesInner> getLeaRanges() {
    return leaRanges;
  }


  @JsonProperty(JSON_PROPERTY_LEA_RANGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLeaRanges(@jakarta.annotation.Nullable List<AvailDriversResponseConRangesInner> leaRanges) {
    this.leaRanges = leaRanges;
  }

  public AvailTDsResponse mecRanges(@jakarta.annotation.Nullable List<AvailDriversResponseConRangesInner> mecRanges) {
    
    this.mecRanges = mecRanges;
    return this;
  }

  public AvailTDsResponse addMecRangesItem(AvailDriversResponseConRangesInner mecRangesItem) {
    if (this.mecRanges == null) {
      this.mecRanges = new ArrayList<>();
    }
    this.mecRanges.add(mecRangesItem);
    return this;
  }

  /**
   * Get mecRanges
   * @return mecRanges
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MEC_RANGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<AvailDriversResponseConRangesInner> getMecRanges() {
    return mecRanges;
  }


  @JsonProperty(JSON_PROPERTY_MEC_RANGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMecRanges(@jakarta.annotation.Nullable List<AvailDriversResponseConRangesInner> mecRanges) {
    this.mecRanges = mecRanges;
  }

  public AvailTDsResponse eleRanges(@jakarta.annotation.Nullable List<AvailDriversResponseConRangesInner> eleRanges) {
    
    this.eleRanges = eleRanges;
    return this;
  }

  public AvailTDsResponse addEleRangesItem(AvailDriversResponseConRangesInner eleRangesItem) {
    if (this.eleRanges == null) {
      this.eleRanges = new ArrayList<>();
    }
    this.eleRanges.add(eleRangesItem);
    return this;
  }

  /**
   * Get eleRanges
   * @return eleRanges
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ELE_RANGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<AvailDriversResponseConRangesInner> getEleRanges() {
    return eleRanges;
  }


  @JsonProperty(JSON_PROPERTY_ELE_RANGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEleRanges(@jakarta.annotation.Nullable List<AvailDriversResponseConRangesInner> eleRanges) {
    this.eleRanges = eleRanges;
  }

  public AvailTDsResponse expRanges(@jakarta.annotation.Nullable List<AvailDriversResponseConRangesInner> expRanges) {
    
    this.expRanges = expRanges;
    return this;
  }

  public AvailTDsResponse addExpRangesItem(AvailDriversResponseConRangesInner expRangesItem) {
    if (this.expRanges == null) {
      this.expRanges = new ArrayList<>();
    }
    this.expRanges.add(expRangesItem);
    return this;
  }

  /**
   * Get expRanges
   * @return expRanges
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXP_RANGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<AvailDriversResponseConRangesInner> getExpRanges() {
    return expRanges;
  }


  @JsonProperty(JSON_PROPERTY_EXP_RANGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpRanges(@jakarta.annotation.Nullable List<AvailDriversResponseConRangesInner> expRanges) {
    this.expRanges = expRanges;
  }

  public AvailTDsResponse aerRanges(@jakarta.annotation.Nullable List<AvailDriversResponseConRangesInner> aerRanges) {
    
    this.aerRanges = aerRanges;
    return this;
  }

  public AvailTDsResponse addAerRangesItem(AvailDriversResponseConRangesInner aerRangesItem) {
    if (this.aerRanges == null) {
      this.aerRanges = new ArrayList<>();
    }
    this.aerRanges.add(aerRangesItem);
    return this;
  }

  /**
   * Get aerRanges
   * @return aerRanges
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AER_RANGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<AvailDriversResponseConRangesInner> getAerRanges() {
    return aerRanges;
  }


  @JsonProperty(JSON_PROPERTY_AER_RANGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAerRanges(@jakarta.annotation.Nullable List<AvailDriversResponseConRangesInner> aerRanges) {
    this.aerRanges = aerRanges;
  }

  public AvailTDsResponse pitRanges(@jakarta.annotation.Nullable List<AvailDriversResponseConRangesInner> pitRanges) {
    
    this.pitRanges = pitRanges;
    return this;
  }

  public AvailTDsResponse addPitRangesItem(AvailDriversResponseConRangesInner pitRangesItem) {
    if (this.pitRanges == null) {
      this.pitRanges = new ArrayList<>();
    }
    this.pitRanges.add(pitRangesItem);
    return this;
  }

  /**
   * Get pitRanges
   * @return pitRanges
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PIT_RANGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<AvailDriversResponseConRangesInner> getPitRanges() {
    return pitRanges;
  }


  @JsonProperty(JSON_PROPERTY_PIT_RANGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPitRanges(@jakarta.annotation.Nullable List<AvailDriversResponseConRangesInner> pitRanges) {
    this.pitRanges = pitRanges;
  }

  public AvailTDsResponse motRanges(@jakarta.annotation.Nullable List<AvailDriversResponseConRangesInner> motRanges) {
    
    this.motRanges = motRanges;
    return this;
  }

  public AvailTDsResponse addMotRangesItem(AvailDriversResponseConRangesInner motRangesItem) {
    if (this.motRanges == null) {
      this.motRanges = new ArrayList<>();
    }
    this.motRanges.add(motRangesItem);
    return this;
  }

  /**
   * Get motRanges
   * @return motRanges
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MOT_RANGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<AvailDriversResponseConRangesInner> getMotRanges() {
    return motRanges;
  }


  @JsonProperty(JSON_PROPERTY_MOT_RANGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMotRanges(@jakarta.annotation.Nullable List<AvailDriversResponseConRangesInner> motRanges) {
    this.motRanges = motRanges;
  }

  public AvailTDsResponse ageRanges(@jakarta.annotation.Nullable List<AvailDriversResponseConRangesInner> ageRanges) {
    
    this.ageRanges = ageRanges;
    return this;
  }

  public AvailTDsResponse addAgeRangesItem(AvailDriversResponseConRangesInner ageRangesItem) {
    if (this.ageRanges == null) {
      this.ageRanges = new ArrayList<>();
    }
    this.ageRanges.add(ageRangesItem);
    return this;
  }

  /**
   * Get ageRanges
   * @return ageRanges
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AGE_RANGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<AvailDriversResponseConRangesInner> getAgeRanges() {
    return ageRanges;
  }


  @JsonProperty(JSON_PROPERTY_AGE_RANGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAgeRanges(@jakarta.annotation.Nullable List<AvailDriversResponseConRangesInner> ageRanges) {
    this.ageRanges = ageRanges;
  }

  public AvailTDsResponse minsalRanges(@jakarta.annotation.Nullable List<AvailDriversResponseConRangesInner> minsalRanges) {
    
    this.minsalRanges = minsalRanges;
    return this;
  }

  public AvailTDsResponse addMinsalRangesItem(AvailDriversResponseConRangesInner minsalRangesItem) {
    if (this.minsalRanges == null) {
      this.minsalRanges = new ArrayList<>();
    }
    this.minsalRanges.add(minsalRangesItem);
    return this;
  }

  /**
   * Get minsalRanges
   * @return minsalRanges
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MINSAL_RANGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<AvailDriversResponseConRangesInner> getMinsalRanges() {
    return minsalRanges;
  }


  @JsonProperty(JSON_PROPERTY_MINSAL_RANGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMinsalRanges(@jakarta.annotation.Nullable List<AvailDriversResponseConRangesInner> minsalRanges) {
    this.minsalRanges = minsalRanges;
  }

  public AvailTDsResponse offRanges(@jakarta.annotation.Nullable List<AvailDriversResponseConRangesInner> offRanges) {
    
    this.offRanges = offRanges;
    return this;
  }

  public AvailTDsResponse addOffRangesItem(AvailDriversResponseConRangesInner offRangesItem) {
    if (this.offRanges == null) {
      this.offRanges = new ArrayList<>();
    }
    this.offRanges.add(offRangesItem);
    return this;
  }

  /**
   * Get offRanges
   * @return offRanges
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OFF_RANGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<AvailDriversResponseConRangesInner> getOffRanges() {
    return offRanges;
  }


  @JsonProperty(JSON_PROPERTY_OFF_RANGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOffRanges(@jakarta.annotation.Nullable List<AvailDriversResponseConRangesInner> offRanges) {
    this.offRanges = offRanges;
  }

  public AvailTDsResponse showAlertSL(@jakarta.annotation.Nullable Boolean showAlertSL) {
    
    this.showAlertSL = showAlertSL;
    return this;
  }

  /**
   * Get showAlertSL
   * @return showAlertSL
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHOW_ALERT_S_L)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getShowAlertSL() {
    return showAlertSL;
  }


  @JsonProperty(JSON_PROPERTY_SHOW_ALERT_S_L)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShowAlertSL(@jakarta.annotation.Nullable Boolean showAlertSL) {
    this.showAlertSL = showAlertSL;
  }

  public AvailTDsResponse pageCount(@jakarta.annotation.Nullable Integer pageCount) {
    
    this.pageCount = pageCount;
    return this;
  }

  /**
   * Get pageCount
   * @return pageCount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAGE_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPageCount() {
    return pageCount;
  }


  @JsonProperty(JSON_PROPERTY_PAGE_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPageCount(@jakarta.annotation.Nullable Integer pageCount) {
    this.pageCount = pageCount;
  }

  public AvailTDsResponse pageSize(@jakarta.annotation.Nullable String pageSize) {
    
    this.pageSize = pageSize;
    return this;
  }

  /**
   * Get pageSize
   * @return pageSize
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAGE_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPageSize() {
    return pageSize;
  }


  @JsonProperty(JSON_PROPERTY_PAGE_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPageSize(@jakarta.annotation.Nullable String pageSize) {
    this.pageSize = pageSize;
  }

  public AvailTDsResponse pageIndex(@jakarta.annotation.Nullable Integer pageIndex) {
    
    this.pageIndex = pageIndex;
    return this;
  }

  /**
   * Get pageIndex
   * @return pageIndex
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAGE_INDEX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPageIndex() {
    return pageIndex;
  }


  @JsonProperty(JSON_PROPERTY_PAGE_INDEX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPageIndex(@jakarta.annotation.Nullable Integer pageIndex) {
    this.pageIndex = pageIndex;
  }

  public AvailTDsResponse apiRequestsRemaining(@jakarta.annotation.Nullable Integer apiRequestsRemaining) {
    
    this.apiRequestsRemaining = apiRequestsRemaining;
    return this;
  }

  /**
   * Get apiRequestsRemaining
   * @return apiRequestsRemaining
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_API_REQUESTS_REMAINING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getApiRequestsRemaining() {
    return apiRequestsRemaining;
  }


  @JsonProperty(JSON_PROPERTY_API_REQUESTS_REMAINING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApiRequestsRemaining(@jakarta.annotation.Nullable Integer apiRequestsRemaining) {
    this.apiRequestsRemaining = apiRequestsRemaining;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AvailTDsResponse availTDsResponse = (AvailTDsResponse) o;
    return Objects.equals(this.loadingDataState, availTDsResponse.loadingDataState) &&
        Objects.equals(this.tds, availTDsResponse.tds) &&
        Objects.equals(this.OA, availTDsResponse.OA) &&
        Objects.equals(this.filter1, availTDsResponse.filter1) &&
        Objects.equals(this.filter2, availTDsResponse.filter2) &&
        Objects.equals(this.filter3, availTDsResponse.filter3) &&
        Objects.equals(this.filter1Range, availTDsResponse.filter1Range) &&
        Objects.equals(this.filter2Range, availTDsResponse.filter2Range) &&
        Objects.equals(this.filter3Range, availTDsResponse.filter3Range) &&
        Objects.equals(this.sortParam, availTDsResponse.sortParam) &&
        Objects.equals(this.ranges, availTDsResponse.ranges) &&
        Objects.equals(this.leaRanges, availTDsResponse.leaRanges) &&
        Objects.equals(this.mecRanges, availTDsResponse.mecRanges) &&
        Objects.equals(this.eleRanges, availTDsResponse.eleRanges) &&
        Objects.equals(this.expRanges, availTDsResponse.expRanges) &&
        Objects.equals(this.aerRanges, availTDsResponse.aerRanges) &&
        Objects.equals(this.pitRanges, availTDsResponse.pitRanges) &&
        Objects.equals(this.motRanges, availTDsResponse.motRanges) &&
        Objects.equals(this.ageRanges, availTDsResponse.ageRanges) &&
        Objects.equals(this.minsalRanges, availTDsResponse.minsalRanges) &&
        Objects.equals(this.offRanges, availTDsResponse.offRanges) &&
        Objects.equals(this.showAlertSL, availTDsResponse.showAlertSL) &&
        Objects.equals(this.pageCount, availTDsResponse.pageCount) &&
        Objects.equals(this.pageSize, availTDsResponse.pageSize) &&
        Objects.equals(this.pageIndex, availTDsResponse.pageIndex) &&
        Objects.equals(this.apiRequestsRemaining, availTDsResponse.apiRequestsRemaining);
  }

  @Override
  public int hashCode() {
    return Objects.hash(loadingDataState, tds, OA, filter1, filter2, filter3, filter1Range, filter2Range, filter3Range, sortParam, ranges, leaRanges, mecRanges, eleRanges, expRanges, aerRanges, pitRanges, motRanges, ageRanges, minsalRanges, offRanges, showAlertSL, pageCount, pageSize, pageIndex, apiRequestsRemaining);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AvailTDsResponse {\n");
    sb.append("    loadingDataState: ").append(toIndentedString(loadingDataState)).append("\n");
    sb.append("    tds: ").append(toIndentedString(tds)).append("\n");
    sb.append("    OA: ").append(toIndentedString(OA)).append("\n");
    sb.append("    filter1: ").append(toIndentedString(filter1)).append("\n");
    sb.append("    filter2: ").append(toIndentedString(filter2)).append("\n");
    sb.append("    filter3: ").append(toIndentedString(filter3)).append("\n");
    sb.append("    filter1Range: ").append(toIndentedString(filter1Range)).append("\n");
    sb.append("    filter2Range: ").append(toIndentedString(filter2Range)).append("\n");
    sb.append("    filter3Range: ").append(toIndentedString(filter3Range)).append("\n");
    sb.append("    sortParam: ").append(toIndentedString(sortParam)).append("\n");
    sb.append("    ranges: ").append(toIndentedString(ranges)).append("\n");
    sb.append("    leaRanges: ").append(toIndentedString(leaRanges)).append("\n");
    sb.append("    mecRanges: ").append(toIndentedString(mecRanges)).append("\n");
    sb.append("    eleRanges: ").append(toIndentedString(eleRanges)).append("\n");
    sb.append("    expRanges: ").append(toIndentedString(expRanges)).append("\n");
    sb.append("    aerRanges: ").append(toIndentedString(aerRanges)).append("\n");
    sb.append("    pitRanges: ").append(toIndentedString(pitRanges)).append("\n");
    sb.append("    motRanges: ").append(toIndentedString(motRanges)).append("\n");
    sb.append("    ageRanges: ").append(toIndentedString(ageRanges)).append("\n");
    sb.append("    minsalRanges: ").append(toIndentedString(minsalRanges)).append("\n");
    sb.append("    offRanges: ").append(toIndentedString(offRanges)).append("\n");
    sb.append("    showAlertSL: ").append(toIndentedString(showAlertSL)).append("\n");
    sb.append("    pageCount: ").append(toIndentedString(pageCount)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    pageIndex: ").append(toIndentedString(pageIndex)).append("\n");
    sb.append("    apiRequestsRemaining: ").append(toIndentedString(apiRequestsRemaining)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

