/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * AvailDriversResponseDriversInner
 */
@JsonPropertyOrder({
  AvailDriversResponseDriversInner.JSON_PROPERTY_IDX,
  AvailDriversResponseDriversInner.JSON_PROPERTY_DRI_ID,
  AvailDriversResponseDriversInner.JSON_PROPERTY_NAME,
  AvailDriversResponseDriversInner.JSON_PROPERTY_NAT_CODE,
  AvailDriversResponseDriversInner.JSON_PROPERTY_RETIRING,
  AvailDriversResponseDriversInner.JSON_PROPERTY_O_A,
  AvailDriversResponseDriversInner.JSON_PROPERTY_AGE,
  AvailDriversResponseDriversInner.JSON_PROPERTY_SALARY,
  AvailDriversResponseDriversInner.JSON_PROPERTY_SIGN_FEE,
  AvailDriversResponseDriversInner.JSON_PROPERTY_OFFERS,
  AvailDriversResponseDriversInner.JSON_PROPERTY_IN_SHORTLIST
})
@JsonTypeName("AvailDriversResponse_drivers_inner")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class AvailDriversResponseDriversInner {
  public static final String JSON_PROPERTY_IDX = "idx";
  @jakarta.annotation.Nullable
  private Integer idx;

  public static final String JSON_PROPERTY_DRI_ID = "driId";
  @jakarta.annotation.Nullable
  private Integer driId;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_NAT_CODE = "natCode";
  @jakarta.annotation.Nullable
  private String natCode;

  public static final String JSON_PROPERTY_RETIRING = "retiring";
  @jakarta.annotation.Nullable
  private String retiring;

  public static final String JSON_PROPERTY_O_A = "OA";
  @jakarta.annotation.Nullable
  private String OA;

  public static final String JSON_PROPERTY_AGE = "age";
  @jakarta.annotation.Nullable
  private String age;

  public static final String JSON_PROPERTY_SALARY = "salary";
  @jakarta.annotation.Nullable
  private String salary;

  public static final String JSON_PROPERTY_SIGN_FEE = "signFee";
  @jakarta.annotation.Nullable
  private String signFee;

  public static final String JSON_PROPERTY_OFFERS = "offers";
  @jakarta.annotation.Nullable
  private Integer offers;

  public static final String JSON_PROPERTY_IN_SHORTLIST = "inShortlist";
  @jakarta.annotation.Nullable
  private Integer inShortlist;

  public AvailDriversResponseDriversInner() {
  }

  public AvailDriversResponseDriversInner idx(@jakarta.annotation.Nullable Integer idx) {
    
    this.idx = idx;
    return this;
  }

  /**
   * Get idx
   * @return idx
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IDX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getIdx() {
    return idx;
  }


  @JsonProperty(JSON_PROPERTY_IDX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdx(@jakarta.annotation.Nullable Integer idx) {
    this.idx = idx;
  }

  public AvailDriversResponseDriversInner driId(@jakarta.annotation.Nullable Integer driId) {
    
    this.driId = driId;
    return this;
  }

  /**
   * Get driId
   * @return driId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DRI_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getDriId() {
    return driId;
  }


  @JsonProperty(JSON_PROPERTY_DRI_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDriId(@jakarta.annotation.Nullable Integer driId) {
    this.driId = driId;
  }

  public AvailDriversResponseDriversInner name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  public AvailDriversResponseDriversInner natCode(@jakarta.annotation.Nullable String natCode) {
    
    this.natCode = natCode;
    return this;
  }

  /**
   * Get natCode
   * @return natCode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNatCode() {
    return natCode;
  }


  @JsonProperty(JSON_PROPERTY_NAT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNatCode(@jakarta.annotation.Nullable String natCode) {
    this.natCode = natCode;
  }

  public AvailDriversResponseDriversInner retiring(@jakarta.annotation.Nullable String retiring) {
    
    this.retiring = retiring;
    return this;
  }

  /**
   * Get retiring
   * @return retiring
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RETIRING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRetiring() {
    return retiring;
  }


  @JsonProperty(JSON_PROPERTY_RETIRING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRetiring(@jakarta.annotation.Nullable String retiring) {
    this.retiring = retiring;
  }

  public AvailDriversResponseDriversInner OA(@jakarta.annotation.Nullable String OA) {
    
    this.OA = OA;
    return this;
  }

  /**
   * Get OA
   * @return OA
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_O_A)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOA() {
    return OA;
  }


  @JsonProperty(JSON_PROPERTY_O_A)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOA(@jakarta.annotation.Nullable String OA) {
    this.OA = OA;
  }

  public AvailDriversResponseDriversInner age(@jakarta.annotation.Nullable String age) {
    
    this.age = age;
    return this;
  }

  /**
   * Get age
   * @return age
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAge() {
    return age;
  }


  @JsonProperty(JSON_PROPERTY_AGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAge(@jakarta.annotation.Nullable String age) {
    this.age = age;
  }

  public AvailDriversResponseDriversInner salary(@jakarta.annotation.Nullable String salary) {
    
    this.salary = salary;
    return this;
  }

  /**
   * Get salary
   * @return salary
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SALARY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSalary() {
    return salary;
  }


  @JsonProperty(JSON_PROPERTY_SALARY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSalary(@jakarta.annotation.Nullable String salary) {
    this.salary = salary;
  }

  public AvailDriversResponseDriversInner signFee(@jakarta.annotation.Nullable String signFee) {
    
    this.signFee = signFee;
    return this;
  }

  /**
   * Get signFee
   * @return signFee
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIGN_FEE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSignFee() {
    return signFee;
  }


  @JsonProperty(JSON_PROPERTY_SIGN_FEE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignFee(@jakarta.annotation.Nullable String signFee) {
    this.signFee = signFee;
  }

  public AvailDriversResponseDriversInner offers(@jakarta.annotation.Nullable Integer offers) {
    
    this.offers = offers;
    return this;
  }

  /**
   * Get offers
   * @return offers
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OFFERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getOffers() {
    return offers;
  }


  @JsonProperty(JSON_PROPERTY_OFFERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOffers(@jakarta.annotation.Nullable Integer offers) {
    this.offers = offers;
  }

  public AvailDriversResponseDriversInner inShortlist(@jakarta.annotation.Nullable Integer inShortlist) {
    
    this.inShortlist = inShortlist;
    return this;
  }

  /**
   * Get inShortlist
   * @return inShortlist
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IN_SHORTLIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getInShortlist() {
    return inShortlist;
  }


  @JsonProperty(JSON_PROPERTY_IN_SHORTLIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInShortlist(@jakarta.annotation.Nullable Integer inShortlist) {
    this.inShortlist = inShortlist;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AvailDriversResponseDriversInner availDriversResponseDriversInner = (AvailDriversResponseDriversInner) o;
    return Objects.equals(this.idx, availDriversResponseDriversInner.idx) &&
        Objects.equals(this.driId, availDriversResponseDriversInner.driId) &&
        Objects.equals(this.name, availDriversResponseDriversInner.name) &&
        Objects.equals(this.natCode, availDriversResponseDriversInner.natCode) &&
        Objects.equals(this.retiring, availDriversResponseDriversInner.retiring) &&
        Objects.equals(this.OA, availDriversResponseDriversInner.OA) &&
        Objects.equals(this.age, availDriversResponseDriversInner.age) &&
        Objects.equals(this.salary, availDriversResponseDriversInner.salary) &&
        Objects.equals(this.signFee, availDriversResponseDriversInner.signFee) &&
        Objects.equals(this.offers, availDriversResponseDriversInner.offers) &&
        Objects.equals(this.inShortlist, availDriversResponseDriversInner.inShortlist);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idx, driId, name, natCode, retiring, OA, age, salary, signFee, offers, inShortlist);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AvailDriversResponseDriversInner {\n");
    sb.append("    idx: ").append(toIndentedString(idx)).append("\n");
    sb.append("    driId: ").append(toIndentedString(driId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    natCode: ").append(toIndentedString(natCode)).append("\n");
    sb.append("    retiring: ").append(toIndentedString(retiring)).append("\n");
    sb.append("    OA: ").append(toIndentedString(OA)).append("\n");
    sb.append("    age: ").append(toIndentedString(age)).append("\n");
    sb.append("    salary: ").append(toIndentedString(salary)).append("\n");
    sb.append("    signFee: ").append(toIndentedString(signFee)).append("\n");
    sb.append("    offers: ").append(toIndentedString(offers)).append("\n");
    sb.append("    inShortlist: ").append(toIndentedString(inShortlist)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

