/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * DriverProfileResponseFaceJSONMouth
 */
@JsonPropertyOrder({
  DriverProfileResponseFaceJSONMouth.JSON_PROPERTY_ID,
  DriverProfileResponseFaceJSONMouth.JSON_PROPERTY_FLIP
})
@JsonTypeName("DriverProfileResponse_faceJSON_mouth")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class DriverProfileResponseFaceJSONMouth {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_FLIP = "flip";
  @jakarta.annotation.Nullable
  private Boolean flip;

  public DriverProfileResponseFaceJSONMouth() {
  }

  public DriverProfileResponseFaceJSONMouth id(@jakarta.annotation.Nullable String id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable String id) {
    this.id = id;
  }

  public DriverProfileResponseFaceJSONMouth flip(@jakarta.annotation.Nullable Boolean flip) {
    
    this.flip = flip;
    return this;
  }

  /**
   * Get flip
   * @return flip
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FLIP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getFlip() {
    return flip;
  }


  @JsonProperty(JSON_PROPERTY_FLIP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFlip(@jakarta.annotation.Nullable Boolean flip) {
    this.flip = flip;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DriverProfileResponseFaceJSONMouth driverProfileResponseFaceJSONMouth = (DriverProfileResponseFaceJSONMouth) o;
    return Objects.equals(this.id, driverProfileResponseFaceJSONMouth.id) &&
        Objects.equals(this.flip, driverProfileResponseFaceJSONMouth.flip);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, flip);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DriverProfileResponseFaceJSONMouth {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    flip: ").append(toIndentedString(flip)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

