/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.jlobato.gpro.model.SnFHistoryResponseDataGraphYAxisLabels;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * EconomyHistoryGraphResponseDataGraphXAxis
 */
@JsonPropertyOrder({
  EconomyHistoryGraphResponseDataGraphXAxis.JSON_PROPERTY_CATEGORIES,
  EconomyHistoryGraphResponseDataGraphXAxis.JSON_PROPERTY_TICK_POSITIONS,
  EconomyHistoryGraphResponseDataGraphXAxis.JSON_PROPERTY_LABELS
})
@JsonTypeName("EconomyHistoryGraphResponse_dataGraph_xAxis")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class EconomyHistoryGraphResponseDataGraphXAxis {
  public static final String JSON_PROPERTY_CATEGORIES = "categories";
  @jakarta.annotation.Nullable
  private List<String> categories = new ArrayList<>();

  public static final String JSON_PROPERTY_TICK_POSITIONS = "tickPositions";
  @jakarta.annotation.Nullable
  private List<String> tickPositions = new ArrayList<>();

  public static final String JSON_PROPERTY_LABELS = "labels";
  @jakarta.annotation.Nullable
  private SnFHistoryResponseDataGraphYAxisLabels labels;

  public EconomyHistoryGraphResponseDataGraphXAxis() {
  }

  public EconomyHistoryGraphResponseDataGraphXAxis categories(@jakarta.annotation.Nullable List<String> categories) {
    
    this.categories = categories;
    return this;
  }

  public EconomyHistoryGraphResponseDataGraphXAxis addCategoriesItem(String categoriesItem) {
    if (this.categories == null) {
      this.categories = new ArrayList<>();
    }
    this.categories.add(categoriesItem);
    return this;
  }

  /**
   * Get categories
   * @return categories
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CATEGORIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getCategories() {
    return categories;
  }


  @JsonProperty(JSON_PROPERTY_CATEGORIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCategories(@jakarta.annotation.Nullable List<String> categories) {
    this.categories = categories;
  }

  public EconomyHistoryGraphResponseDataGraphXAxis tickPositions(@jakarta.annotation.Nullable List<String> tickPositions) {
    
    this.tickPositions = tickPositions;
    return this;
  }

  public EconomyHistoryGraphResponseDataGraphXAxis addTickPositionsItem(String tickPositionsItem) {
    if (this.tickPositions == null) {
      this.tickPositions = new ArrayList<>();
    }
    this.tickPositions.add(tickPositionsItem);
    return this;
  }

  /**
   * Get tickPositions
   * @return tickPositions
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TICK_POSITIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getTickPositions() {
    return tickPositions;
  }


  @JsonProperty(JSON_PROPERTY_TICK_POSITIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTickPositions(@jakarta.annotation.Nullable List<String> tickPositions) {
    this.tickPositions = tickPositions;
  }

  public EconomyHistoryGraphResponseDataGraphXAxis labels(@jakarta.annotation.Nullable SnFHistoryResponseDataGraphYAxisLabels labels) {
    
    this.labels = labels;
    return this;
  }

  /**
   * Get labels
   * @return labels
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LABELS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SnFHistoryResponseDataGraphYAxisLabels getLabels() {
    return labels;
  }


  @JsonProperty(JSON_PROPERTY_LABELS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLabels(@jakarta.annotation.Nullable SnFHistoryResponseDataGraphYAxisLabels labels) {
    this.labels = labels;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EconomyHistoryGraphResponseDataGraphXAxis economyHistoryGraphResponseDataGraphXAxis = (EconomyHistoryGraphResponseDataGraphXAxis) o;
    return Objects.equals(this.categories, economyHistoryGraphResponseDataGraphXAxis.categories) &&
        Objects.equals(this.tickPositions, economyHistoryGraphResponseDataGraphXAxis.tickPositions) &&
        Objects.equals(this.labels, economyHistoryGraphResponseDataGraphXAxis.labels);
  }

  @Override
  public int hashCode() {
    return Objects.hash(categories, tickPositions, labels);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EconomyHistoryGraphResponseDataGraphXAxis {\n");
    sb.append("    categories: ").append(toIndentedString(categories)).append("\n");
    sb.append("    tickPositions: ").append(toIndentedString(tickPositions)).append("\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

