/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.jlobato.gpro.model.EconomyHistoryResponseDataInner;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * EconomyHistoryResponse
 */
@JsonPropertyOrder({
  EconomyHistoryResponse.JSON_PROPERTY_LOADING_DATA_STATE,
  EconomyHistoryResponse.JSON_PROPERTY_CUR_PAGE,
  EconomyHistoryResponse.JSON_PROPERTY_TOT_PAGES,
  EconomyHistoryResponse.JSON_PROPERTY_DATA,
  EconomyHistoryResponse.JSON_PROPERTY_API_REQUESTS_REMAINING
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class EconomyHistoryResponse {
  public static final String JSON_PROPERTY_LOADING_DATA_STATE = "loadingDataState";
  @jakarta.annotation.Nullable
  private Integer loadingDataState;

  public static final String JSON_PROPERTY_CUR_PAGE = "curPage";
  @jakarta.annotation.Nullable
  private Integer curPage;

  public static final String JSON_PROPERTY_TOT_PAGES = "totPages";
  @jakarta.annotation.Nullable
  private Integer totPages;

  public static final String JSON_PROPERTY_DATA = "data";
  @jakarta.annotation.Nullable
  private List<EconomyHistoryResponseDataInner> data = new ArrayList<>();

  public static final String JSON_PROPERTY_API_REQUESTS_REMAINING = "apiRequestsRemaining";
  @jakarta.annotation.Nullable
  private Integer apiRequestsRemaining;

  public EconomyHistoryResponse() {
  }

  public EconomyHistoryResponse loadingDataState(@jakarta.annotation.Nullable Integer loadingDataState) {
    
    this.loadingDataState = loadingDataState;
    return this;
  }

  /**
   * Get loadingDataState
   * @return loadingDataState
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOADING_DATA_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getLoadingDataState() {
    return loadingDataState;
  }


  @JsonProperty(JSON_PROPERTY_LOADING_DATA_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLoadingDataState(@jakarta.annotation.Nullable Integer loadingDataState) {
    this.loadingDataState = loadingDataState;
  }

  public EconomyHistoryResponse curPage(@jakarta.annotation.Nullable Integer curPage) {
    
    this.curPage = curPage;
    return this;
  }

  /**
   * Get curPage
   * @return curPage
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CUR_PAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCurPage() {
    return curPage;
  }


  @JsonProperty(JSON_PROPERTY_CUR_PAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurPage(@jakarta.annotation.Nullable Integer curPage) {
    this.curPage = curPage;
  }

  public EconomyHistoryResponse totPages(@jakarta.annotation.Nullable Integer totPages) {
    
    this.totPages = totPages;
    return this;
  }

  /**
   * Get totPages
   * @return totPages
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOT_PAGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTotPages() {
    return totPages;
  }


  @JsonProperty(JSON_PROPERTY_TOT_PAGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotPages(@jakarta.annotation.Nullable Integer totPages) {
    this.totPages = totPages;
  }

  public EconomyHistoryResponse data(@jakarta.annotation.Nullable List<EconomyHistoryResponseDataInner> data) {
    
    this.data = data;
    return this;
  }

  public EconomyHistoryResponse addDataItem(EconomyHistoryResponseDataInner dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<>();
    }
    this.data.add(dataItem);
    return this;
  }

  /**
   * Get data
   * @return data
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<EconomyHistoryResponseDataInner> getData() {
    return data;
  }


  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setData(@jakarta.annotation.Nullable List<EconomyHistoryResponseDataInner> data) {
    this.data = data;
  }

  public EconomyHistoryResponse apiRequestsRemaining(@jakarta.annotation.Nullable Integer apiRequestsRemaining) {
    
    this.apiRequestsRemaining = apiRequestsRemaining;
    return this;
  }

  /**
   * Get apiRequestsRemaining
   * @return apiRequestsRemaining
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_API_REQUESTS_REMAINING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getApiRequestsRemaining() {
    return apiRequestsRemaining;
  }


  @JsonProperty(JSON_PROPERTY_API_REQUESTS_REMAINING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApiRequestsRemaining(@jakarta.annotation.Nullable Integer apiRequestsRemaining) {
    this.apiRequestsRemaining = apiRequestsRemaining;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EconomyHistoryResponse economyHistoryResponse = (EconomyHistoryResponse) o;
    return Objects.equals(this.loadingDataState, economyHistoryResponse.loadingDataState) &&
        Objects.equals(this.curPage, economyHistoryResponse.curPage) &&
        Objects.equals(this.totPages, economyHistoryResponse.totPages) &&
        Objects.equals(this.data, economyHistoryResponse.data) &&
        Objects.equals(this.apiRequestsRemaining, economyHistoryResponse.apiRequestsRemaining);
  }

  @Override
  public int hashCode() {
    return Objects.hash(loadingDataState, curPage, totPages, data, apiRequestsRemaining);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EconomyHistoryResponse {\n");
    sb.append("    loadingDataState: ").append(toIndentedString(loadingDataState)).append("\n");
    sb.append("    curPage: ").append(toIndentedString(curPage)).append("\n");
    sb.append("    totPages: ").append(toIndentedString(totPages)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    apiRequestsRemaining: ").append(toIndentedString(apiRequestsRemaining)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

