/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.jlobato.gpro.model.CalendarResponseGroupsInner;
import org.jlobato.gpro.model.History500OBRResponse;
import org.jlobato.gpro.model.History500OBRResponseSectionsInner;
import org.jlobato.gpro.model.HistoryCalendarResponse;
import org.jlobato.gpro.model.HistoryGroupCupResponse;
import org.jlobato.gpro.model.HistoryGroupCupResponseCupDataInner;
import org.jlobato.gpro.model.HistoryGroupStandingsResponse;
import org.jlobato.gpro.model.HistoryGroupStandingsResponseManagersInner;
import org.jlobato.gpro.model.HistoryManResultsResponse;
import org.jlobato.gpro.model.HistoryNationsCupResponse;
import org.jlobato.gpro.model.HistoryTeamStandingsResponse;
import org.jlobato.gpro.model.HistoryTeamsCupResponse;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GetHistory200Response
 */
@JsonPropertyOrder({
  GetHistory200Response.JSON_PROPERTY_LOADING_DATA_STATE,
  GetHistory200Response.JSON_PROPERTY_SECTIONS,
  GetHistory200Response.JSON_PROPERTY_GROUP,
  GetHistory200Response.JSON_PROPERTY_REQUESTED_SEASON,
  GetHistory200Response.JSON_PROPERTY_SEASON,
  GetHistory200Response.JSON_PROPERTY_TITLE,
  GetHistory200Response.JSON_PROPERTY_STATS_TYPE,
  GetHistory200Response.JSON_PROPERTY_MANAGERS,
  GetHistory200Response.JSON_PROPERTY_GROUPS,
  GetHistory200Response.JSON_PROPERTY_ERROR_TEXT,
  GetHistory200Response.JSON_PROPERTY_CUP_DATA,
  GetHistory200Response.JSON_PROPERTY_NOTE
})
@JsonTypeName("GetHistory_200_response")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class GetHistory200Response {
  public static final String JSON_PROPERTY_LOADING_DATA_STATE = "loadingDataState";
  @jakarta.annotation.Nullable
  private String loadingDataState;

  public static final String JSON_PROPERTY_SECTIONS = "sections";
  @jakarta.annotation.Nullable
  private List<History500OBRResponseSectionsInner> sections = new ArrayList<>();

  public static final String JSON_PROPERTY_GROUP = "group";
  @jakarta.annotation.Nullable
  private String group;

  public static final String JSON_PROPERTY_REQUESTED_SEASON = "requestedSeason";
  @jakarta.annotation.Nullable
  private Integer requestedSeason;

  public static final String JSON_PROPERTY_SEASON = "season";
  @jakarta.annotation.Nullable
  private Integer season;

  public static final String JSON_PROPERTY_TITLE = "title";
  @jakarta.annotation.Nullable
  private String title;

  public static final String JSON_PROPERTY_STATS_TYPE = "statsType";
  @jakarta.annotation.Nullable
  private String statsType;

  public static final String JSON_PROPERTY_MANAGERS = "managers";
  @jakarta.annotation.Nullable
  private List<HistoryGroupStandingsResponseManagersInner> managers = new ArrayList<>();

  public static final String JSON_PROPERTY_GROUPS = "groups";
  @jakarta.annotation.Nullable
  private List<CalendarResponseGroupsInner> groups = new ArrayList<>();

  public static final String JSON_PROPERTY_ERROR_TEXT = "errorText";
  @jakarta.annotation.Nullable
  private String errorText;

  public static final String JSON_PROPERTY_CUP_DATA = "cupData";
  @jakarta.annotation.Nullable
  private List<HistoryGroupCupResponseCupDataInner> cupData = new ArrayList<>();

  public static final String JSON_PROPERTY_NOTE = "note";
  @jakarta.annotation.Nullable
  private String note;

  public GetHistory200Response() {
  }

  public GetHistory200Response loadingDataState(@jakarta.annotation.Nullable String loadingDataState) {
    
    this.loadingDataState = loadingDataState;
    return this;
  }

  /**
   * Get loadingDataState
   * @return loadingDataState
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOADING_DATA_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLoadingDataState() {
    return loadingDataState;
  }


  @JsonProperty(JSON_PROPERTY_LOADING_DATA_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLoadingDataState(@jakarta.annotation.Nullable String loadingDataState) {
    this.loadingDataState = loadingDataState;
  }

  public GetHistory200Response sections(@jakarta.annotation.Nullable List<History500OBRResponseSectionsInner> sections) {
    
    this.sections = sections;
    return this;
  }

  public GetHistory200Response addSectionsItem(History500OBRResponseSectionsInner sectionsItem) {
    if (this.sections == null) {
      this.sections = new ArrayList<>();
    }
    this.sections.add(sectionsItem);
    return this;
  }

  /**
   * Get sections
   * @return sections
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SECTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<History500OBRResponseSectionsInner> getSections() {
    return sections;
  }


  @JsonProperty(JSON_PROPERTY_SECTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSections(@jakarta.annotation.Nullable List<History500OBRResponseSectionsInner> sections) {
    this.sections = sections;
  }

  public GetHistory200Response group(@jakarta.annotation.Nullable String group) {
    
    this.group = group;
    return this;
  }

  /**
   * Get group
   * @return group
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GROUP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGroup() {
    return group;
  }


  @JsonProperty(JSON_PROPERTY_GROUP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGroup(@jakarta.annotation.Nullable String group) {
    this.group = group;
  }

  public GetHistory200Response requestedSeason(@jakarta.annotation.Nullable Integer requestedSeason) {
    
    this.requestedSeason = requestedSeason;
    return this;
  }

  /**
   * Get requestedSeason
   * @return requestedSeason
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REQUESTED_SEASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRequestedSeason() {
    return requestedSeason;
  }


  @JsonProperty(JSON_PROPERTY_REQUESTED_SEASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRequestedSeason(@jakarta.annotation.Nullable Integer requestedSeason) {
    this.requestedSeason = requestedSeason;
  }

  public GetHistory200Response season(@jakarta.annotation.Nullable Integer season) {
    
    this.season = season;
    return this;
  }

  /**
   * Get season
   * @return season
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSeason() {
    return season;
  }


  @JsonProperty(JSON_PROPERTY_SEASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeason(@jakarta.annotation.Nullable Integer season) {
    this.season = season;
  }

  public GetHistory200Response title(@jakarta.annotation.Nullable String title) {
    
    this.title = title;
    return this;
  }

  /**
   * Get title
   * @return title
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTitle() {
    return title;
  }


  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTitle(@jakarta.annotation.Nullable String title) {
    this.title = title;
  }

  public GetHistory200Response statsType(@jakarta.annotation.Nullable String statsType) {
    
    this.statsType = statsType;
    return this;
  }

  /**
   * Get statsType
   * @return statsType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATS_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatsType() {
    return statsType;
  }


  @JsonProperty(JSON_PROPERTY_STATS_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatsType(@jakarta.annotation.Nullable String statsType) {
    this.statsType = statsType;
  }

  public GetHistory200Response managers(@jakarta.annotation.Nullable List<HistoryGroupStandingsResponseManagersInner> managers) {
    
    this.managers = managers;
    return this;
  }

  public GetHistory200Response addManagersItem(HistoryGroupStandingsResponseManagersInner managersItem) {
    if (this.managers == null) {
      this.managers = new ArrayList<>();
    }
    this.managers.add(managersItem);
    return this;
  }

  /**
   * Get managers
   * @return managers
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MANAGERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<HistoryGroupStandingsResponseManagersInner> getManagers() {
    return managers;
  }


  @JsonProperty(JSON_PROPERTY_MANAGERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManagers(@jakarta.annotation.Nullable List<HistoryGroupStandingsResponseManagersInner> managers) {
    this.managers = managers;
  }

  public GetHistory200Response groups(@jakarta.annotation.Nullable List<CalendarResponseGroupsInner> groups) {
    
    this.groups = groups;
    return this;
  }

  public GetHistory200Response addGroupsItem(CalendarResponseGroupsInner groupsItem) {
    if (this.groups == null) {
      this.groups = new ArrayList<>();
    }
    this.groups.add(groupsItem);
    return this;
  }

  /**
   * Get groups
   * @return groups
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GROUPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CalendarResponseGroupsInner> getGroups() {
    return groups;
  }


  @JsonProperty(JSON_PROPERTY_GROUPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGroups(@jakarta.annotation.Nullable List<CalendarResponseGroupsInner> groups) {
    this.groups = groups;
  }

  public GetHistory200Response errorText(@jakarta.annotation.Nullable String errorText) {
    
    this.errorText = errorText;
    return this;
  }

  /**
   * Get errorText
   * @return errorText
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ERROR_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getErrorText() {
    return errorText;
  }


  @JsonProperty(JSON_PROPERTY_ERROR_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setErrorText(@jakarta.annotation.Nullable String errorText) {
    this.errorText = errorText;
  }

  public GetHistory200Response cupData(@jakarta.annotation.Nullable List<HistoryGroupCupResponseCupDataInner> cupData) {
    
    this.cupData = cupData;
    return this;
  }

  public GetHistory200Response addCupDataItem(HistoryGroupCupResponseCupDataInner cupDataItem) {
    if (this.cupData == null) {
      this.cupData = new ArrayList<>();
    }
    this.cupData.add(cupDataItem);
    return this;
  }

  /**
   * Get cupData
   * @return cupData
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CUP_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<HistoryGroupCupResponseCupDataInner> getCupData() {
    return cupData;
  }


  @JsonProperty(JSON_PROPERTY_CUP_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCupData(@jakarta.annotation.Nullable List<HistoryGroupCupResponseCupDataInner> cupData) {
    this.cupData = cupData;
  }

  public GetHistory200Response note(@jakarta.annotation.Nullable String note) {
    
    this.note = note;
    return this;
  }

  /**
   * Get note
   * @return note
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NOTE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNote() {
    return note;
  }


  @JsonProperty(JSON_PROPERTY_NOTE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNote(@jakarta.annotation.Nullable String note) {
    this.note = note;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetHistory200Response getHistory200Response = (GetHistory200Response) o;
    return Objects.equals(this.loadingDataState, getHistory200Response.loadingDataState) &&
        Objects.equals(this.sections, getHistory200Response.sections) &&
        Objects.equals(this.group, getHistory200Response.group) &&
        Objects.equals(this.requestedSeason, getHistory200Response.requestedSeason) &&
        Objects.equals(this.season, getHistory200Response.season) &&
        Objects.equals(this.title, getHistory200Response.title) &&
        Objects.equals(this.statsType, getHistory200Response.statsType) &&
        Objects.equals(this.managers, getHistory200Response.managers) &&
        Objects.equals(this.groups, getHistory200Response.groups) &&
        Objects.equals(this.errorText, getHistory200Response.errorText) &&
        Objects.equals(this.cupData, getHistory200Response.cupData) &&
        Objects.equals(this.note, getHistory200Response.note);
  }

  @Override
  public int hashCode() {
    return Objects.hash(loadingDataState, sections, group, requestedSeason, season, title, statsType, managers, groups, errorText, cupData, note);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetHistory200Response {\n");
    sb.append("    loadingDataState: ").append(toIndentedString(loadingDataState)).append("\n");
    sb.append("    sections: ").append(toIndentedString(sections)).append("\n");
    sb.append("    group: ").append(toIndentedString(group)).append("\n");
    sb.append("    requestedSeason: ").append(toIndentedString(requestedSeason)).append("\n");
    sb.append("    season: ").append(toIndentedString(season)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    statsType: ").append(toIndentedString(statsType)).append("\n");
    sb.append("    managers: ").append(toIndentedString(managers)).append("\n");
    sb.append("    groups: ").append(toIndentedString(groups)).append("\n");
    sb.append("    errorText: ").append(toIndentedString(errorText)).append("\n");
    sb.append("    cupData: ").append(toIndentedString(cupData)).append("\n");
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

