/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * OfficeResponse
 */
@JsonPropertyOrder({
  OfficeResponse.JSON_PROPERTY_LOADING_DATA_STATE,
  OfficeResponse.JSON_PROPERTY_SEASON_NB,
  OfficeResponse.JSON_PROPERTY_RACE_NB,
  OfficeResponse.JSON_PROPERTY_TRACK_ID,
  OfficeResponse.JSON_PROPERTY_END_OF_SEASON,
  OfficeResponse.JSON_PROPERTY_ACTIVATE_TEAM_STATUS,
  OfficeResponse.JSON_PROPERTY_ACC_STATUS_ID,
  OfficeResponse.JSON_PROPERTY_ACC_STATUS,
  OfficeResponse.JSON_PROPERTY_NEXT_SEASON_RESET_DATE,
  OfficeResponse.JSON_PROPERTY_UPDATE_IN_PROGRESS,
  OfficeResponse.JSON_PROPERTY_PROGRESS,
  OfficeResponse.JSON_PROPERTY_TRACK_NAME,
  OfficeResponse.JSON_PROPERTY_TRACK_NAT_CODE,
  OfficeResponse.JSON_PROPERTY_SECONDS_LEFT,
  OfficeResponse.JSON_PROPERTY_SECONDS_LEFT_QUAL,
  OfficeResponse.JSON_PROPERTY_DONE_PRACTICE,
  OfficeResponse.JSON_PROPERTY_DONE_Q1,
  OfficeResponse.JSON_PROPERTY_DONE_Q2,
  OfficeResponse.JSON_PROPERTY_DONE_RACE_SETUP,
  OfficeResponse.JSON_PROPERTY_DONE_DRI_TRAIN,
  OfficeResponse.JSON_PROPERTY_DONE_STAFF_TRAIN,
  OfficeResponse.JSON_PROPERTY_DONE_CAR_REPAIR,
  OfficeResponse.JSON_PROPERTY_DONE_FACILITIES_UPDATE,
  OfficeResponse.JSON_PROPERTY_DONE_TESTING,
  OfficeResponse.JSON_PROPERTY_TESTING_STINTS,
  OfficeResponse.JSON_PROPERTY_SPONSORS_ALERT,
  OfficeResponse.JSON_PROPERTY_SPONSORS_NO_NEG,
  OfficeResponse.JSON_PROPERTY_TYRE_SUPPLIER_ID,
  OfficeResponse.JSON_PROPERTY_DRI_NAME,
  OfficeResponse.JSON_PROPERTY_DRI_O_A,
  OfficeResponse.JSON_PROPERTY_DRI_RACES_LEFT,
  OfficeResponse.JSON_PROPERTY_DRI_SALARY,
  OfficeResponse.JSON_PROPERTY_DRI_ENERGY,
  OfficeResponse.JSON_PROPERTY_DRI_ID,
  OfficeResponse.JSON_PROPERTY_TD_NAME,
  OfficeResponse.JSON_PROPERTY_TD_O_A,
  OfficeResponse.JSON_PROPERTY_TD_RACES_LEFT,
  OfficeResponse.JSON_PROPERTY_TD_SALARY,
  OfficeResponse.JSON_PROPERTY_TD_ID,
  OfficeResponse.JSON_PROPERTY_IS_CERTIFIED,
  OfficeResponse.JSON_PROPERTY_CHAMPS,
  OfficeResponse.JSON_PROPERTY_ACTIVATION_PIXEL_FIRED,
  OfficeResponse.JSON_PROPERTY_PTS,
  OfficeResponse.JSON_PROPERTY_POS,
  OfficeResponse.JSON_PROPERTY_AVG,
  OfficeResponse.JSON_PROPERTY_NEW_QUALIFIERS_Q1,
  OfficeResponse.JSON_PROPERTY_NEW_QUALIFIERS_Q2,
  OfficeResponse.JSON_PROPERTY_QUAL1_POS,
  OfficeResponse.JSON_PROPERTY_QUAL1_DIFF,
  OfficeResponse.JSON_PROPERTY_QUAL1_LAP_TIME,
  OfficeResponse.JSON_PROPERTY_QUAL2_POS,
  OfficeResponse.JSON_PROPERTY_QUAL2_DIFF,
  OfficeResponse.JSON_PROPERTY_QUAL2_LAP_TIME,
  OfficeResponse.JSON_PROPERTY_QUAL_S_G_POS,
  OfficeResponse.JSON_PROPERTY_QUAL_S_G_DIFF,
  OfficeResponse.JSON_PROPERTY_QUAL_S_G_LAP_TIME,
  OfficeResponse.JSON_PROPERTY_TEAM_FORUM_UNREAD_TOPICS,
  OfficeResponse.JSON_PROPERTY_FORUM_UNREAD_COUNT,
  OfficeResponse.JSON_PROPERTY_UNREAD_ANNOUNCEMENTS,
  OfficeResponse.JSON_PROPERTY_WARN_STATUS,
  OfficeResponse.JSON_PROPERTY_ACC_VIOLATION_STATUS,
  OfficeResponse.JSON_PROPERTY_STATUS_TXT,
  OfficeResponse.JSON_PROPERTY_EMAIL_NEEDS_UPDATE,
  OfficeResponse.JSON_PROPERTY_EMAIL_CONFIRMED,
  OfficeResponse.JSON_PROPERTY_NO_FREE_SPOTS,
  OfficeResponse.JSON_PROPERTY_SHOW_TUTORIAL,
  OfficeResponse.JSON_PROPERTY_NEED_REFRESH,
  OfficeResponse.JSON_PROPERTY_CASH,
  OfficeResponse.JSON_PROPERTY_API_REQUESTS_REMAINING
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class OfficeResponse {
  public static final String JSON_PROPERTY_LOADING_DATA_STATE = "loadingDataState";
  @jakarta.annotation.Nullable
  private Integer loadingDataState;

  public static final String JSON_PROPERTY_SEASON_NB = "seasonNb";
  @jakarta.annotation.Nullable
  private String seasonNb;

  public static final String JSON_PROPERTY_RACE_NB = "raceNb";
  @jakarta.annotation.Nullable
  private String raceNb;

  public static final String JSON_PROPERTY_TRACK_ID = "trackId";
  @jakarta.annotation.Nullable
  private String trackId;

  public static final String JSON_PROPERTY_END_OF_SEASON = "endOfSeason";
  @jakarta.annotation.Nullable
  private Integer endOfSeason;

  public static final String JSON_PROPERTY_ACTIVATE_TEAM_STATUS = "activateTeamStatus";
  @jakarta.annotation.Nullable
  private Integer activateTeamStatus;

  public static final String JSON_PROPERTY_ACC_STATUS_ID = "accStatusId";
  @jakarta.annotation.Nullable
  private Integer accStatusId;

  public static final String JSON_PROPERTY_ACC_STATUS = "accStatus";
  @jakarta.annotation.Nullable
  private String accStatus;

  public static final String JSON_PROPERTY_NEXT_SEASON_RESET_DATE = "nextSeasonResetDate";
  @jakarta.annotation.Nullable
  private String nextSeasonResetDate;

  public static final String JSON_PROPERTY_UPDATE_IN_PROGRESS = "updateInProgress";
  @jakarta.annotation.Nullable
  private Integer updateInProgress;

  public static final String JSON_PROPERTY_PROGRESS = "progress";
  @jakarta.annotation.Nullable
  private Integer progress;

  public static final String JSON_PROPERTY_TRACK_NAME = "trackName";
  @jakarta.annotation.Nullable
  private String trackName;

  public static final String JSON_PROPERTY_TRACK_NAT_CODE = "trackNatCode";
  @jakarta.annotation.Nullable
  private String trackNatCode;

  public static final String JSON_PROPERTY_SECONDS_LEFT = "secondsLeft";
  @jakarta.annotation.Nullable
  private String secondsLeft;

  public static final String JSON_PROPERTY_SECONDS_LEFT_QUAL = "secondsLeftQual";
  @jakarta.annotation.Nullable
  private String secondsLeftQual;

  public static final String JSON_PROPERTY_DONE_PRACTICE = "donePractice";
  @jakarta.annotation.Nullable
  private String donePractice;

  public static final String JSON_PROPERTY_DONE_Q1 = "doneQ1";
  @jakarta.annotation.Nullable
  private String doneQ1;

  public static final String JSON_PROPERTY_DONE_Q2 = "doneQ2";
  @jakarta.annotation.Nullable
  private String doneQ2;

  public static final String JSON_PROPERTY_DONE_RACE_SETUP = "doneRaceSetup";
  @jakarta.annotation.Nullable
  private String doneRaceSetup;

  public static final String JSON_PROPERTY_DONE_DRI_TRAIN = "doneDriTrain";
  @jakarta.annotation.Nullable
  private String doneDriTrain;

  public static final String JSON_PROPERTY_DONE_STAFF_TRAIN = "doneStaffTrain";
  @jakarta.annotation.Nullable
  private String doneStaffTrain;

  public static final String JSON_PROPERTY_DONE_CAR_REPAIR = "doneCarRepair";
  @jakarta.annotation.Nullable
  private String doneCarRepair;

  public static final String JSON_PROPERTY_DONE_FACILITIES_UPDATE = "doneFacilitiesUpdate";
  @jakarta.annotation.Nullable
  private String doneFacilitiesUpdate;

  public static final String JSON_PROPERTY_DONE_TESTING = "doneTesting";
  @jakarta.annotation.Nullable
  private String doneTesting;

  public static final String JSON_PROPERTY_TESTING_STINTS = "testingStints";
  @jakarta.annotation.Nullable
  private String testingStints;

  public static final String JSON_PROPERTY_SPONSORS_ALERT = "sponsorsAlert";
  @jakarta.annotation.Nullable
  private Integer sponsorsAlert;

  public static final String JSON_PROPERTY_SPONSORS_NO_NEG = "sponsorsNoNeg";
  @jakarta.annotation.Nullable
  private Integer sponsorsNoNeg;

  public static final String JSON_PROPERTY_TYRE_SUPPLIER_ID = "tyreSupplierId";
  @jakarta.annotation.Nullable
  private Integer tyreSupplierId;

  public static final String JSON_PROPERTY_DRI_NAME = "driName";
  @jakarta.annotation.Nullable
  private String driName;

  public static final String JSON_PROPERTY_DRI_O_A = "driOA";
  @jakarta.annotation.Nullable
  private String driOA;

  public static final String JSON_PROPERTY_DRI_RACES_LEFT = "driRacesLeft";
  @jakarta.annotation.Nullable
  private String driRacesLeft;

  public static final String JSON_PROPERTY_DRI_SALARY = "driSalary";
  @jakarta.annotation.Nullable
  private String driSalary;

  public static final String JSON_PROPERTY_DRI_ENERGY = "driEnergy";
  @jakarta.annotation.Nullable
  private String driEnergy;

  public static final String JSON_PROPERTY_DRI_ID = "driId";
  @jakarta.annotation.Nullable
  private String driId;

  public static final String JSON_PROPERTY_TD_NAME = "tdName";
  @jakarta.annotation.Nullable
  private String tdName;

  public static final String JSON_PROPERTY_TD_O_A = "tdOA";
  @jakarta.annotation.Nullable
  private String tdOA;

  public static final String JSON_PROPERTY_TD_RACES_LEFT = "tdRacesLeft";
  @jakarta.annotation.Nullable
  private String tdRacesLeft;

  public static final String JSON_PROPERTY_TD_SALARY = "tdSalary";
  @jakarta.annotation.Nullable
  private String tdSalary;

  public static final String JSON_PROPERTY_TD_ID = "tdId";
  @jakarta.annotation.Nullable
  private String tdId;

  public static final String JSON_PROPERTY_IS_CERTIFIED = "isCertified";
  @jakarta.annotation.Nullable
  private String isCertified;

  public static final String JSON_PROPERTY_CHAMPS = "champs";
  @jakarta.annotation.Nullable
  private String champs;

  public static final String JSON_PROPERTY_ACTIVATION_PIXEL_FIRED = "activationPixelFired";
  @jakarta.annotation.Nullable
  private String activationPixelFired;

  public static final String JSON_PROPERTY_PTS = "pts";
  @jakarta.annotation.Nullable
  private String pts;

  public static final String JSON_PROPERTY_POS = "pos";
  @jakarta.annotation.Nullable
  private String pos;

  public static final String JSON_PROPERTY_AVG = "avg";
  @jakarta.annotation.Nullable
  private String avg;

  public static final String JSON_PROPERTY_NEW_QUALIFIERS_Q1 = "newQualifiersQ1";
  @jakarta.annotation.Nullable
  private Integer newQualifiersQ1;

  public static final String JSON_PROPERTY_NEW_QUALIFIERS_Q2 = "newQualifiersQ2";
  @jakarta.annotation.Nullable
  private Integer newQualifiersQ2;

  public static final String JSON_PROPERTY_QUAL1_POS = "qual1Pos";
  @jakarta.annotation.Nullable
  private String qual1Pos;

  public static final String JSON_PROPERTY_QUAL1_DIFF = "qual1Diff";
  @jakarta.annotation.Nullable
  private String qual1Diff;

  public static final String JSON_PROPERTY_QUAL1_LAP_TIME = "qual1LapTime";
  @jakarta.annotation.Nullable
  private String qual1LapTime;

  public static final String JSON_PROPERTY_QUAL2_POS = "qual2Pos";
  @jakarta.annotation.Nullable
  private String qual2Pos;

  public static final String JSON_PROPERTY_QUAL2_DIFF = "qual2Diff";
  @jakarta.annotation.Nullable
  private String qual2Diff;

  public static final String JSON_PROPERTY_QUAL2_LAP_TIME = "qual2LapTime";
  @jakarta.annotation.Nullable
  private String qual2LapTime;

  public static final String JSON_PROPERTY_QUAL_S_G_POS = "qualSGPos";
  @jakarta.annotation.Nullable
  private String qualSGPos;

  public static final String JSON_PROPERTY_QUAL_S_G_DIFF = "qualSGDiff";
  @jakarta.annotation.Nullable
  private String qualSGDiff;

  public static final String JSON_PROPERTY_QUAL_S_G_LAP_TIME = "qualSGLapTime";
  @jakarta.annotation.Nullable
  private String qualSGLapTime;

  public static final String JSON_PROPERTY_TEAM_FORUM_UNREAD_TOPICS = "teamForumUnreadTopics";
  @jakarta.annotation.Nullable
  private Integer teamForumUnreadTopics;

  public static final String JSON_PROPERTY_FORUM_UNREAD_COUNT = "forumUnreadCount";
  @jakarta.annotation.Nullable
  private Integer forumUnreadCount;

  public static final String JSON_PROPERTY_UNREAD_ANNOUNCEMENTS = "unreadAnnouncements";
  @jakarta.annotation.Nullable
  private Integer unreadAnnouncements;

  public static final String JSON_PROPERTY_WARN_STATUS = "warnStatus";
  @jakarta.annotation.Nullable
  private Integer warnStatus;

  public static final String JSON_PROPERTY_ACC_VIOLATION_STATUS = "accViolationStatus";
  @jakarta.annotation.Nullable
  private Integer accViolationStatus;

  public static final String JSON_PROPERTY_STATUS_TXT = "statusTxt";
  @jakarta.annotation.Nullable
  private String statusTxt;

  public static final String JSON_PROPERTY_EMAIL_NEEDS_UPDATE = "emailNeedsUpdate";
  @jakarta.annotation.Nullable
  private String emailNeedsUpdate;

  public static final String JSON_PROPERTY_EMAIL_CONFIRMED = "emailConfirmed";
  @jakarta.annotation.Nullable
  private Integer emailConfirmed;

  public static final String JSON_PROPERTY_NO_FREE_SPOTS = "noFreeSpots";
  @jakarta.annotation.Nullable
  private Integer noFreeSpots;

  public static final String JSON_PROPERTY_SHOW_TUTORIAL = "showTutorial";
  @jakarta.annotation.Nullable
  private Boolean showTutorial;

  public static final String JSON_PROPERTY_NEED_REFRESH = "needRefresh";
  @jakarta.annotation.Nullable
  private Integer needRefresh;

  public static final String JSON_PROPERTY_CASH = "cash";
  @jakarta.annotation.Nullable
  private Integer cash;

  public static final String JSON_PROPERTY_API_REQUESTS_REMAINING = "apiRequestsRemaining";
  @jakarta.annotation.Nullable
  private Integer apiRequestsRemaining;

  public OfficeResponse() {
  }

  public OfficeResponse loadingDataState(@jakarta.annotation.Nullable Integer loadingDataState) {
    
    this.loadingDataState = loadingDataState;
    return this;
  }

  /**
   * Get loadingDataState
   * @return loadingDataState
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOADING_DATA_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getLoadingDataState() {
    return loadingDataState;
  }


  @JsonProperty(JSON_PROPERTY_LOADING_DATA_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLoadingDataState(@jakarta.annotation.Nullable Integer loadingDataState) {
    this.loadingDataState = loadingDataState;
  }

  public OfficeResponse seasonNb(@jakarta.annotation.Nullable String seasonNb) {
    
    this.seasonNb = seasonNb;
    return this;
  }

  /**
   * Get seasonNb
   * @return seasonNb
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEASON_NB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSeasonNb() {
    return seasonNb;
  }


  @JsonProperty(JSON_PROPERTY_SEASON_NB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeasonNb(@jakarta.annotation.Nullable String seasonNb) {
    this.seasonNb = seasonNb;
  }

  public OfficeResponse raceNb(@jakarta.annotation.Nullable String raceNb) {
    
    this.raceNb = raceNb;
    return this;
  }

  /**
   * Get raceNb
   * @return raceNb
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RACE_NB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRaceNb() {
    return raceNb;
  }


  @JsonProperty(JSON_PROPERTY_RACE_NB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRaceNb(@jakarta.annotation.Nullable String raceNb) {
    this.raceNb = raceNb;
  }

  public OfficeResponse trackId(@jakarta.annotation.Nullable String trackId) {
    
    this.trackId = trackId;
    return this;
  }

  /**
   * Get trackId
   * @return trackId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRACK_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTrackId() {
    return trackId;
  }


  @JsonProperty(JSON_PROPERTY_TRACK_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrackId(@jakarta.annotation.Nullable String trackId) {
    this.trackId = trackId;
  }

  public OfficeResponse endOfSeason(@jakarta.annotation.Nullable Integer endOfSeason) {
    
    this.endOfSeason = endOfSeason;
    return this;
  }

  /**
   * Get endOfSeason
   * @return endOfSeason
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_END_OF_SEASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getEndOfSeason() {
    return endOfSeason;
  }


  @JsonProperty(JSON_PROPERTY_END_OF_SEASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndOfSeason(@jakarta.annotation.Nullable Integer endOfSeason) {
    this.endOfSeason = endOfSeason;
  }

  public OfficeResponse activateTeamStatus(@jakarta.annotation.Nullable Integer activateTeamStatus) {
    
    this.activateTeamStatus = activateTeamStatus;
    return this;
  }

  /**
   * Get activateTeamStatus
   * @return activateTeamStatus
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACTIVATE_TEAM_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getActivateTeamStatus() {
    return activateTeamStatus;
  }


  @JsonProperty(JSON_PROPERTY_ACTIVATE_TEAM_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActivateTeamStatus(@jakarta.annotation.Nullable Integer activateTeamStatus) {
    this.activateTeamStatus = activateTeamStatus;
  }

  public OfficeResponse accStatusId(@jakarta.annotation.Nullable Integer accStatusId) {
    
    this.accStatusId = accStatusId;
    return this;
  }

  /**
   * Get accStatusId
   * @return accStatusId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACC_STATUS_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAccStatusId() {
    return accStatusId;
  }


  @JsonProperty(JSON_PROPERTY_ACC_STATUS_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccStatusId(@jakarta.annotation.Nullable Integer accStatusId) {
    this.accStatusId = accStatusId;
  }

  public OfficeResponse accStatus(@jakarta.annotation.Nullable String accStatus) {
    
    this.accStatus = accStatus;
    return this;
  }

  /**
   * Get accStatus
   * @return accStatus
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACC_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAccStatus() {
    return accStatus;
  }


  @JsonProperty(JSON_PROPERTY_ACC_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccStatus(@jakarta.annotation.Nullable String accStatus) {
    this.accStatus = accStatus;
  }

  public OfficeResponse nextSeasonResetDate(@jakarta.annotation.Nullable String nextSeasonResetDate) {
    
    this.nextSeasonResetDate = nextSeasonResetDate;
    return this;
  }

  /**
   * Get nextSeasonResetDate
   * @return nextSeasonResetDate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NEXT_SEASON_RESET_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNextSeasonResetDate() {
    return nextSeasonResetDate;
  }


  @JsonProperty(JSON_PROPERTY_NEXT_SEASON_RESET_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNextSeasonResetDate(@jakarta.annotation.Nullable String nextSeasonResetDate) {
    this.nextSeasonResetDate = nextSeasonResetDate;
  }

  public OfficeResponse updateInProgress(@jakarta.annotation.Nullable Integer updateInProgress) {
    
    this.updateInProgress = updateInProgress;
    return this;
  }

  /**
   * Get updateInProgress
   * @return updateInProgress
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATE_IN_PROGRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getUpdateInProgress() {
    return updateInProgress;
  }


  @JsonProperty(JSON_PROPERTY_UPDATE_IN_PROGRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdateInProgress(@jakarta.annotation.Nullable Integer updateInProgress) {
    this.updateInProgress = updateInProgress;
  }

  public OfficeResponse progress(@jakarta.annotation.Nullable Integer progress) {
    
    this.progress = progress;
    return this;
  }

  /**
   * Get progress
   * @return progress
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROGRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getProgress() {
    return progress;
  }


  @JsonProperty(JSON_PROPERTY_PROGRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProgress(@jakarta.annotation.Nullable Integer progress) {
    this.progress = progress;
  }

  public OfficeResponse trackName(@jakarta.annotation.Nullable String trackName) {
    
    this.trackName = trackName;
    return this;
  }

  /**
   * Get trackName
   * @return trackName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRACK_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTrackName() {
    return trackName;
  }


  @JsonProperty(JSON_PROPERTY_TRACK_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrackName(@jakarta.annotation.Nullable String trackName) {
    this.trackName = trackName;
  }

  public OfficeResponse trackNatCode(@jakarta.annotation.Nullable String trackNatCode) {
    
    this.trackNatCode = trackNatCode;
    return this;
  }

  /**
   * Get trackNatCode
   * @return trackNatCode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRACK_NAT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTrackNatCode() {
    return trackNatCode;
  }


  @JsonProperty(JSON_PROPERTY_TRACK_NAT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrackNatCode(@jakarta.annotation.Nullable String trackNatCode) {
    this.trackNatCode = trackNatCode;
  }

  public OfficeResponse secondsLeft(@jakarta.annotation.Nullable String secondsLeft) {
    
    this.secondsLeft = secondsLeft;
    return this;
  }

  /**
   * Get secondsLeft
   * @return secondsLeft
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SECONDS_LEFT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSecondsLeft() {
    return secondsLeft;
  }


  @JsonProperty(JSON_PROPERTY_SECONDS_LEFT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSecondsLeft(@jakarta.annotation.Nullable String secondsLeft) {
    this.secondsLeft = secondsLeft;
  }

  public OfficeResponse secondsLeftQual(@jakarta.annotation.Nullable String secondsLeftQual) {
    
    this.secondsLeftQual = secondsLeftQual;
    return this;
  }

  /**
   * Get secondsLeftQual
   * @return secondsLeftQual
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SECONDS_LEFT_QUAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSecondsLeftQual() {
    return secondsLeftQual;
  }


  @JsonProperty(JSON_PROPERTY_SECONDS_LEFT_QUAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSecondsLeftQual(@jakarta.annotation.Nullable String secondsLeftQual) {
    this.secondsLeftQual = secondsLeftQual;
  }

  public OfficeResponse donePractice(@jakarta.annotation.Nullable String donePractice) {
    
    this.donePractice = donePractice;
    return this;
  }

  /**
   * Get donePractice
   * @return donePractice
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DONE_PRACTICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDonePractice() {
    return donePractice;
  }


  @JsonProperty(JSON_PROPERTY_DONE_PRACTICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDonePractice(@jakarta.annotation.Nullable String donePractice) {
    this.donePractice = donePractice;
  }

  public OfficeResponse doneQ1(@jakarta.annotation.Nullable String doneQ1) {
    
    this.doneQ1 = doneQ1;
    return this;
  }

  /**
   * Get doneQ1
   * @return doneQ1
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DONE_Q1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDoneQ1() {
    return doneQ1;
  }


  @JsonProperty(JSON_PROPERTY_DONE_Q1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDoneQ1(@jakarta.annotation.Nullable String doneQ1) {
    this.doneQ1 = doneQ1;
  }

  public OfficeResponse doneQ2(@jakarta.annotation.Nullable String doneQ2) {
    
    this.doneQ2 = doneQ2;
    return this;
  }

  /**
   * Get doneQ2
   * @return doneQ2
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DONE_Q2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDoneQ2() {
    return doneQ2;
  }


  @JsonProperty(JSON_PROPERTY_DONE_Q2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDoneQ2(@jakarta.annotation.Nullable String doneQ2) {
    this.doneQ2 = doneQ2;
  }

  public OfficeResponse doneRaceSetup(@jakarta.annotation.Nullable String doneRaceSetup) {
    
    this.doneRaceSetup = doneRaceSetup;
    return this;
  }

  /**
   * Get doneRaceSetup
   * @return doneRaceSetup
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DONE_RACE_SETUP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDoneRaceSetup() {
    return doneRaceSetup;
  }


  @JsonProperty(JSON_PROPERTY_DONE_RACE_SETUP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDoneRaceSetup(@jakarta.annotation.Nullable String doneRaceSetup) {
    this.doneRaceSetup = doneRaceSetup;
  }

  public OfficeResponse doneDriTrain(@jakarta.annotation.Nullable String doneDriTrain) {
    
    this.doneDriTrain = doneDriTrain;
    return this;
  }

  /**
   * Get doneDriTrain
   * @return doneDriTrain
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DONE_DRI_TRAIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDoneDriTrain() {
    return doneDriTrain;
  }


  @JsonProperty(JSON_PROPERTY_DONE_DRI_TRAIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDoneDriTrain(@jakarta.annotation.Nullable String doneDriTrain) {
    this.doneDriTrain = doneDriTrain;
  }

  public OfficeResponse doneStaffTrain(@jakarta.annotation.Nullable String doneStaffTrain) {
    
    this.doneStaffTrain = doneStaffTrain;
    return this;
  }

  /**
   * Get doneStaffTrain
   * @return doneStaffTrain
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DONE_STAFF_TRAIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDoneStaffTrain() {
    return doneStaffTrain;
  }


  @JsonProperty(JSON_PROPERTY_DONE_STAFF_TRAIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDoneStaffTrain(@jakarta.annotation.Nullable String doneStaffTrain) {
    this.doneStaffTrain = doneStaffTrain;
  }

  public OfficeResponse doneCarRepair(@jakarta.annotation.Nullable String doneCarRepair) {
    
    this.doneCarRepair = doneCarRepair;
    return this;
  }

  /**
   * Get doneCarRepair
   * @return doneCarRepair
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DONE_CAR_REPAIR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDoneCarRepair() {
    return doneCarRepair;
  }


  @JsonProperty(JSON_PROPERTY_DONE_CAR_REPAIR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDoneCarRepair(@jakarta.annotation.Nullable String doneCarRepair) {
    this.doneCarRepair = doneCarRepair;
  }

  public OfficeResponse doneFacilitiesUpdate(@jakarta.annotation.Nullable String doneFacilitiesUpdate) {
    
    this.doneFacilitiesUpdate = doneFacilitiesUpdate;
    return this;
  }

  /**
   * Get doneFacilitiesUpdate
   * @return doneFacilitiesUpdate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DONE_FACILITIES_UPDATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDoneFacilitiesUpdate() {
    return doneFacilitiesUpdate;
  }


  @JsonProperty(JSON_PROPERTY_DONE_FACILITIES_UPDATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDoneFacilitiesUpdate(@jakarta.annotation.Nullable String doneFacilitiesUpdate) {
    this.doneFacilitiesUpdate = doneFacilitiesUpdate;
  }

  public OfficeResponse doneTesting(@jakarta.annotation.Nullable String doneTesting) {
    
    this.doneTesting = doneTesting;
    return this;
  }

  /**
   * Get doneTesting
   * @return doneTesting
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DONE_TESTING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDoneTesting() {
    return doneTesting;
  }


  @JsonProperty(JSON_PROPERTY_DONE_TESTING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDoneTesting(@jakarta.annotation.Nullable String doneTesting) {
    this.doneTesting = doneTesting;
  }

  public OfficeResponse testingStints(@jakarta.annotation.Nullable String testingStints) {
    
    this.testingStints = testingStints;
    return this;
  }

  /**
   * Get testingStints
   * @return testingStints
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TESTING_STINTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTestingStints() {
    return testingStints;
  }


  @JsonProperty(JSON_PROPERTY_TESTING_STINTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTestingStints(@jakarta.annotation.Nullable String testingStints) {
    this.testingStints = testingStints;
  }

  public OfficeResponse sponsorsAlert(@jakarta.annotation.Nullable Integer sponsorsAlert) {
    
    this.sponsorsAlert = sponsorsAlert;
    return this;
  }

  /**
   * Get sponsorsAlert
   * @return sponsorsAlert
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SPONSORS_ALERT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSponsorsAlert() {
    return sponsorsAlert;
  }


  @JsonProperty(JSON_PROPERTY_SPONSORS_ALERT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSponsorsAlert(@jakarta.annotation.Nullable Integer sponsorsAlert) {
    this.sponsorsAlert = sponsorsAlert;
  }

  public OfficeResponse sponsorsNoNeg(@jakarta.annotation.Nullable Integer sponsorsNoNeg) {
    
    this.sponsorsNoNeg = sponsorsNoNeg;
    return this;
  }

  /**
   * Get sponsorsNoNeg
   * @return sponsorsNoNeg
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SPONSORS_NO_NEG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSponsorsNoNeg() {
    return sponsorsNoNeg;
  }


  @JsonProperty(JSON_PROPERTY_SPONSORS_NO_NEG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSponsorsNoNeg(@jakarta.annotation.Nullable Integer sponsorsNoNeg) {
    this.sponsorsNoNeg = sponsorsNoNeg;
  }

  public OfficeResponse tyreSupplierId(@jakarta.annotation.Nullable Integer tyreSupplierId) {
    
    this.tyreSupplierId = tyreSupplierId;
    return this;
  }

  /**
   * Get tyreSupplierId
   * @return tyreSupplierId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYRE_SUPPLIER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTyreSupplierId() {
    return tyreSupplierId;
  }


  @JsonProperty(JSON_PROPERTY_TYRE_SUPPLIER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTyreSupplierId(@jakarta.annotation.Nullable Integer tyreSupplierId) {
    this.tyreSupplierId = tyreSupplierId;
  }

  public OfficeResponse driName(@jakarta.annotation.Nullable String driName) {
    
    this.driName = driName;
    return this;
  }

  /**
   * Get driName
   * @return driName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DRI_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDriName() {
    return driName;
  }


  @JsonProperty(JSON_PROPERTY_DRI_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDriName(@jakarta.annotation.Nullable String driName) {
    this.driName = driName;
  }

  public OfficeResponse driOA(@jakarta.annotation.Nullable String driOA) {
    
    this.driOA = driOA;
    return this;
  }

  /**
   * Get driOA
   * @return driOA
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DRI_O_A)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDriOA() {
    return driOA;
  }


  @JsonProperty(JSON_PROPERTY_DRI_O_A)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDriOA(@jakarta.annotation.Nullable String driOA) {
    this.driOA = driOA;
  }

  public OfficeResponse driRacesLeft(@jakarta.annotation.Nullable String driRacesLeft) {
    
    this.driRacesLeft = driRacesLeft;
    return this;
  }

  /**
   * Get driRacesLeft
   * @return driRacesLeft
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DRI_RACES_LEFT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDriRacesLeft() {
    return driRacesLeft;
  }


  @JsonProperty(JSON_PROPERTY_DRI_RACES_LEFT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDriRacesLeft(@jakarta.annotation.Nullable String driRacesLeft) {
    this.driRacesLeft = driRacesLeft;
  }

  public OfficeResponse driSalary(@jakarta.annotation.Nullable String driSalary) {
    
    this.driSalary = driSalary;
    return this;
  }

  /**
   * Get driSalary
   * @return driSalary
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DRI_SALARY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDriSalary() {
    return driSalary;
  }


  @JsonProperty(JSON_PROPERTY_DRI_SALARY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDriSalary(@jakarta.annotation.Nullable String driSalary) {
    this.driSalary = driSalary;
  }

  public OfficeResponse driEnergy(@jakarta.annotation.Nullable String driEnergy) {
    
    this.driEnergy = driEnergy;
    return this;
  }

  /**
   * Get driEnergy
   * @return driEnergy
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DRI_ENERGY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDriEnergy() {
    return driEnergy;
  }


  @JsonProperty(JSON_PROPERTY_DRI_ENERGY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDriEnergy(@jakarta.annotation.Nullable String driEnergy) {
    this.driEnergy = driEnergy;
  }

  public OfficeResponse driId(@jakarta.annotation.Nullable String driId) {
    
    this.driId = driId;
    return this;
  }

  /**
   * Get driId
   * @return driId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DRI_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDriId() {
    return driId;
  }


  @JsonProperty(JSON_PROPERTY_DRI_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDriId(@jakarta.annotation.Nullable String driId) {
    this.driId = driId;
  }

  public OfficeResponse tdName(@jakarta.annotation.Nullable String tdName) {
    
    this.tdName = tdName;
    return this;
  }

  /**
   * Get tdName
   * @return tdName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TD_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTdName() {
    return tdName;
  }


  @JsonProperty(JSON_PROPERTY_TD_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTdName(@jakarta.annotation.Nullable String tdName) {
    this.tdName = tdName;
  }

  public OfficeResponse tdOA(@jakarta.annotation.Nullable String tdOA) {
    
    this.tdOA = tdOA;
    return this;
  }

  /**
   * Get tdOA
   * @return tdOA
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TD_O_A)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTdOA() {
    return tdOA;
  }


  @JsonProperty(JSON_PROPERTY_TD_O_A)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTdOA(@jakarta.annotation.Nullable String tdOA) {
    this.tdOA = tdOA;
  }

  public OfficeResponse tdRacesLeft(@jakarta.annotation.Nullable String tdRacesLeft) {
    
    this.tdRacesLeft = tdRacesLeft;
    return this;
  }

  /**
   * Get tdRacesLeft
   * @return tdRacesLeft
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TD_RACES_LEFT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTdRacesLeft() {
    return tdRacesLeft;
  }


  @JsonProperty(JSON_PROPERTY_TD_RACES_LEFT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTdRacesLeft(@jakarta.annotation.Nullable String tdRacesLeft) {
    this.tdRacesLeft = tdRacesLeft;
  }

  public OfficeResponse tdSalary(@jakarta.annotation.Nullable String tdSalary) {
    
    this.tdSalary = tdSalary;
    return this;
  }

  /**
   * Get tdSalary
   * @return tdSalary
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TD_SALARY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTdSalary() {
    return tdSalary;
  }


  @JsonProperty(JSON_PROPERTY_TD_SALARY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTdSalary(@jakarta.annotation.Nullable String tdSalary) {
    this.tdSalary = tdSalary;
  }

  public OfficeResponse tdId(@jakarta.annotation.Nullable String tdId) {
    
    this.tdId = tdId;
    return this;
  }

  /**
   * Get tdId
   * @return tdId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TD_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTdId() {
    return tdId;
  }


  @JsonProperty(JSON_PROPERTY_TD_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTdId(@jakarta.annotation.Nullable String tdId) {
    this.tdId = tdId;
  }

  public OfficeResponse isCertified(@jakarta.annotation.Nullable String isCertified) {
    
    this.isCertified = isCertified;
    return this;
  }

  /**
   * Get isCertified
   * @return isCertified
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_CERTIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIsCertified() {
    return isCertified;
  }


  @JsonProperty(JSON_PROPERTY_IS_CERTIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsCertified(@jakarta.annotation.Nullable String isCertified) {
    this.isCertified = isCertified;
  }

  public OfficeResponse champs(@jakarta.annotation.Nullable String champs) {
    
    this.champs = champs;
    return this;
  }

  /**
   * Get champs
   * @return champs
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHAMPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getChamps() {
    return champs;
  }


  @JsonProperty(JSON_PROPERTY_CHAMPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChamps(@jakarta.annotation.Nullable String champs) {
    this.champs = champs;
  }

  public OfficeResponse activationPixelFired(@jakarta.annotation.Nullable String activationPixelFired) {
    
    this.activationPixelFired = activationPixelFired;
    return this;
  }

  /**
   * Get activationPixelFired
   * @return activationPixelFired
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACTIVATION_PIXEL_FIRED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getActivationPixelFired() {
    return activationPixelFired;
  }


  @JsonProperty(JSON_PROPERTY_ACTIVATION_PIXEL_FIRED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActivationPixelFired(@jakarta.annotation.Nullable String activationPixelFired) {
    this.activationPixelFired = activationPixelFired;
  }

  public OfficeResponse pts(@jakarta.annotation.Nullable String pts) {
    
    this.pts = pts;
    return this;
  }

  /**
   * Get pts
   * @return pts
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPts() {
    return pts;
  }


  @JsonProperty(JSON_PROPERTY_PTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPts(@jakarta.annotation.Nullable String pts) {
    this.pts = pts;
  }

  public OfficeResponse pos(@jakarta.annotation.Nullable String pos) {
    
    this.pos = pos;
    return this;
  }

  /**
   * Get pos
   * @return pos
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPos() {
    return pos;
  }


  @JsonProperty(JSON_PROPERTY_POS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPos(@jakarta.annotation.Nullable String pos) {
    this.pos = pos;
  }

  public OfficeResponse avg(@jakarta.annotation.Nullable String avg) {
    
    this.avg = avg;
    return this;
  }

  /**
   * Get avg
   * @return avg
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AVG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAvg() {
    return avg;
  }


  @JsonProperty(JSON_PROPERTY_AVG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAvg(@jakarta.annotation.Nullable String avg) {
    this.avg = avg;
  }

  public OfficeResponse newQualifiersQ1(@jakarta.annotation.Nullable Integer newQualifiersQ1) {
    
    this.newQualifiersQ1 = newQualifiersQ1;
    return this;
  }

  /**
   * Get newQualifiersQ1
   * @return newQualifiersQ1
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NEW_QUALIFIERS_Q1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNewQualifiersQ1() {
    return newQualifiersQ1;
  }


  @JsonProperty(JSON_PROPERTY_NEW_QUALIFIERS_Q1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNewQualifiersQ1(@jakarta.annotation.Nullable Integer newQualifiersQ1) {
    this.newQualifiersQ1 = newQualifiersQ1;
  }

  public OfficeResponse newQualifiersQ2(@jakarta.annotation.Nullable Integer newQualifiersQ2) {
    
    this.newQualifiersQ2 = newQualifiersQ2;
    return this;
  }

  /**
   * Get newQualifiersQ2
   * @return newQualifiersQ2
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NEW_QUALIFIERS_Q2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNewQualifiersQ2() {
    return newQualifiersQ2;
  }


  @JsonProperty(JSON_PROPERTY_NEW_QUALIFIERS_Q2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNewQualifiersQ2(@jakarta.annotation.Nullable Integer newQualifiersQ2) {
    this.newQualifiersQ2 = newQualifiersQ2;
  }

  public OfficeResponse qual1Pos(@jakarta.annotation.Nullable String qual1Pos) {
    
    this.qual1Pos = qual1Pos;
    return this;
  }

  /**
   * Get qual1Pos
   * @return qual1Pos
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUAL1_POS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getQual1Pos() {
    return qual1Pos;
  }


  @JsonProperty(JSON_PROPERTY_QUAL1_POS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQual1Pos(@jakarta.annotation.Nullable String qual1Pos) {
    this.qual1Pos = qual1Pos;
  }

  public OfficeResponse qual1Diff(@jakarta.annotation.Nullable String qual1Diff) {
    
    this.qual1Diff = qual1Diff;
    return this;
  }

  /**
   * Get qual1Diff
   * @return qual1Diff
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUAL1_DIFF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getQual1Diff() {
    return qual1Diff;
  }


  @JsonProperty(JSON_PROPERTY_QUAL1_DIFF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQual1Diff(@jakarta.annotation.Nullable String qual1Diff) {
    this.qual1Diff = qual1Diff;
  }

  public OfficeResponse qual1LapTime(@jakarta.annotation.Nullable String qual1LapTime) {
    
    this.qual1LapTime = qual1LapTime;
    return this;
  }

  /**
   * Get qual1LapTime
   * @return qual1LapTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUAL1_LAP_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getQual1LapTime() {
    return qual1LapTime;
  }


  @JsonProperty(JSON_PROPERTY_QUAL1_LAP_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQual1LapTime(@jakarta.annotation.Nullable String qual1LapTime) {
    this.qual1LapTime = qual1LapTime;
  }

  public OfficeResponse qual2Pos(@jakarta.annotation.Nullable String qual2Pos) {
    
    this.qual2Pos = qual2Pos;
    return this;
  }

  /**
   * Get qual2Pos
   * @return qual2Pos
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUAL2_POS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getQual2Pos() {
    return qual2Pos;
  }


  @JsonProperty(JSON_PROPERTY_QUAL2_POS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQual2Pos(@jakarta.annotation.Nullable String qual2Pos) {
    this.qual2Pos = qual2Pos;
  }

  public OfficeResponse qual2Diff(@jakarta.annotation.Nullable String qual2Diff) {
    
    this.qual2Diff = qual2Diff;
    return this;
  }

  /**
   * Get qual2Diff
   * @return qual2Diff
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUAL2_DIFF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getQual2Diff() {
    return qual2Diff;
  }


  @JsonProperty(JSON_PROPERTY_QUAL2_DIFF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQual2Diff(@jakarta.annotation.Nullable String qual2Diff) {
    this.qual2Diff = qual2Diff;
  }

  public OfficeResponse qual2LapTime(@jakarta.annotation.Nullable String qual2LapTime) {
    
    this.qual2LapTime = qual2LapTime;
    return this;
  }

  /**
   * Get qual2LapTime
   * @return qual2LapTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUAL2_LAP_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getQual2LapTime() {
    return qual2LapTime;
  }


  @JsonProperty(JSON_PROPERTY_QUAL2_LAP_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQual2LapTime(@jakarta.annotation.Nullable String qual2LapTime) {
    this.qual2LapTime = qual2LapTime;
  }

  public OfficeResponse qualSGPos(@jakarta.annotation.Nullable String qualSGPos) {
    
    this.qualSGPos = qualSGPos;
    return this;
  }

  /**
   * Get qualSGPos
   * @return qualSGPos
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUAL_S_G_POS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getQualSGPos() {
    return qualSGPos;
  }


  @JsonProperty(JSON_PROPERTY_QUAL_S_G_POS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQualSGPos(@jakarta.annotation.Nullable String qualSGPos) {
    this.qualSGPos = qualSGPos;
  }

  public OfficeResponse qualSGDiff(@jakarta.annotation.Nullable String qualSGDiff) {
    
    this.qualSGDiff = qualSGDiff;
    return this;
  }

  /**
   * Get qualSGDiff
   * @return qualSGDiff
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUAL_S_G_DIFF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getQualSGDiff() {
    return qualSGDiff;
  }


  @JsonProperty(JSON_PROPERTY_QUAL_S_G_DIFF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQualSGDiff(@jakarta.annotation.Nullable String qualSGDiff) {
    this.qualSGDiff = qualSGDiff;
  }

  public OfficeResponse qualSGLapTime(@jakarta.annotation.Nullable String qualSGLapTime) {
    
    this.qualSGLapTime = qualSGLapTime;
    return this;
  }

  /**
   * Get qualSGLapTime
   * @return qualSGLapTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUAL_S_G_LAP_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getQualSGLapTime() {
    return qualSGLapTime;
  }


  @JsonProperty(JSON_PROPERTY_QUAL_S_G_LAP_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQualSGLapTime(@jakarta.annotation.Nullable String qualSGLapTime) {
    this.qualSGLapTime = qualSGLapTime;
  }

  public OfficeResponse teamForumUnreadTopics(@jakarta.annotation.Nullable Integer teamForumUnreadTopics) {
    
    this.teamForumUnreadTopics = teamForumUnreadTopics;
    return this;
  }

  /**
   * Get teamForumUnreadTopics
   * @return teamForumUnreadTopics
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEAM_FORUM_UNREAD_TOPICS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTeamForumUnreadTopics() {
    return teamForumUnreadTopics;
  }


  @JsonProperty(JSON_PROPERTY_TEAM_FORUM_UNREAD_TOPICS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTeamForumUnreadTopics(@jakarta.annotation.Nullable Integer teamForumUnreadTopics) {
    this.teamForumUnreadTopics = teamForumUnreadTopics;
  }

  public OfficeResponse forumUnreadCount(@jakarta.annotation.Nullable Integer forumUnreadCount) {
    
    this.forumUnreadCount = forumUnreadCount;
    return this;
  }

  /**
   * Get forumUnreadCount
   * @return forumUnreadCount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FORUM_UNREAD_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getForumUnreadCount() {
    return forumUnreadCount;
  }


  @JsonProperty(JSON_PROPERTY_FORUM_UNREAD_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setForumUnreadCount(@jakarta.annotation.Nullable Integer forumUnreadCount) {
    this.forumUnreadCount = forumUnreadCount;
  }

  public OfficeResponse unreadAnnouncements(@jakarta.annotation.Nullable Integer unreadAnnouncements) {
    
    this.unreadAnnouncements = unreadAnnouncements;
    return this;
  }

  /**
   * Get unreadAnnouncements
   * @return unreadAnnouncements
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UNREAD_ANNOUNCEMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getUnreadAnnouncements() {
    return unreadAnnouncements;
  }


  @JsonProperty(JSON_PROPERTY_UNREAD_ANNOUNCEMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnreadAnnouncements(@jakarta.annotation.Nullable Integer unreadAnnouncements) {
    this.unreadAnnouncements = unreadAnnouncements;
  }

  public OfficeResponse warnStatus(@jakarta.annotation.Nullable Integer warnStatus) {
    
    this.warnStatus = warnStatus;
    return this;
  }

  /**
   * Get warnStatus
   * @return warnStatus
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WARN_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getWarnStatus() {
    return warnStatus;
  }


  @JsonProperty(JSON_PROPERTY_WARN_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWarnStatus(@jakarta.annotation.Nullable Integer warnStatus) {
    this.warnStatus = warnStatus;
  }

  public OfficeResponse accViolationStatus(@jakarta.annotation.Nullable Integer accViolationStatus) {
    
    this.accViolationStatus = accViolationStatus;
    return this;
  }

  /**
   * Get accViolationStatus
   * @return accViolationStatus
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACC_VIOLATION_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAccViolationStatus() {
    return accViolationStatus;
  }


  @JsonProperty(JSON_PROPERTY_ACC_VIOLATION_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccViolationStatus(@jakarta.annotation.Nullable Integer accViolationStatus) {
    this.accViolationStatus = accViolationStatus;
  }

  public OfficeResponse statusTxt(@jakarta.annotation.Nullable String statusTxt) {
    
    this.statusTxt = statusTxt;
    return this;
  }

  /**
   * Get statusTxt
   * @return statusTxt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS_TXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatusTxt() {
    return statusTxt;
  }


  @JsonProperty(JSON_PROPERTY_STATUS_TXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatusTxt(@jakarta.annotation.Nullable String statusTxt) {
    this.statusTxt = statusTxt;
  }

  public OfficeResponse emailNeedsUpdate(@jakarta.annotation.Nullable String emailNeedsUpdate) {
    
    this.emailNeedsUpdate = emailNeedsUpdate;
    return this;
  }

  /**
   * Get emailNeedsUpdate
   * @return emailNeedsUpdate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EMAIL_NEEDS_UPDATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEmailNeedsUpdate() {
    return emailNeedsUpdate;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL_NEEDS_UPDATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmailNeedsUpdate(@jakarta.annotation.Nullable String emailNeedsUpdate) {
    this.emailNeedsUpdate = emailNeedsUpdate;
  }

  public OfficeResponse emailConfirmed(@jakarta.annotation.Nullable Integer emailConfirmed) {
    
    this.emailConfirmed = emailConfirmed;
    return this;
  }

  /**
   * Get emailConfirmed
   * @return emailConfirmed
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EMAIL_CONFIRMED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getEmailConfirmed() {
    return emailConfirmed;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL_CONFIRMED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmailConfirmed(@jakarta.annotation.Nullable Integer emailConfirmed) {
    this.emailConfirmed = emailConfirmed;
  }

  public OfficeResponse noFreeSpots(@jakarta.annotation.Nullable Integer noFreeSpots) {
    
    this.noFreeSpots = noFreeSpots;
    return this;
  }

  /**
   * Get noFreeSpots
   * @return noFreeSpots
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NO_FREE_SPOTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNoFreeSpots() {
    return noFreeSpots;
  }


  @JsonProperty(JSON_PROPERTY_NO_FREE_SPOTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNoFreeSpots(@jakarta.annotation.Nullable Integer noFreeSpots) {
    this.noFreeSpots = noFreeSpots;
  }

  public OfficeResponse showTutorial(@jakarta.annotation.Nullable Boolean showTutorial) {
    
    this.showTutorial = showTutorial;
    return this;
  }

  /**
   * Get showTutorial
   * @return showTutorial
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHOW_TUTORIAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getShowTutorial() {
    return showTutorial;
  }


  @JsonProperty(JSON_PROPERTY_SHOW_TUTORIAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShowTutorial(@jakarta.annotation.Nullable Boolean showTutorial) {
    this.showTutorial = showTutorial;
  }

  public OfficeResponse needRefresh(@jakarta.annotation.Nullable Integer needRefresh) {
    
    this.needRefresh = needRefresh;
    return this;
  }

  /**
   * Get needRefresh
   * @return needRefresh
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NEED_REFRESH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNeedRefresh() {
    return needRefresh;
  }


  @JsonProperty(JSON_PROPERTY_NEED_REFRESH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNeedRefresh(@jakarta.annotation.Nullable Integer needRefresh) {
    this.needRefresh = needRefresh;
  }

  public OfficeResponse cash(@jakarta.annotation.Nullable Integer cash) {
    
    this.cash = cash;
    return this;
  }

  /**
   * Get cash
   * @return cash
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCash() {
    return cash;
  }


  @JsonProperty(JSON_PROPERTY_CASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCash(@jakarta.annotation.Nullable Integer cash) {
    this.cash = cash;
  }

  public OfficeResponse apiRequestsRemaining(@jakarta.annotation.Nullable Integer apiRequestsRemaining) {
    
    this.apiRequestsRemaining = apiRequestsRemaining;
    return this;
  }

  /**
   * Get apiRequestsRemaining
   * @return apiRequestsRemaining
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_API_REQUESTS_REMAINING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getApiRequestsRemaining() {
    return apiRequestsRemaining;
  }


  @JsonProperty(JSON_PROPERTY_API_REQUESTS_REMAINING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApiRequestsRemaining(@jakarta.annotation.Nullable Integer apiRequestsRemaining) {
    this.apiRequestsRemaining = apiRequestsRemaining;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OfficeResponse officeResponse = (OfficeResponse) o;
    return Objects.equals(this.loadingDataState, officeResponse.loadingDataState) &&
        Objects.equals(this.seasonNb, officeResponse.seasonNb) &&
        Objects.equals(this.raceNb, officeResponse.raceNb) &&
        Objects.equals(this.trackId, officeResponse.trackId) &&
        Objects.equals(this.endOfSeason, officeResponse.endOfSeason) &&
        Objects.equals(this.activateTeamStatus, officeResponse.activateTeamStatus) &&
        Objects.equals(this.accStatusId, officeResponse.accStatusId) &&
        Objects.equals(this.accStatus, officeResponse.accStatus) &&
        Objects.equals(this.nextSeasonResetDate, officeResponse.nextSeasonResetDate) &&
        Objects.equals(this.updateInProgress, officeResponse.updateInProgress) &&
        Objects.equals(this.progress, officeResponse.progress) &&
        Objects.equals(this.trackName, officeResponse.trackName) &&
        Objects.equals(this.trackNatCode, officeResponse.trackNatCode) &&
        Objects.equals(this.secondsLeft, officeResponse.secondsLeft) &&
        Objects.equals(this.secondsLeftQual, officeResponse.secondsLeftQual) &&
        Objects.equals(this.donePractice, officeResponse.donePractice) &&
        Objects.equals(this.doneQ1, officeResponse.doneQ1) &&
        Objects.equals(this.doneQ2, officeResponse.doneQ2) &&
        Objects.equals(this.doneRaceSetup, officeResponse.doneRaceSetup) &&
        Objects.equals(this.doneDriTrain, officeResponse.doneDriTrain) &&
        Objects.equals(this.doneStaffTrain, officeResponse.doneStaffTrain) &&
        Objects.equals(this.doneCarRepair, officeResponse.doneCarRepair) &&
        Objects.equals(this.doneFacilitiesUpdate, officeResponse.doneFacilitiesUpdate) &&
        Objects.equals(this.doneTesting, officeResponse.doneTesting) &&
        Objects.equals(this.testingStints, officeResponse.testingStints) &&
        Objects.equals(this.sponsorsAlert, officeResponse.sponsorsAlert) &&
        Objects.equals(this.sponsorsNoNeg, officeResponse.sponsorsNoNeg) &&
        Objects.equals(this.tyreSupplierId, officeResponse.tyreSupplierId) &&
        Objects.equals(this.driName, officeResponse.driName) &&
        Objects.equals(this.driOA, officeResponse.driOA) &&
        Objects.equals(this.driRacesLeft, officeResponse.driRacesLeft) &&
        Objects.equals(this.driSalary, officeResponse.driSalary) &&
        Objects.equals(this.driEnergy, officeResponse.driEnergy) &&
        Objects.equals(this.driId, officeResponse.driId) &&
        Objects.equals(this.tdName, officeResponse.tdName) &&
        Objects.equals(this.tdOA, officeResponse.tdOA) &&
        Objects.equals(this.tdRacesLeft, officeResponse.tdRacesLeft) &&
        Objects.equals(this.tdSalary, officeResponse.tdSalary) &&
        Objects.equals(this.tdId, officeResponse.tdId) &&
        Objects.equals(this.isCertified, officeResponse.isCertified) &&
        Objects.equals(this.champs, officeResponse.champs) &&
        Objects.equals(this.activationPixelFired, officeResponse.activationPixelFired) &&
        Objects.equals(this.pts, officeResponse.pts) &&
        Objects.equals(this.pos, officeResponse.pos) &&
        Objects.equals(this.avg, officeResponse.avg) &&
        Objects.equals(this.newQualifiersQ1, officeResponse.newQualifiersQ1) &&
        Objects.equals(this.newQualifiersQ2, officeResponse.newQualifiersQ2) &&
        Objects.equals(this.qual1Pos, officeResponse.qual1Pos) &&
        Objects.equals(this.qual1Diff, officeResponse.qual1Diff) &&
        Objects.equals(this.qual1LapTime, officeResponse.qual1LapTime) &&
        Objects.equals(this.qual2Pos, officeResponse.qual2Pos) &&
        Objects.equals(this.qual2Diff, officeResponse.qual2Diff) &&
        Objects.equals(this.qual2LapTime, officeResponse.qual2LapTime) &&
        Objects.equals(this.qualSGPos, officeResponse.qualSGPos) &&
        Objects.equals(this.qualSGDiff, officeResponse.qualSGDiff) &&
        Objects.equals(this.qualSGLapTime, officeResponse.qualSGLapTime) &&
        Objects.equals(this.teamForumUnreadTopics, officeResponse.teamForumUnreadTopics) &&
        Objects.equals(this.forumUnreadCount, officeResponse.forumUnreadCount) &&
        Objects.equals(this.unreadAnnouncements, officeResponse.unreadAnnouncements) &&
        Objects.equals(this.warnStatus, officeResponse.warnStatus) &&
        Objects.equals(this.accViolationStatus, officeResponse.accViolationStatus) &&
        Objects.equals(this.statusTxt, officeResponse.statusTxt) &&
        Objects.equals(this.emailNeedsUpdate, officeResponse.emailNeedsUpdate) &&
        Objects.equals(this.emailConfirmed, officeResponse.emailConfirmed) &&
        Objects.equals(this.noFreeSpots, officeResponse.noFreeSpots) &&
        Objects.equals(this.showTutorial, officeResponse.showTutorial) &&
        Objects.equals(this.needRefresh, officeResponse.needRefresh) &&
        Objects.equals(this.cash, officeResponse.cash) &&
        Objects.equals(this.apiRequestsRemaining, officeResponse.apiRequestsRemaining);
  }

  @Override
  public int hashCode() {
    return Objects.hash(loadingDataState, seasonNb, raceNb, trackId, endOfSeason, activateTeamStatus, accStatusId, accStatus, nextSeasonResetDate, updateInProgress, progress, trackName, trackNatCode, secondsLeft, secondsLeftQual, donePractice, doneQ1, doneQ2, doneRaceSetup, doneDriTrain, doneStaffTrain, doneCarRepair, doneFacilitiesUpdate, doneTesting, testingStints, sponsorsAlert, sponsorsNoNeg, tyreSupplierId, driName, driOA, driRacesLeft, driSalary, driEnergy, driId, tdName, tdOA, tdRacesLeft, tdSalary, tdId, isCertified, champs, activationPixelFired, pts, pos, avg, newQualifiersQ1, newQualifiersQ2, qual1Pos, qual1Diff, qual1LapTime, qual2Pos, qual2Diff, qual2LapTime, qualSGPos, qualSGDiff, qualSGLapTime, teamForumUnreadTopics, forumUnreadCount, unreadAnnouncements, warnStatus, accViolationStatus, statusTxt, emailNeedsUpdate, emailConfirmed, noFreeSpots, showTutorial, needRefresh, cash, apiRequestsRemaining);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OfficeResponse {\n");
    sb.append("    loadingDataState: ").append(toIndentedString(loadingDataState)).append("\n");
    sb.append("    seasonNb: ").append(toIndentedString(seasonNb)).append("\n");
    sb.append("    raceNb: ").append(toIndentedString(raceNb)).append("\n");
    sb.append("    trackId: ").append(toIndentedString(trackId)).append("\n");
    sb.append("    endOfSeason: ").append(toIndentedString(endOfSeason)).append("\n");
    sb.append("    activateTeamStatus: ").append(toIndentedString(activateTeamStatus)).append("\n");
    sb.append("    accStatusId: ").append(toIndentedString(accStatusId)).append("\n");
    sb.append("    accStatus: ").append(toIndentedString(accStatus)).append("\n");
    sb.append("    nextSeasonResetDate: ").append(toIndentedString(nextSeasonResetDate)).append("\n");
    sb.append("    updateInProgress: ").append(toIndentedString(updateInProgress)).append("\n");
    sb.append("    progress: ").append(toIndentedString(progress)).append("\n");
    sb.append("    trackName: ").append(toIndentedString(trackName)).append("\n");
    sb.append("    trackNatCode: ").append(toIndentedString(trackNatCode)).append("\n");
    sb.append("    secondsLeft: ").append(toIndentedString(secondsLeft)).append("\n");
    sb.append("    secondsLeftQual: ").append(toIndentedString(secondsLeftQual)).append("\n");
    sb.append("    donePractice: ").append(toIndentedString(donePractice)).append("\n");
    sb.append("    doneQ1: ").append(toIndentedString(doneQ1)).append("\n");
    sb.append("    doneQ2: ").append(toIndentedString(doneQ2)).append("\n");
    sb.append("    doneRaceSetup: ").append(toIndentedString(doneRaceSetup)).append("\n");
    sb.append("    doneDriTrain: ").append(toIndentedString(doneDriTrain)).append("\n");
    sb.append("    doneStaffTrain: ").append(toIndentedString(doneStaffTrain)).append("\n");
    sb.append("    doneCarRepair: ").append(toIndentedString(doneCarRepair)).append("\n");
    sb.append("    doneFacilitiesUpdate: ").append(toIndentedString(doneFacilitiesUpdate)).append("\n");
    sb.append("    doneTesting: ").append(toIndentedString(doneTesting)).append("\n");
    sb.append("    testingStints: ").append(toIndentedString(testingStints)).append("\n");
    sb.append("    sponsorsAlert: ").append(toIndentedString(sponsorsAlert)).append("\n");
    sb.append("    sponsorsNoNeg: ").append(toIndentedString(sponsorsNoNeg)).append("\n");
    sb.append("    tyreSupplierId: ").append(toIndentedString(tyreSupplierId)).append("\n");
    sb.append("    driName: ").append(toIndentedString(driName)).append("\n");
    sb.append("    driOA: ").append(toIndentedString(driOA)).append("\n");
    sb.append("    driRacesLeft: ").append(toIndentedString(driRacesLeft)).append("\n");
    sb.append("    driSalary: ").append(toIndentedString(driSalary)).append("\n");
    sb.append("    driEnergy: ").append(toIndentedString(driEnergy)).append("\n");
    sb.append("    driId: ").append(toIndentedString(driId)).append("\n");
    sb.append("    tdName: ").append(toIndentedString(tdName)).append("\n");
    sb.append("    tdOA: ").append(toIndentedString(tdOA)).append("\n");
    sb.append("    tdRacesLeft: ").append(toIndentedString(tdRacesLeft)).append("\n");
    sb.append("    tdSalary: ").append(toIndentedString(tdSalary)).append("\n");
    sb.append("    tdId: ").append(toIndentedString(tdId)).append("\n");
    sb.append("    isCertified: ").append(toIndentedString(isCertified)).append("\n");
    sb.append("    champs: ").append(toIndentedString(champs)).append("\n");
    sb.append("    activationPixelFired: ").append(toIndentedString(activationPixelFired)).append("\n");
    sb.append("    pts: ").append(toIndentedString(pts)).append("\n");
    sb.append("    pos: ").append(toIndentedString(pos)).append("\n");
    sb.append("    avg: ").append(toIndentedString(avg)).append("\n");
    sb.append("    newQualifiersQ1: ").append(toIndentedString(newQualifiersQ1)).append("\n");
    sb.append("    newQualifiersQ2: ").append(toIndentedString(newQualifiersQ2)).append("\n");
    sb.append("    qual1Pos: ").append(toIndentedString(qual1Pos)).append("\n");
    sb.append("    qual1Diff: ").append(toIndentedString(qual1Diff)).append("\n");
    sb.append("    qual1LapTime: ").append(toIndentedString(qual1LapTime)).append("\n");
    sb.append("    qual2Pos: ").append(toIndentedString(qual2Pos)).append("\n");
    sb.append("    qual2Diff: ").append(toIndentedString(qual2Diff)).append("\n");
    sb.append("    qual2LapTime: ").append(toIndentedString(qual2LapTime)).append("\n");
    sb.append("    qualSGPos: ").append(toIndentedString(qualSGPos)).append("\n");
    sb.append("    qualSGDiff: ").append(toIndentedString(qualSGDiff)).append("\n");
    sb.append("    qualSGLapTime: ").append(toIndentedString(qualSGLapTime)).append("\n");
    sb.append("    teamForumUnreadTopics: ").append(toIndentedString(teamForumUnreadTopics)).append("\n");
    sb.append("    forumUnreadCount: ").append(toIndentedString(forumUnreadCount)).append("\n");
    sb.append("    unreadAnnouncements: ").append(toIndentedString(unreadAnnouncements)).append("\n");
    sb.append("    warnStatus: ").append(toIndentedString(warnStatus)).append("\n");
    sb.append("    accViolationStatus: ").append(toIndentedString(accViolationStatus)).append("\n");
    sb.append("    statusTxt: ").append(toIndentedString(statusTxt)).append("\n");
    sb.append("    emailNeedsUpdate: ").append(toIndentedString(emailNeedsUpdate)).append("\n");
    sb.append("    emailConfirmed: ").append(toIndentedString(emailConfirmed)).append("\n");
    sb.append("    noFreeSpots: ").append(toIndentedString(noFreeSpots)).append("\n");
    sb.append("    showTutorial: ").append(toIndentedString(showTutorial)).append("\n");
    sb.append("    needRefresh: ").append(toIndentedString(needRefresh)).append("\n");
    sb.append("    cash: ").append(toIndentedString(cash)).append("\n");
    sb.append("    apiRequestsRemaining: ").append(toIndentedString(apiRequestsRemaining)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

