/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * QualyResultsResponseQ1DataInner
 */
@JsonPropertyOrder({
  QualyResultsResponseQ1DataInner.JSON_PROPERTY_NAME,
  QualyResultsResponseQ1DataInner.JSON_PROPERTY_POS,
  QualyResultsResponseQ1DataInner.JSON_PROPERTY_TYRE,
  QualyResultsResponseQ1DataInner.JSON_PROPERTY_NAT_CODE,
  QualyResultsResponseQ1DataInner.JSON_PROPERTY_I_D_M,
  QualyResultsResponseQ1DataInner.JSON_PROPERTY_CHAMPS,
  QualyResultsResponseQ1DataInner.JSON_PROPERTY_LAP_TIME,
  QualyResultsResponseQ1DataInner.JSON_PROPERTY_GAP
})
@JsonTypeName("QualyResultsResponse_q1Data_inner")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class QualyResultsResponseQ1DataInner {
  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_POS = "pos";
  @jakarta.annotation.Nullable
  private String pos;

  public static final String JSON_PROPERTY_TYRE = "tyre";
  @jakarta.annotation.Nullable
  private String tyre;

  public static final String JSON_PROPERTY_NAT_CODE = "natCode";
  @jakarta.annotation.Nullable
  private String natCode;

  public static final String JSON_PROPERTY_I_D_M = "IDM";
  @jakarta.annotation.Nullable
  private Integer IDM;

  public static final String JSON_PROPERTY_CHAMPS = "champs";
  @jakarta.annotation.Nullable
  private String champs;

  public static final String JSON_PROPERTY_LAP_TIME = "lapTime";
  @jakarta.annotation.Nullable
  private String lapTime;

  public static final String JSON_PROPERTY_GAP = "gap";
  @jakarta.annotation.Nullable
  private String gap;

  public QualyResultsResponseQ1DataInner() {
  }

  public QualyResultsResponseQ1DataInner name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  public QualyResultsResponseQ1DataInner pos(@jakarta.annotation.Nullable String pos) {
    
    this.pos = pos;
    return this;
  }

  /**
   * Get pos
   * @return pos
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPos() {
    return pos;
  }


  @JsonProperty(JSON_PROPERTY_POS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPos(@jakarta.annotation.Nullable String pos) {
    this.pos = pos;
  }

  public QualyResultsResponseQ1DataInner tyre(@jakarta.annotation.Nullable String tyre) {
    
    this.tyre = tyre;
    return this;
  }

  /**
   * Get tyre
   * @return tyre
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYRE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTyre() {
    return tyre;
  }


  @JsonProperty(JSON_PROPERTY_TYRE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTyre(@jakarta.annotation.Nullable String tyre) {
    this.tyre = tyre;
  }

  public QualyResultsResponseQ1DataInner natCode(@jakarta.annotation.Nullable String natCode) {
    
    this.natCode = natCode;
    return this;
  }

  /**
   * Get natCode
   * @return natCode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNatCode() {
    return natCode;
  }


  @JsonProperty(JSON_PROPERTY_NAT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNatCode(@jakarta.annotation.Nullable String natCode) {
    this.natCode = natCode;
  }

  public QualyResultsResponseQ1DataInner IDM(@jakarta.annotation.Nullable Integer IDM) {
    
    this.IDM = IDM;
    return this;
  }

  /**
   * Get IDM
   * @return IDM
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_I_D_M)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getIDM() {
    return IDM;
  }


  @JsonProperty(JSON_PROPERTY_I_D_M)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIDM(@jakarta.annotation.Nullable Integer IDM) {
    this.IDM = IDM;
  }

  public QualyResultsResponseQ1DataInner champs(@jakarta.annotation.Nullable String champs) {
    
    this.champs = champs;
    return this;
  }

  /**
   * Get champs
   * @return champs
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHAMPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getChamps() {
    return champs;
  }


  @JsonProperty(JSON_PROPERTY_CHAMPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChamps(@jakarta.annotation.Nullable String champs) {
    this.champs = champs;
  }

  public QualyResultsResponseQ1DataInner lapTime(@jakarta.annotation.Nullable String lapTime) {
    
    this.lapTime = lapTime;
    return this;
  }

  /**
   * Get lapTime
   * @return lapTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAP_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLapTime() {
    return lapTime;
  }


  @JsonProperty(JSON_PROPERTY_LAP_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLapTime(@jakarta.annotation.Nullable String lapTime) {
    this.lapTime = lapTime;
  }

  public QualyResultsResponseQ1DataInner gap(@jakarta.annotation.Nullable String gap) {
    
    this.gap = gap;
    return this;
  }

  /**
   * Get gap
   * @return gap
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GAP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGap() {
    return gap;
  }


  @JsonProperty(JSON_PROPERTY_GAP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGap(@jakarta.annotation.Nullable String gap) {
    this.gap = gap;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QualyResultsResponseQ1DataInner qualyResultsResponseQ1DataInner = (QualyResultsResponseQ1DataInner) o;
    return Objects.equals(this.name, qualyResultsResponseQ1DataInner.name) &&
        Objects.equals(this.pos, qualyResultsResponseQ1DataInner.pos) &&
        Objects.equals(this.tyre, qualyResultsResponseQ1DataInner.tyre) &&
        Objects.equals(this.natCode, qualyResultsResponseQ1DataInner.natCode) &&
        Objects.equals(this.IDM, qualyResultsResponseQ1DataInner.IDM) &&
        Objects.equals(this.champs, qualyResultsResponseQ1DataInner.champs) &&
        Objects.equals(this.lapTime, qualyResultsResponseQ1DataInner.lapTime) &&
        Objects.equals(this.gap, qualyResultsResponseQ1DataInner.gap);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, pos, tyre, natCode, IDM, champs, lapTime, gap);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QualyResultsResponseQ1DataInner {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    pos: ").append(toIndentedString(pos)).append("\n");
    sb.append("    tyre: ").append(toIndentedString(tyre)).append("\n");
    sb.append("    natCode: ").append(toIndentedString(natCode)).append("\n");
    sb.append("    IDM: ").append(toIndentedString(IDM)).append("\n");
    sb.append("    champs: ").append(toIndentedString(champs)).append("\n");
    sb.append("    lapTime: ").append(toIndentedString(lapTime)).append("\n");
    sb.append("    gap: ").append(toIndentedString(gap)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

