/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Qualy2StandingsResponseManagersQ2Inner
 */
@JsonPropertyOrder({
  Qualy2StandingsResponseManagersQ2Inner.JSON_PROPERTY_NAME,
  Qualy2StandingsResponseManagersQ2Inner.JSON_PROPERTY_POS,
  Qualy2StandingsResponseManagersQ2Inner.JSON_PROPERTY_TYRE,
  Qualy2StandingsResponseManagersQ2Inner.JSON_PROPERTY_NEW_QUALIFIER,
  Qualy2StandingsResponseManagersQ2Inner.JSON_PROPERTY_NAT_CODE,
  Qualy2StandingsResponseManagersQ2Inner.JSON_PROPERTY_I_D_M,
  Qualy2StandingsResponseManagersQ2Inner.JSON_PROPERTY_CHAMPS,
  Qualy2StandingsResponseManagersQ2Inner.JSON_PROPERTY_LAP_TIME,
  Qualy2StandingsResponseManagersQ2Inner.JSON_PROPERTY_SEPARATOR,
  Qualy2StandingsResponseManagersQ2Inner.JSON_PROPERTY_GAP
})
@JsonTypeName("Qualy2StandingsResponse_managersQ2_inner")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class Qualy2StandingsResponseManagersQ2Inner {
  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_POS = "pos";
  @jakarta.annotation.Nullable
  private String pos;

  public static final String JSON_PROPERTY_TYRE = "tyre";
  @jakarta.annotation.Nullable
  private String tyre;

  public static final String JSON_PROPERTY_NEW_QUALIFIER = "newQualifier";
  @jakarta.annotation.Nullable
  private Integer newQualifier;

  public static final String JSON_PROPERTY_NAT_CODE = "natCode";
  @jakarta.annotation.Nullable
  private String natCode;

  public static final String JSON_PROPERTY_I_D_M = "IDM";
  @jakarta.annotation.Nullable
  private Integer IDM;

  public static final String JSON_PROPERTY_CHAMPS = "champs";
  @jakarta.annotation.Nullable
  private String champs;

  public static final String JSON_PROPERTY_LAP_TIME = "lapTime";
  @jakarta.annotation.Nullable
  private String lapTime;

  public static final String JSON_PROPERTY_SEPARATOR = "separator";
  @jakarta.annotation.Nullable
  private Integer separator;

  public static final String JSON_PROPERTY_GAP = "gap";
  @jakarta.annotation.Nullable
  private String gap;

  public Qualy2StandingsResponseManagersQ2Inner() {
  }

  public Qualy2StandingsResponseManagersQ2Inner name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  public Qualy2StandingsResponseManagersQ2Inner pos(@jakarta.annotation.Nullable String pos) {
    
    this.pos = pos;
    return this;
  }

  /**
   * Get pos
   * @return pos
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPos() {
    return pos;
  }


  @JsonProperty(JSON_PROPERTY_POS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPos(@jakarta.annotation.Nullable String pos) {
    this.pos = pos;
  }

  public Qualy2StandingsResponseManagersQ2Inner tyre(@jakarta.annotation.Nullable String tyre) {
    
    this.tyre = tyre;
    return this;
  }

  /**
   * Get tyre
   * @return tyre
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYRE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTyre() {
    return tyre;
  }


  @JsonProperty(JSON_PROPERTY_TYRE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTyre(@jakarta.annotation.Nullable String tyre) {
    this.tyre = tyre;
  }

  public Qualy2StandingsResponseManagersQ2Inner newQualifier(@jakarta.annotation.Nullable Integer newQualifier) {
    
    this.newQualifier = newQualifier;
    return this;
  }

  /**
   * Get newQualifier
   * @return newQualifier
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NEW_QUALIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNewQualifier() {
    return newQualifier;
  }


  @JsonProperty(JSON_PROPERTY_NEW_QUALIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNewQualifier(@jakarta.annotation.Nullable Integer newQualifier) {
    this.newQualifier = newQualifier;
  }

  public Qualy2StandingsResponseManagersQ2Inner natCode(@jakarta.annotation.Nullable String natCode) {
    
    this.natCode = natCode;
    return this;
  }

  /**
   * Get natCode
   * @return natCode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNatCode() {
    return natCode;
  }


  @JsonProperty(JSON_PROPERTY_NAT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNatCode(@jakarta.annotation.Nullable String natCode) {
    this.natCode = natCode;
  }

  public Qualy2StandingsResponseManagersQ2Inner IDM(@jakarta.annotation.Nullable Integer IDM) {
    
    this.IDM = IDM;
    return this;
  }

  /**
   * Get IDM
   * @return IDM
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_I_D_M)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getIDM() {
    return IDM;
  }


  @JsonProperty(JSON_PROPERTY_I_D_M)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIDM(@jakarta.annotation.Nullable Integer IDM) {
    this.IDM = IDM;
  }

  public Qualy2StandingsResponseManagersQ2Inner champs(@jakarta.annotation.Nullable String champs) {
    
    this.champs = champs;
    return this;
  }

  /**
   * Get champs
   * @return champs
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHAMPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getChamps() {
    return champs;
  }


  @JsonProperty(JSON_PROPERTY_CHAMPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChamps(@jakarta.annotation.Nullable String champs) {
    this.champs = champs;
  }

  public Qualy2StandingsResponseManagersQ2Inner lapTime(@jakarta.annotation.Nullable String lapTime) {
    
    this.lapTime = lapTime;
    return this;
  }

  /**
   * Get lapTime
   * @return lapTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAP_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLapTime() {
    return lapTime;
  }


  @JsonProperty(JSON_PROPERTY_LAP_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLapTime(@jakarta.annotation.Nullable String lapTime) {
    this.lapTime = lapTime;
  }

  public Qualy2StandingsResponseManagersQ2Inner separator(@jakarta.annotation.Nullable Integer separator) {
    
    this.separator = separator;
    return this;
  }

  /**
   * Get separator
   * @return separator
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEPARATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSeparator() {
    return separator;
  }


  @JsonProperty(JSON_PROPERTY_SEPARATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeparator(@jakarta.annotation.Nullable Integer separator) {
    this.separator = separator;
  }

  public Qualy2StandingsResponseManagersQ2Inner gap(@jakarta.annotation.Nullable String gap) {
    
    this.gap = gap;
    return this;
  }

  /**
   * Get gap
   * @return gap
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GAP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGap() {
    return gap;
  }


  @JsonProperty(JSON_PROPERTY_GAP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGap(@jakarta.annotation.Nullable String gap) {
    this.gap = gap;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Qualy2StandingsResponseManagersQ2Inner qualy2StandingsResponseManagersQ2Inner = (Qualy2StandingsResponseManagersQ2Inner) o;
    return Objects.equals(this.name, qualy2StandingsResponseManagersQ2Inner.name) &&
        Objects.equals(this.pos, qualy2StandingsResponseManagersQ2Inner.pos) &&
        Objects.equals(this.tyre, qualy2StandingsResponseManagersQ2Inner.tyre) &&
        Objects.equals(this.newQualifier, qualy2StandingsResponseManagersQ2Inner.newQualifier) &&
        Objects.equals(this.natCode, qualy2StandingsResponseManagersQ2Inner.natCode) &&
        Objects.equals(this.IDM, qualy2StandingsResponseManagersQ2Inner.IDM) &&
        Objects.equals(this.champs, qualy2StandingsResponseManagersQ2Inner.champs) &&
        Objects.equals(this.lapTime, qualy2StandingsResponseManagersQ2Inner.lapTime) &&
        Objects.equals(this.separator, qualy2StandingsResponseManagersQ2Inner.separator) &&
        Objects.equals(this.gap, qualy2StandingsResponseManagersQ2Inner.gap);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, pos, tyre, newQualifier, natCode, IDM, champs, lapTime, separator, gap);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Qualy2StandingsResponseManagersQ2Inner {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    pos: ").append(toIndentedString(pos)).append("\n");
    sb.append("    tyre: ").append(toIndentedString(tyre)).append("\n");
    sb.append("    newQualifier: ").append(toIndentedString(newQualifier)).append("\n");
    sb.append("    natCode: ").append(toIndentedString(natCode)).append("\n");
    sb.append("    IDM: ").append(toIndentedString(IDM)).append("\n");
    sb.append("    champs: ").append(toIndentedString(champs)).append("\n");
    sb.append("    lapTime: ").append(toIndentedString(lapTime)).append("\n");
    sb.append("    separator: ").append(toIndentedString(separator)).append("\n");
    sb.append("    gap: ").append(toIndentedString(gap)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

