/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RaceAnalysisResponsePitsInner
 */
@JsonPropertyOrder({
  RaceAnalysisResponsePitsInner.JSON_PROPERTY_IDX,
  RaceAnalysisResponsePitsInner.JSON_PROPERTY_LAP,
  RaceAnalysisResponsePitsInner.JSON_PROPERTY_REASON,
  RaceAnalysisResponsePitsInner.JSON_PROPERTY_TYRE_COND,
  RaceAnalysisResponsePitsInner.JSON_PROPERTY_FUEL_LEFT,
  RaceAnalysisResponsePitsInner.JSON_PROPERTY_REFILLED_TO,
  RaceAnalysisResponsePitsInner.JSON_PROPERTY_PIT_TIME
})
@JsonTypeName("RaceAnalysisResponse_pits_inner")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class RaceAnalysisResponsePitsInner {
  public static final String JSON_PROPERTY_IDX = "idx";
  @jakarta.annotation.Nullable
  private Integer idx;

  public static final String JSON_PROPERTY_LAP = "lap";
  @jakarta.annotation.Nullable
  private Integer lap;

  public static final String JSON_PROPERTY_REASON = "reason";
  @jakarta.annotation.Nullable
  private String reason;

  public static final String JSON_PROPERTY_TYRE_COND = "tyreCond";
  @jakarta.annotation.Nullable
  private Integer tyreCond;

  public static final String JSON_PROPERTY_FUEL_LEFT = "fuelLeft";
  @jakarta.annotation.Nullable
  private Integer fuelLeft;

  public static final String JSON_PROPERTY_REFILLED_TO = "refilledTo";
  @jakarta.annotation.Nullable
  private Integer refilledTo;

  public static final String JSON_PROPERTY_PIT_TIME = "pitTime";
  @jakarta.annotation.Nullable
  private String pitTime;

  public RaceAnalysisResponsePitsInner() {
  }

  public RaceAnalysisResponsePitsInner idx(@jakarta.annotation.Nullable Integer idx) {
    
    this.idx = idx;
    return this;
  }

  /**
   * Get idx
   * @return idx
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IDX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getIdx() {
    return idx;
  }


  @JsonProperty(JSON_PROPERTY_IDX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdx(@jakarta.annotation.Nullable Integer idx) {
    this.idx = idx;
  }

  public RaceAnalysisResponsePitsInner lap(@jakarta.annotation.Nullable Integer lap) {
    
    this.lap = lap;
    return this;
  }

  /**
   * Get lap
   * @return lap
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getLap() {
    return lap;
  }


  @JsonProperty(JSON_PROPERTY_LAP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLap(@jakarta.annotation.Nullable Integer lap) {
    this.lap = lap;
  }

  public RaceAnalysisResponsePitsInner reason(@jakarta.annotation.Nullable String reason) {
    
    this.reason = reason;
    return this;
  }

  /**
   * Get reason
   * @return reason
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReason() {
    return reason;
  }


  @JsonProperty(JSON_PROPERTY_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReason(@jakarta.annotation.Nullable String reason) {
    this.reason = reason;
  }

  public RaceAnalysisResponsePitsInner tyreCond(@jakarta.annotation.Nullable Integer tyreCond) {
    
    this.tyreCond = tyreCond;
    return this;
  }

  /**
   * Get tyreCond
   * @return tyreCond
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYRE_COND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTyreCond() {
    return tyreCond;
  }


  @JsonProperty(JSON_PROPERTY_TYRE_COND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTyreCond(@jakarta.annotation.Nullable Integer tyreCond) {
    this.tyreCond = tyreCond;
  }

  public RaceAnalysisResponsePitsInner fuelLeft(@jakarta.annotation.Nullable Integer fuelLeft) {
    
    this.fuelLeft = fuelLeft;
    return this;
  }

  /**
   * Get fuelLeft
   * @return fuelLeft
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FUEL_LEFT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFuelLeft() {
    return fuelLeft;
  }


  @JsonProperty(JSON_PROPERTY_FUEL_LEFT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFuelLeft(@jakarta.annotation.Nullable Integer fuelLeft) {
    this.fuelLeft = fuelLeft;
  }

  public RaceAnalysisResponsePitsInner refilledTo(@jakarta.annotation.Nullable Integer refilledTo) {
    
    this.refilledTo = refilledTo;
    return this;
  }

  /**
   * Get refilledTo
   * @return refilledTo
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REFILLED_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRefilledTo() {
    return refilledTo;
  }


  @JsonProperty(JSON_PROPERTY_REFILLED_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRefilledTo(@jakarta.annotation.Nullable Integer refilledTo) {
    this.refilledTo = refilledTo;
  }

  public RaceAnalysisResponsePitsInner pitTime(@jakarta.annotation.Nullable String pitTime) {
    
    this.pitTime = pitTime;
    return this;
  }

  /**
   * Get pitTime
   * @return pitTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PIT_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPitTime() {
    return pitTime;
  }


  @JsonProperty(JSON_PROPERTY_PIT_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPitTime(@jakarta.annotation.Nullable String pitTime) {
    this.pitTime = pitTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RaceAnalysisResponsePitsInner raceAnalysisResponsePitsInner = (RaceAnalysisResponsePitsInner) o;
    return Objects.equals(this.idx, raceAnalysisResponsePitsInner.idx) &&
        Objects.equals(this.lap, raceAnalysisResponsePitsInner.lap) &&
        Objects.equals(this.reason, raceAnalysisResponsePitsInner.reason) &&
        Objects.equals(this.tyreCond, raceAnalysisResponsePitsInner.tyreCond) &&
        Objects.equals(this.fuelLeft, raceAnalysisResponsePitsInner.fuelLeft) &&
        Objects.equals(this.refilledTo, raceAnalysisResponsePitsInner.refilledTo) &&
        Objects.equals(this.pitTime, raceAnalysisResponsePitsInner.pitTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idx, lap, reason, tyreCond, fuelLeft, refilledTo, pitTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RaceAnalysisResponsePitsInner {\n");
    sb.append("    idx: ").append(toIndentedString(idx)).append("\n");
    sb.append("    lap: ").append(toIndentedString(lap)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    tyreCond: ").append(toIndentedString(tyreCond)).append("\n");
    sb.append("    fuelLeft: ").append(toIndentedString(fuelLeft)).append("\n");
    sb.append("    refilledTo: ").append(toIndentedString(refilledTo)).append("\n");
    sb.append("    pitTime: ").append(toIndentedString(pitTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

