/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.jlobato.gpro.model.RaceAnalysisNAResponseRacesToSelectInner;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RaceAnalysisNAResponse
 */
@JsonPropertyOrder({
  RaceAnalysisNAResponse.JSON_PROPERTY_LOADING_DATA_STATE,
  RaceAnalysisNAResponse.JSON_PROPERTY_IGNORE_REF_CHECK,
  RaceAnalysisNAResponse.JSON_PROPERTY_SEGMENT_SELECTED,
  RaceAnalysisNAResponse.JSON_PROPERTY_UNLOCKED,
  RaceAnalysisNAResponse.JSON_PROPERTY_CREDITS,
  RaceAnalysisNAResponse.JSON_PROPERTY_SEL_SEASON_NB,
  RaceAnalysisNAResponse.JSON_PROPERTY_SEL_RACE_NB,
  RaceAnalysisNAResponse.JSON_PROPERTY_GROUP,
  RaceAnalysisNAResponse.JSON_PROPERTY_TRACK_NAME,
  RaceAnalysisNAResponse.JSON_PROPERTY_TRACK_NAT_CODE,
  RaceAnalysisNAResponse.JSON_PROPERTY_TRACK_COUNTRY,
  RaceAnalysisNAResponse.JSON_PROPERTY_TRACK_ID,
  RaceAnalysisNAResponse.JSON_PROPERTY_RACES_TO_SELECT,
  RaceAnalysisNAResponse.JSON_PROPERTY_LAPS,
  RaceAnalysisNAResponse.JSON_PROPERTY_API_REQUESTS_REMAINING
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class RaceAnalysisNAResponse {
  public static final String JSON_PROPERTY_LOADING_DATA_STATE = "loadingDataState";
  @jakarta.annotation.Nullable
  private Integer loadingDataState;

  public static final String JSON_PROPERTY_IGNORE_REF_CHECK = "ignoreRefCheck";
  @jakarta.annotation.Nullable
  private Integer ignoreRefCheck;

  public static final String JSON_PROPERTY_SEGMENT_SELECTED = "segmentSelected";
  @jakarta.annotation.Nullable
  private String segmentSelected;

  public static final String JSON_PROPERTY_UNLOCKED = "unlocked";
  @jakarta.annotation.Nullable
  private String unlocked;

  public static final String JSON_PROPERTY_CREDITS = "credits";
  @jakarta.annotation.Nullable
  private String credits;

  public static final String JSON_PROPERTY_SEL_SEASON_NB = "selSeasonNb";
  @jakarta.annotation.Nullable
  private String selSeasonNb;

  public static final String JSON_PROPERTY_SEL_RACE_NB = "selRaceNb";
  @jakarta.annotation.Nullable
  private String selRaceNb;

  public static final String JSON_PROPERTY_GROUP = "group";
  @jakarta.annotation.Nullable
  private String group;

  public static final String JSON_PROPERTY_TRACK_NAME = "trackName";
  @jakarta.annotation.Nullable
  private String trackName;

  public static final String JSON_PROPERTY_TRACK_NAT_CODE = "trackNatCode";
  @jakarta.annotation.Nullable
  private String trackNatCode;

  public static final String JSON_PROPERTY_TRACK_COUNTRY = "trackCountry";
  @jakarta.annotation.Nullable
  private String trackCountry;

  public static final String JSON_PROPERTY_TRACK_ID = "trackId";
  @jakarta.annotation.Nullable
  private String trackId;

  public static final String JSON_PROPERTY_RACES_TO_SELECT = "racesToSelect";
  @jakarta.annotation.Nullable
  private List<RaceAnalysisNAResponseRacesToSelectInner> racesToSelect = new ArrayList<>();

  public static final String JSON_PROPERTY_LAPS = "laps";
  @jakarta.annotation.Nullable
  private List<Object> laps = new ArrayList<>();

  public static final String JSON_PROPERTY_API_REQUESTS_REMAINING = "apiRequestsRemaining";
  @jakarta.annotation.Nullable
  private Integer apiRequestsRemaining;

  public RaceAnalysisNAResponse() {
  }

  public RaceAnalysisNAResponse loadingDataState(@jakarta.annotation.Nullable Integer loadingDataState) {
    
    this.loadingDataState = loadingDataState;
    return this;
  }

  /**
   * Get loadingDataState
   * @return loadingDataState
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOADING_DATA_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getLoadingDataState() {
    return loadingDataState;
  }


  @JsonProperty(JSON_PROPERTY_LOADING_DATA_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLoadingDataState(@jakarta.annotation.Nullable Integer loadingDataState) {
    this.loadingDataState = loadingDataState;
  }

  public RaceAnalysisNAResponse ignoreRefCheck(@jakarta.annotation.Nullable Integer ignoreRefCheck) {
    
    this.ignoreRefCheck = ignoreRefCheck;
    return this;
  }

  /**
   * Get ignoreRefCheck
   * @return ignoreRefCheck
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IGNORE_REF_CHECK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getIgnoreRefCheck() {
    return ignoreRefCheck;
  }


  @JsonProperty(JSON_PROPERTY_IGNORE_REF_CHECK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIgnoreRefCheck(@jakarta.annotation.Nullable Integer ignoreRefCheck) {
    this.ignoreRefCheck = ignoreRefCheck;
  }

  public RaceAnalysisNAResponse segmentSelected(@jakarta.annotation.Nullable String segmentSelected) {
    
    this.segmentSelected = segmentSelected;
    return this;
  }

  /**
   * Get segmentSelected
   * @return segmentSelected
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEGMENT_SELECTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSegmentSelected() {
    return segmentSelected;
  }


  @JsonProperty(JSON_PROPERTY_SEGMENT_SELECTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSegmentSelected(@jakarta.annotation.Nullable String segmentSelected) {
    this.segmentSelected = segmentSelected;
  }

  public RaceAnalysisNAResponse unlocked(@jakarta.annotation.Nullable String unlocked) {
    
    this.unlocked = unlocked;
    return this;
  }

  /**
   * Get unlocked
   * @return unlocked
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UNLOCKED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUnlocked() {
    return unlocked;
  }


  @JsonProperty(JSON_PROPERTY_UNLOCKED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnlocked(@jakarta.annotation.Nullable String unlocked) {
    this.unlocked = unlocked;
  }

  public RaceAnalysisNAResponse credits(@jakarta.annotation.Nullable String credits) {
    
    this.credits = credits;
    return this;
  }

  /**
   * Get credits
   * @return credits
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREDITS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCredits() {
    return credits;
  }


  @JsonProperty(JSON_PROPERTY_CREDITS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCredits(@jakarta.annotation.Nullable String credits) {
    this.credits = credits;
  }

  public RaceAnalysisNAResponse selSeasonNb(@jakarta.annotation.Nullable String selSeasonNb) {
    
    this.selSeasonNb = selSeasonNb;
    return this;
  }

  /**
   * Get selSeasonNb
   * @return selSeasonNb
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEL_SEASON_NB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSelSeasonNb() {
    return selSeasonNb;
  }


  @JsonProperty(JSON_PROPERTY_SEL_SEASON_NB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSelSeasonNb(@jakarta.annotation.Nullable String selSeasonNb) {
    this.selSeasonNb = selSeasonNb;
  }

  public RaceAnalysisNAResponse selRaceNb(@jakarta.annotation.Nullable String selRaceNb) {
    
    this.selRaceNb = selRaceNb;
    return this;
  }

  /**
   * Get selRaceNb
   * @return selRaceNb
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEL_RACE_NB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSelRaceNb() {
    return selRaceNb;
  }


  @JsonProperty(JSON_PROPERTY_SEL_RACE_NB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSelRaceNb(@jakarta.annotation.Nullable String selRaceNb) {
    this.selRaceNb = selRaceNb;
  }

  public RaceAnalysisNAResponse group(@jakarta.annotation.Nullable String group) {
    
    this.group = group;
    return this;
  }

  /**
   * Get group
   * @return group
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GROUP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGroup() {
    return group;
  }


  @JsonProperty(JSON_PROPERTY_GROUP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGroup(@jakarta.annotation.Nullable String group) {
    this.group = group;
  }

  public RaceAnalysisNAResponse trackName(@jakarta.annotation.Nullable String trackName) {
    
    this.trackName = trackName;
    return this;
  }

  /**
   * Get trackName
   * @return trackName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRACK_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTrackName() {
    return trackName;
  }


  @JsonProperty(JSON_PROPERTY_TRACK_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrackName(@jakarta.annotation.Nullable String trackName) {
    this.trackName = trackName;
  }

  public RaceAnalysisNAResponse trackNatCode(@jakarta.annotation.Nullable String trackNatCode) {
    
    this.trackNatCode = trackNatCode;
    return this;
  }

  /**
   * Get trackNatCode
   * @return trackNatCode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRACK_NAT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTrackNatCode() {
    return trackNatCode;
  }


  @JsonProperty(JSON_PROPERTY_TRACK_NAT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrackNatCode(@jakarta.annotation.Nullable String trackNatCode) {
    this.trackNatCode = trackNatCode;
  }

  public RaceAnalysisNAResponse trackCountry(@jakarta.annotation.Nullable String trackCountry) {
    
    this.trackCountry = trackCountry;
    return this;
  }

  /**
   * Get trackCountry
   * @return trackCountry
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRACK_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTrackCountry() {
    return trackCountry;
  }


  @JsonProperty(JSON_PROPERTY_TRACK_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrackCountry(@jakarta.annotation.Nullable String trackCountry) {
    this.trackCountry = trackCountry;
  }

  public RaceAnalysisNAResponse trackId(@jakarta.annotation.Nullable String trackId) {
    
    this.trackId = trackId;
    return this;
  }

  /**
   * Get trackId
   * @return trackId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRACK_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTrackId() {
    return trackId;
  }


  @JsonProperty(JSON_PROPERTY_TRACK_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrackId(@jakarta.annotation.Nullable String trackId) {
    this.trackId = trackId;
  }

  public RaceAnalysisNAResponse racesToSelect(@jakarta.annotation.Nullable List<RaceAnalysisNAResponseRacesToSelectInner> racesToSelect) {
    
    this.racesToSelect = racesToSelect;
    return this;
  }

  public RaceAnalysisNAResponse addRacesToSelectItem(RaceAnalysisNAResponseRacesToSelectInner racesToSelectItem) {
    if (this.racesToSelect == null) {
      this.racesToSelect = new ArrayList<>();
    }
    this.racesToSelect.add(racesToSelectItem);
    return this;
  }

  /**
   * Get racesToSelect
   * @return racesToSelect
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RACES_TO_SELECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<RaceAnalysisNAResponseRacesToSelectInner> getRacesToSelect() {
    return racesToSelect;
  }


  @JsonProperty(JSON_PROPERTY_RACES_TO_SELECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRacesToSelect(@jakarta.annotation.Nullable List<RaceAnalysisNAResponseRacesToSelectInner> racesToSelect) {
    this.racesToSelect = racesToSelect;
  }

  public RaceAnalysisNAResponse laps(@jakarta.annotation.Nullable List<Object> laps) {
    
    this.laps = laps;
    return this;
  }

  public RaceAnalysisNAResponse addLapsItem(Object lapsItem) {
    if (this.laps == null) {
      this.laps = new ArrayList<>();
    }
    this.laps.add(lapsItem);
    return this;
  }

  /**
   * Get laps
   * @return laps
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Object> getLaps() {
    return laps;
  }


  @JsonProperty(JSON_PROPERTY_LAPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLaps(@jakarta.annotation.Nullable List<Object> laps) {
    this.laps = laps;
  }

  public RaceAnalysisNAResponse apiRequestsRemaining(@jakarta.annotation.Nullable Integer apiRequestsRemaining) {
    
    this.apiRequestsRemaining = apiRequestsRemaining;
    return this;
  }

  /**
   * Get apiRequestsRemaining
   * @return apiRequestsRemaining
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_API_REQUESTS_REMAINING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getApiRequestsRemaining() {
    return apiRequestsRemaining;
  }


  @JsonProperty(JSON_PROPERTY_API_REQUESTS_REMAINING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApiRequestsRemaining(@jakarta.annotation.Nullable Integer apiRequestsRemaining) {
    this.apiRequestsRemaining = apiRequestsRemaining;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RaceAnalysisNAResponse raceAnalysisNAResponse = (RaceAnalysisNAResponse) o;
    return Objects.equals(this.loadingDataState, raceAnalysisNAResponse.loadingDataState) &&
        Objects.equals(this.ignoreRefCheck, raceAnalysisNAResponse.ignoreRefCheck) &&
        Objects.equals(this.segmentSelected, raceAnalysisNAResponse.segmentSelected) &&
        Objects.equals(this.unlocked, raceAnalysisNAResponse.unlocked) &&
        Objects.equals(this.credits, raceAnalysisNAResponse.credits) &&
        Objects.equals(this.selSeasonNb, raceAnalysisNAResponse.selSeasonNb) &&
        Objects.equals(this.selRaceNb, raceAnalysisNAResponse.selRaceNb) &&
        Objects.equals(this.group, raceAnalysisNAResponse.group) &&
        Objects.equals(this.trackName, raceAnalysisNAResponse.trackName) &&
        Objects.equals(this.trackNatCode, raceAnalysisNAResponse.trackNatCode) &&
        Objects.equals(this.trackCountry, raceAnalysisNAResponse.trackCountry) &&
        Objects.equals(this.trackId, raceAnalysisNAResponse.trackId) &&
        Objects.equals(this.racesToSelect, raceAnalysisNAResponse.racesToSelect) &&
        Objects.equals(this.laps, raceAnalysisNAResponse.laps) &&
        Objects.equals(this.apiRequestsRemaining, raceAnalysisNAResponse.apiRequestsRemaining);
  }

  @Override
  public int hashCode() {
    return Objects.hash(loadingDataState, ignoreRefCheck, segmentSelected, unlocked, credits, selSeasonNb, selRaceNb, group, trackName, trackNatCode, trackCountry, trackId, racesToSelect, laps, apiRequestsRemaining);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RaceAnalysisNAResponse {\n");
    sb.append("    loadingDataState: ").append(toIndentedString(loadingDataState)).append("\n");
    sb.append("    ignoreRefCheck: ").append(toIndentedString(ignoreRefCheck)).append("\n");
    sb.append("    segmentSelected: ").append(toIndentedString(segmentSelected)).append("\n");
    sb.append("    unlocked: ").append(toIndentedString(unlocked)).append("\n");
    sb.append("    credits: ").append(toIndentedString(credits)).append("\n");
    sb.append("    selSeasonNb: ").append(toIndentedString(selSeasonNb)).append("\n");
    sb.append("    selRaceNb: ").append(toIndentedString(selRaceNb)).append("\n");
    sb.append("    group: ").append(toIndentedString(group)).append("\n");
    sb.append("    trackName: ").append(toIndentedString(trackName)).append("\n");
    sb.append("    trackNatCode: ").append(toIndentedString(trackNatCode)).append("\n");
    sb.append("    trackCountry: ").append(toIndentedString(trackCountry)).append("\n");
    sb.append("    trackId: ").append(toIndentedString(trackId)).append("\n");
    sb.append("    racesToSelect: ").append(toIndentedString(racesToSelect)).append("\n");
    sb.append("    laps: ").append(toIndentedString(laps)).append("\n");
    sb.append("    apiRequestsRemaining: ").append(toIndentedString(apiRequestsRemaining)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

