/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RaceReplayResponseRacesToSelectInner
 */
@JsonPropertyOrder({
  RaceReplayResponseRacesToSelectInner.JSON_PROPERTY_VALUE,
  RaceReplayResponseRacesToSelectInner.JSON_PROPERTY_SEASON,
  RaceReplayResponseRacesToSelectInner.JSON_PROPERTY_RACE,
  RaceReplayResponseRacesToSelectInner.JSON_PROPERTY_TRACK_NAME,
  RaceReplayResponseRacesToSelectInner.JSON_PROPERTY_NAT_CODE
})
@JsonTypeName("RaceReplayResponse_racesToSelect_inner")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class RaceReplayResponseRacesToSelectInner {
  public static final String JSON_PROPERTY_VALUE = "value";
  @jakarta.annotation.Nullable
  private String value;

  public static final String JSON_PROPERTY_SEASON = "season";
  @jakarta.annotation.Nullable
  private Integer season;

  public static final String JSON_PROPERTY_RACE = "race";
  @jakarta.annotation.Nullable
  private Integer race;

  public static final String JSON_PROPERTY_TRACK_NAME = "trackName";
  @jakarta.annotation.Nullable
  private String trackName;

  public static final String JSON_PROPERTY_NAT_CODE = "natCode";
  @jakarta.annotation.Nullable
  private String natCode;

  public RaceReplayResponseRacesToSelectInner() {
  }

  public RaceReplayResponseRacesToSelectInner value(@jakarta.annotation.Nullable String value) {
    
    this.value = value;
    return this;
  }

  /**
   * Get value
   * @return value
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getValue() {
    return value;
  }


  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValue(@jakarta.annotation.Nullable String value) {
    this.value = value;
  }

  public RaceReplayResponseRacesToSelectInner season(@jakarta.annotation.Nullable Integer season) {
    
    this.season = season;
    return this;
  }

  /**
   * Get season
   * @return season
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSeason() {
    return season;
  }


  @JsonProperty(JSON_PROPERTY_SEASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeason(@jakarta.annotation.Nullable Integer season) {
    this.season = season;
  }

  public RaceReplayResponseRacesToSelectInner race(@jakarta.annotation.Nullable Integer race) {
    
    this.race = race;
    return this;
  }

  /**
   * Get race
   * @return race
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RACE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRace() {
    return race;
  }


  @JsonProperty(JSON_PROPERTY_RACE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRace(@jakarta.annotation.Nullable Integer race) {
    this.race = race;
  }

  public RaceReplayResponseRacesToSelectInner trackName(@jakarta.annotation.Nullable String trackName) {
    
    this.trackName = trackName;
    return this;
  }

  /**
   * Get trackName
   * @return trackName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRACK_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTrackName() {
    return trackName;
  }


  @JsonProperty(JSON_PROPERTY_TRACK_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrackName(@jakarta.annotation.Nullable String trackName) {
    this.trackName = trackName;
  }

  public RaceReplayResponseRacesToSelectInner natCode(@jakarta.annotation.Nullable String natCode) {
    
    this.natCode = natCode;
    return this;
  }

  /**
   * Get natCode
   * @return natCode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNatCode() {
    return natCode;
  }


  @JsonProperty(JSON_PROPERTY_NAT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNatCode(@jakarta.annotation.Nullable String natCode) {
    this.natCode = natCode;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RaceReplayResponseRacesToSelectInner raceReplayResponseRacesToSelectInner = (RaceReplayResponseRacesToSelectInner) o;
    return Objects.equals(this.value, raceReplayResponseRacesToSelectInner.value) &&
        Objects.equals(this.season, raceReplayResponseRacesToSelectInner.season) &&
        Objects.equals(this.race, raceReplayResponseRacesToSelectInner.race) &&
        Objects.equals(this.trackName, raceReplayResponseRacesToSelectInner.trackName) &&
        Objects.equals(this.natCode, raceReplayResponseRacesToSelectInner.natCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value, season, race, trackName, natCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RaceReplayResponseRacesToSelectInner {\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    season: ").append(toIndentedString(season)).append("\n");
    sb.append("    race: ").append(toIndentedString(race)).append("\n");
    sb.append("    trackName: ").append(toIndentedString(trackName)).append("\n");
    sb.append("    natCode: ").append(toIndentedString(natCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

