/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.jlobato.gpro.model.CalendarResponseGroupsInner;
import org.jlobato.gpro.model.DriverProfileResponseFaceJSONHairBg;
import org.jlobato.gpro.model.DriverProfileResponseFavTrack1;
import org.jlobato.gpro.model.RaceReplayResponseRacesToSelectInner;
import org.jlobato.gpro.model.RaceSummaryResponseManagersInner;
import org.jlobato.gpro.model.RaceSummaryResponseNationsInner;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RaceSummaryResponse
 */
@JsonPropertyOrder({
  RaceSummaryResponse.JSON_PROPERTY_LOADING_DATA_STATE,
  RaceSummaryResponse.JSON_PROPERTY_SEGMENT_SELECTED,
  RaceSummaryResponse.JSON_PROPERTY_LOADING_DATA,
  RaceSummaryResponse.JSON_PROPERTY_GROUP,
  RaceSummaryResponse.JSON_PROPERTY_PROPERTY_CLASS,
  RaceSummaryResponse.JSON_PROPERTY_NATION,
  RaceSummaryResponse.JSON_PROPERTY_TEAM,
  RaceSummaryResponse.JSON_PROPERTY_SEASON,
  RaceSummaryResponse.JSON_PROPERTY_RACE,
  RaceSummaryResponse.JSON_PROPERTY_TRACK_NAME,
  RaceSummaryResponse.JSON_PROPERTY_TRACK_ID,
  RaceSummaryResponse.JSON_PROPERTY_SEASONS,
  RaceSummaryResponse.JSON_PROPERTY_RACES,
  RaceSummaryResponse.JSON_PROPERTY_GROUPS,
  RaceSummaryResponse.JSON_PROPERTY_NATIONS,
  RaceSummaryResponse.JSON_PROPERTY_TEAMS,
  RaceSummaryResponse.JSON_PROPERTY_MANAGERS,
  RaceSummaryResponse.JSON_PROPERTY_RACES_TO_SELECT,
  RaceSummaryResponse.JSON_PROPERTY_CUTOFF_TIME112PERCENT,
  RaceSummaryResponse.JSON_PROPERTY_API_REQUESTS_REMAINING
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class RaceSummaryResponse {
  public static final String JSON_PROPERTY_LOADING_DATA_STATE = "loadingDataState";
  @jakarta.annotation.Nullable
  private String loadingDataState;

  public static final String JSON_PROPERTY_SEGMENT_SELECTED = "segmentSelected";
  @jakarta.annotation.Nullable
  private String segmentSelected;

  public static final String JSON_PROPERTY_LOADING_DATA = "loadingData";
  @jakarta.annotation.Nullable
  private Integer loadingData;

  public static final String JSON_PROPERTY_GROUP = "group";
  @jakarta.annotation.Nullable
  private String group;

  public static final String JSON_PROPERTY_PROPERTY_CLASS = "class";
  @jakarta.annotation.Nullable
  private String propertyClass;

  public static final String JSON_PROPERTY_NATION = "nation";
  @jakarta.annotation.Nullable
  private String nation;

  public static final String JSON_PROPERTY_TEAM = "team";
  @jakarta.annotation.Nullable
  private Integer team;

  public static final String JSON_PROPERTY_SEASON = "season";
  @jakarta.annotation.Nullable
  private String season;

  public static final String JSON_PROPERTY_RACE = "race";
  @jakarta.annotation.Nullable
  private String race;

  public static final String JSON_PROPERTY_TRACK_NAME = "trackName";
  @jakarta.annotation.Nullable
  private String trackName;

  public static final String JSON_PROPERTY_TRACK_ID = "trackId";
  @jakarta.annotation.Nullable
  private String trackId;

  public static final String JSON_PROPERTY_SEASONS = "seasons";
  @jakarta.annotation.Nullable
  private List<DriverProfileResponseFaceJSONHairBg> seasons = new ArrayList<>();

  public static final String JSON_PROPERTY_RACES = "races";
  @jakarta.annotation.Nullable
  private List<DriverProfileResponseFaceJSONHairBg> races = new ArrayList<>();

  public static final String JSON_PROPERTY_GROUPS = "groups";
  @jakarta.annotation.Nullable
  private List<CalendarResponseGroupsInner> groups = new ArrayList<>();

  public static final String JSON_PROPERTY_NATIONS = "nations";
  @jakarta.annotation.Nullable
  private List<RaceSummaryResponseNationsInner> nations = new ArrayList<>();

  public static final String JSON_PROPERTY_TEAMS = "teams";
  @jakarta.annotation.Nullable
  private List<DriverProfileResponseFavTrack1> teams = new ArrayList<>();

  public static final String JSON_PROPERTY_MANAGERS = "managers";
  @jakarta.annotation.Nullable
  private List<RaceSummaryResponseManagersInner> managers = new ArrayList<>();

  public static final String JSON_PROPERTY_RACES_TO_SELECT = "racesToSelect";
  @jakarta.annotation.Nullable
  private List<RaceReplayResponseRacesToSelectInner> racesToSelect = new ArrayList<>();

  public static final String JSON_PROPERTY_CUTOFF_TIME112PERCENT = "cutoffTime112percent";
  @jakarta.annotation.Nullable
  private String cutoffTime112percent;

  public static final String JSON_PROPERTY_API_REQUESTS_REMAINING = "apiRequestsRemaining";
  @jakarta.annotation.Nullable
  private Integer apiRequestsRemaining;

  public RaceSummaryResponse() {
  }

  public RaceSummaryResponse loadingDataState(@jakarta.annotation.Nullable String loadingDataState) {
    
    this.loadingDataState = loadingDataState;
    return this;
  }

  /**
   * Get loadingDataState
   * @return loadingDataState
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOADING_DATA_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLoadingDataState() {
    return loadingDataState;
  }


  @JsonProperty(JSON_PROPERTY_LOADING_DATA_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLoadingDataState(@jakarta.annotation.Nullable String loadingDataState) {
    this.loadingDataState = loadingDataState;
  }

  public RaceSummaryResponse segmentSelected(@jakarta.annotation.Nullable String segmentSelected) {
    
    this.segmentSelected = segmentSelected;
    return this;
  }

  /**
   * Get segmentSelected
   * @return segmentSelected
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEGMENT_SELECTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSegmentSelected() {
    return segmentSelected;
  }


  @JsonProperty(JSON_PROPERTY_SEGMENT_SELECTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSegmentSelected(@jakarta.annotation.Nullable String segmentSelected) {
    this.segmentSelected = segmentSelected;
  }

  public RaceSummaryResponse loadingData(@jakarta.annotation.Nullable Integer loadingData) {
    
    this.loadingData = loadingData;
    return this;
  }

  /**
   * Get loadingData
   * @return loadingData
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOADING_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getLoadingData() {
    return loadingData;
  }


  @JsonProperty(JSON_PROPERTY_LOADING_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLoadingData(@jakarta.annotation.Nullable Integer loadingData) {
    this.loadingData = loadingData;
  }

  public RaceSummaryResponse group(@jakarta.annotation.Nullable String group) {
    
    this.group = group;
    return this;
  }

  /**
   * Get group
   * @return group
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GROUP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGroup() {
    return group;
  }


  @JsonProperty(JSON_PROPERTY_GROUP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGroup(@jakarta.annotation.Nullable String group) {
    this.group = group;
  }

  public RaceSummaryResponse propertyClass(@jakarta.annotation.Nullable String propertyClass) {
    
    this.propertyClass = propertyClass;
    return this;
  }

  /**
   * Get propertyClass
   * @return propertyClass
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROPERTY_CLASS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPropertyClass() {
    return propertyClass;
  }


  @JsonProperty(JSON_PROPERTY_PROPERTY_CLASS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPropertyClass(@jakarta.annotation.Nullable String propertyClass) {
    this.propertyClass = propertyClass;
  }

  public RaceSummaryResponse nation(@jakarta.annotation.Nullable String nation) {
    
    this.nation = nation;
    return this;
  }

  /**
   * Get nation
   * @return nation
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNation() {
    return nation;
  }


  @JsonProperty(JSON_PROPERTY_NATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNation(@jakarta.annotation.Nullable String nation) {
    this.nation = nation;
  }

  public RaceSummaryResponse team(@jakarta.annotation.Nullable Integer team) {
    
    this.team = team;
    return this;
  }

  /**
   * Get team
   * @return team
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEAM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTeam() {
    return team;
  }


  @JsonProperty(JSON_PROPERTY_TEAM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTeam(@jakarta.annotation.Nullable Integer team) {
    this.team = team;
  }

  public RaceSummaryResponse season(@jakarta.annotation.Nullable String season) {
    
    this.season = season;
    return this;
  }

  /**
   * Get season
   * @return season
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSeason() {
    return season;
  }


  @JsonProperty(JSON_PROPERTY_SEASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeason(@jakarta.annotation.Nullable String season) {
    this.season = season;
  }

  public RaceSummaryResponse race(@jakarta.annotation.Nullable String race) {
    
    this.race = race;
    return this;
  }

  /**
   * Get race
   * @return race
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RACE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRace() {
    return race;
  }


  @JsonProperty(JSON_PROPERTY_RACE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRace(@jakarta.annotation.Nullable String race) {
    this.race = race;
  }

  public RaceSummaryResponse trackName(@jakarta.annotation.Nullable String trackName) {
    
    this.trackName = trackName;
    return this;
  }

  /**
   * Get trackName
   * @return trackName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRACK_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTrackName() {
    return trackName;
  }


  @JsonProperty(JSON_PROPERTY_TRACK_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrackName(@jakarta.annotation.Nullable String trackName) {
    this.trackName = trackName;
  }

  public RaceSummaryResponse trackId(@jakarta.annotation.Nullable String trackId) {
    
    this.trackId = trackId;
    return this;
  }

  /**
   * Get trackId
   * @return trackId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRACK_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTrackId() {
    return trackId;
  }


  @JsonProperty(JSON_PROPERTY_TRACK_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrackId(@jakarta.annotation.Nullable String trackId) {
    this.trackId = trackId;
  }

  public RaceSummaryResponse seasons(@jakarta.annotation.Nullable List<DriverProfileResponseFaceJSONHairBg> seasons) {
    
    this.seasons = seasons;
    return this;
  }

  public RaceSummaryResponse addSeasonsItem(DriverProfileResponseFaceJSONHairBg seasonsItem) {
    if (this.seasons == null) {
      this.seasons = new ArrayList<>();
    }
    this.seasons.add(seasonsItem);
    return this;
  }

  /**
   * Get seasons
   * @return seasons
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEASONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DriverProfileResponseFaceJSONHairBg> getSeasons() {
    return seasons;
  }


  @JsonProperty(JSON_PROPERTY_SEASONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeasons(@jakarta.annotation.Nullable List<DriverProfileResponseFaceJSONHairBg> seasons) {
    this.seasons = seasons;
  }

  public RaceSummaryResponse races(@jakarta.annotation.Nullable List<DriverProfileResponseFaceJSONHairBg> races) {
    
    this.races = races;
    return this;
  }

  public RaceSummaryResponse addRacesItem(DriverProfileResponseFaceJSONHairBg racesItem) {
    if (this.races == null) {
      this.races = new ArrayList<>();
    }
    this.races.add(racesItem);
    return this;
  }

  /**
   * Get races
   * @return races
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RACES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DriverProfileResponseFaceJSONHairBg> getRaces() {
    return races;
  }


  @JsonProperty(JSON_PROPERTY_RACES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRaces(@jakarta.annotation.Nullable List<DriverProfileResponseFaceJSONHairBg> races) {
    this.races = races;
  }

  public RaceSummaryResponse groups(@jakarta.annotation.Nullable List<CalendarResponseGroupsInner> groups) {
    
    this.groups = groups;
    return this;
  }

  public RaceSummaryResponse addGroupsItem(CalendarResponseGroupsInner groupsItem) {
    if (this.groups == null) {
      this.groups = new ArrayList<>();
    }
    this.groups.add(groupsItem);
    return this;
  }

  /**
   * Get groups
   * @return groups
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GROUPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CalendarResponseGroupsInner> getGroups() {
    return groups;
  }


  @JsonProperty(JSON_PROPERTY_GROUPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGroups(@jakarta.annotation.Nullable List<CalendarResponseGroupsInner> groups) {
    this.groups = groups;
  }

  public RaceSummaryResponse nations(@jakarta.annotation.Nullable List<RaceSummaryResponseNationsInner> nations) {
    
    this.nations = nations;
    return this;
  }

  public RaceSummaryResponse addNationsItem(RaceSummaryResponseNationsInner nationsItem) {
    if (this.nations == null) {
      this.nations = new ArrayList<>();
    }
    this.nations.add(nationsItem);
    return this;
  }

  /**
   * Get nations
   * @return nations
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<RaceSummaryResponseNationsInner> getNations() {
    return nations;
  }


  @JsonProperty(JSON_PROPERTY_NATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNations(@jakarta.annotation.Nullable List<RaceSummaryResponseNationsInner> nations) {
    this.nations = nations;
  }

  public RaceSummaryResponse teams(@jakarta.annotation.Nullable List<DriverProfileResponseFavTrack1> teams) {
    
    this.teams = teams;
    return this;
  }

  public RaceSummaryResponse addTeamsItem(DriverProfileResponseFavTrack1 teamsItem) {
    if (this.teams == null) {
      this.teams = new ArrayList<>();
    }
    this.teams.add(teamsItem);
    return this;
  }

  /**
   * Get teams
   * @return teams
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEAMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DriverProfileResponseFavTrack1> getTeams() {
    return teams;
  }


  @JsonProperty(JSON_PROPERTY_TEAMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTeams(@jakarta.annotation.Nullable List<DriverProfileResponseFavTrack1> teams) {
    this.teams = teams;
  }

  public RaceSummaryResponse managers(@jakarta.annotation.Nullable List<RaceSummaryResponseManagersInner> managers) {
    
    this.managers = managers;
    return this;
  }

  public RaceSummaryResponse addManagersItem(RaceSummaryResponseManagersInner managersItem) {
    if (this.managers == null) {
      this.managers = new ArrayList<>();
    }
    this.managers.add(managersItem);
    return this;
  }

  /**
   * Get managers
   * @return managers
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MANAGERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<RaceSummaryResponseManagersInner> getManagers() {
    return managers;
  }


  @JsonProperty(JSON_PROPERTY_MANAGERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManagers(@jakarta.annotation.Nullable List<RaceSummaryResponseManagersInner> managers) {
    this.managers = managers;
  }

  public RaceSummaryResponse racesToSelect(@jakarta.annotation.Nullable List<RaceReplayResponseRacesToSelectInner> racesToSelect) {
    
    this.racesToSelect = racesToSelect;
    return this;
  }

  public RaceSummaryResponse addRacesToSelectItem(RaceReplayResponseRacesToSelectInner racesToSelectItem) {
    if (this.racesToSelect == null) {
      this.racesToSelect = new ArrayList<>();
    }
    this.racesToSelect.add(racesToSelectItem);
    return this;
  }

  /**
   * Get racesToSelect
   * @return racesToSelect
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RACES_TO_SELECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<RaceReplayResponseRacesToSelectInner> getRacesToSelect() {
    return racesToSelect;
  }


  @JsonProperty(JSON_PROPERTY_RACES_TO_SELECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRacesToSelect(@jakarta.annotation.Nullable List<RaceReplayResponseRacesToSelectInner> racesToSelect) {
    this.racesToSelect = racesToSelect;
  }

  public RaceSummaryResponse cutoffTime112percent(@jakarta.annotation.Nullable String cutoffTime112percent) {
    
    this.cutoffTime112percent = cutoffTime112percent;
    return this;
  }

  /**
   * Get cutoffTime112percent
   * @return cutoffTime112percent
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CUTOFF_TIME112PERCENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCutoffTime112percent() {
    return cutoffTime112percent;
  }


  @JsonProperty(JSON_PROPERTY_CUTOFF_TIME112PERCENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCutoffTime112percent(@jakarta.annotation.Nullable String cutoffTime112percent) {
    this.cutoffTime112percent = cutoffTime112percent;
  }

  public RaceSummaryResponse apiRequestsRemaining(@jakarta.annotation.Nullable Integer apiRequestsRemaining) {
    
    this.apiRequestsRemaining = apiRequestsRemaining;
    return this;
  }

  /**
   * Get apiRequestsRemaining
   * @return apiRequestsRemaining
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_API_REQUESTS_REMAINING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getApiRequestsRemaining() {
    return apiRequestsRemaining;
  }


  @JsonProperty(JSON_PROPERTY_API_REQUESTS_REMAINING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApiRequestsRemaining(@jakarta.annotation.Nullable Integer apiRequestsRemaining) {
    this.apiRequestsRemaining = apiRequestsRemaining;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RaceSummaryResponse raceSummaryResponse = (RaceSummaryResponse) o;
    return Objects.equals(this.loadingDataState, raceSummaryResponse.loadingDataState) &&
        Objects.equals(this.segmentSelected, raceSummaryResponse.segmentSelected) &&
        Objects.equals(this.loadingData, raceSummaryResponse.loadingData) &&
        Objects.equals(this.group, raceSummaryResponse.group) &&
        Objects.equals(this.propertyClass, raceSummaryResponse.propertyClass) &&
        Objects.equals(this.nation, raceSummaryResponse.nation) &&
        Objects.equals(this.team, raceSummaryResponse.team) &&
        Objects.equals(this.season, raceSummaryResponse.season) &&
        Objects.equals(this.race, raceSummaryResponse.race) &&
        Objects.equals(this.trackName, raceSummaryResponse.trackName) &&
        Objects.equals(this.trackId, raceSummaryResponse.trackId) &&
        Objects.equals(this.seasons, raceSummaryResponse.seasons) &&
        Objects.equals(this.races, raceSummaryResponse.races) &&
        Objects.equals(this.groups, raceSummaryResponse.groups) &&
        Objects.equals(this.nations, raceSummaryResponse.nations) &&
        Objects.equals(this.teams, raceSummaryResponse.teams) &&
        Objects.equals(this.managers, raceSummaryResponse.managers) &&
        Objects.equals(this.racesToSelect, raceSummaryResponse.racesToSelect) &&
        Objects.equals(this.cutoffTime112percent, raceSummaryResponse.cutoffTime112percent) &&
        Objects.equals(this.apiRequestsRemaining, raceSummaryResponse.apiRequestsRemaining);
  }

  @Override
  public int hashCode() {
    return Objects.hash(loadingDataState, segmentSelected, loadingData, group, propertyClass, nation, team, season, race, trackName, trackId, seasons, races, groups, nations, teams, managers, racesToSelect, cutoffTime112percent, apiRequestsRemaining);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RaceSummaryResponse {\n");
    sb.append("    loadingDataState: ").append(toIndentedString(loadingDataState)).append("\n");
    sb.append("    segmentSelected: ").append(toIndentedString(segmentSelected)).append("\n");
    sb.append("    loadingData: ").append(toIndentedString(loadingData)).append("\n");
    sb.append("    group: ").append(toIndentedString(group)).append("\n");
    sb.append("    propertyClass: ").append(toIndentedString(propertyClass)).append("\n");
    sb.append("    nation: ").append(toIndentedString(nation)).append("\n");
    sb.append("    team: ").append(toIndentedString(team)).append("\n");
    sb.append("    season: ").append(toIndentedString(season)).append("\n");
    sb.append("    race: ").append(toIndentedString(race)).append("\n");
    sb.append("    trackName: ").append(toIndentedString(trackName)).append("\n");
    sb.append("    trackId: ").append(toIndentedString(trackId)).append("\n");
    sb.append("    seasons: ").append(toIndentedString(seasons)).append("\n");
    sb.append("    races: ").append(toIndentedString(races)).append("\n");
    sb.append("    groups: ").append(toIndentedString(groups)).append("\n");
    sb.append("    nations: ").append(toIndentedString(nations)).append("\n");
    sb.append("    teams: ").append(toIndentedString(teams)).append("\n");
    sb.append("    managers: ").append(toIndentedString(managers)).append("\n");
    sb.append("    racesToSelect: ").append(toIndentedString(racesToSelect)).append("\n");
    sb.append("    cutoffTime112percent: ").append(toIndentedString(cutoffTime112percent)).append("\n");
    sb.append("    apiRequestsRemaining: ").append(toIndentedString(apiRequestsRemaining)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

