/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * StandingsResponseDataGraphChartBackgroundColorLinearGradient
 */
@JsonPropertyOrder({
  StandingsResponseDataGraphChartBackgroundColorLinearGradient.JSON_PROPERTY_X1,
  StandingsResponseDataGraphChartBackgroundColorLinearGradient.JSON_PROPERTY_Y1,
  StandingsResponseDataGraphChartBackgroundColorLinearGradient.JSON_PROPERTY_X2,
  StandingsResponseDataGraphChartBackgroundColorLinearGradient.JSON_PROPERTY_Y2
})
@JsonTypeName("StandingsResponse_dataGraph_chart_backgroundColor_linearGradient")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class StandingsResponseDataGraphChartBackgroundColorLinearGradient {
  public static final String JSON_PROPERTY_X1 = "x1";
  @jakarta.annotation.Nullable
  private Integer x1;

  public static final String JSON_PROPERTY_Y1 = "y1";
  @jakarta.annotation.Nullable
  private Integer y1;

  public static final String JSON_PROPERTY_X2 = "x2";
  @jakarta.annotation.Nullable
  private Integer x2;

  public static final String JSON_PROPERTY_Y2 = "y2";
  @jakarta.annotation.Nullable
  private Integer y2;

  public StandingsResponseDataGraphChartBackgroundColorLinearGradient() {
  }

  public StandingsResponseDataGraphChartBackgroundColorLinearGradient x1(@jakarta.annotation.Nullable Integer x1) {
    
    this.x1 = x1;
    return this;
  }

  /**
   * Get x1
   * @return x1
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_X1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getX1() {
    return x1;
  }


  @JsonProperty(JSON_PROPERTY_X1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setX1(@jakarta.annotation.Nullable Integer x1) {
    this.x1 = x1;
  }

  public StandingsResponseDataGraphChartBackgroundColorLinearGradient y1(@jakarta.annotation.Nullable Integer y1) {
    
    this.y1 = y1;
    return this;
  }

  /**
   * Get y1
   * @return y1
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_Y1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getY1() {
    return y1;
  }


  @JsonProperty(JSON_PROPERTY_Y1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setY1(@jakarta.annotation.Nullable Integer y1) {
    this.y1 = y1;
  }

  public StandingsResponseDataGraphChartBackgroundColorLinearGradient x2(@jakarta.annotation.Nullable Integer x2) {
    
    this.x2 = x2;
    return this;
  }

  /**
   * Get x2
   * @return x2
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_X2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getX2() {
    return x2;
  }


  @JsonProperty(JSON_PROPERTY_X2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setX2(@jakarta.annotation.Nullable Integer x2) {
    this.x2 = x2;
  }

  public StandingsResponseDataGraphChartBackgroundColorLinearGradient y2(@jakarta.annotation.Nullable Integer y2) {
    
    this.y2 = y2;
    return this;
  }

  /**
   * Get y2
   * @return y2
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_Y2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getY2() {
    return y2;
  }


  @JsonProperty(JSON_PROPERTY_Y2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setY2(@jakarta.annotation.Nullable Integer y2) {
    this.y2 = y2;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StandingsResponseDataGraphChartBackgroundColorLinearGradient standingsResponseDataGraphChartBackgroundColorLinearGradient = (StandingsResponseDataGraphChartBackgroundColorLinearGradient) o;
    return Objects.equals(this.x1, standingsResponseDataGraphChartBackgroundColorLinearGradient.x1) &&
        Objects.equals(this.y1, standingsResponseDataGraphChartBackgroundColorLinearGradient.y1) &&
        Objects.equals(this.x2, standingsResponseDataGraphChartBackgroundColorLinearGradient.x2) &&
        Objects.equals(this.y2, standingsResponseDataGraphChartBackgroundColorLinearGradient.y2);
  }

  @Override
  public int hashCode() {
    return Objects.hash(x1, y1, x2, y2);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StandingsResponseDataGraphChartBackgroundColorLinearGradient {\n");
    sb.append("    x1: ").append(toIndentedString(x1)).append("\n");
    sb.append("    y1: ").append(toIndentedString(y1)).append("\n");
    sb.append("    x2: ").append(toIndentedString(x2)).append("\n");
    sb.append("    y2: ").append(toIndentedString(y2)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

