/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * StandingsResponseDataGraphRangeSelectorButtonThemeStyle
 */
@JsonPropertyOrder({
  StandingsResponseDataGraphRangeSelectorButtonThemeStyle.JSON_PROPERTY_COLOR,
  StandingsResponseDataGraphRangeSelectorButtonThemeStyle.JSON_PROPERTY_FONT_WEIGHT
})
@JsonTypeName("StandingsResponse_dataGraph_rangeSelector_buttonTheme_style")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class StandingsResponseDataGraphRangeSelectorButtonThemeStyle {
  public static final String JSON_PROPERTY_COLOR = "color";
  @jakarta.annotation.Nullable
  private String color;

  public static final String JSON_PROPERTY_FONT_WEIGHT = "fontWeight";
  @jakarta.annotation.Nullable
  private String fontWeight;

  public StandingsResponseDataGraphRangeSelectorButtonThemeStyle() {
  }

  public StandingsResponseDataGraphRangeSelectorButtonThemeStyle color(@jakarta.annotation.Nullable String color) {
    
    this.color = color;
    return this;
  }

  /**
   * Get color
   * @return color
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getColor() {
    return color;
  }


  @JsonProperty(JSON_PROPERTY_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setColor(@jakarta.annotation.Nullable String color) {
    this.color = color;
  }

  public StandingsResponseDataGraphRangeSelectorButtonThemeStyle fontWeight(@jakarta.annotation.Nullable String fontWeight) {
    
    this.fontWeight = fontWeight;
    return this;
  }

  /**
   * Get fontWeight
   * @return fontWeight
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FONT_WEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFontWeight() {
    return fontWeight;
  }


  @JsonProperty(JSON_PROPERTY_FONT_WEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFontWeight(@jakarta.annotation.Nullable String fontWeight) {
    this.fontWeight = fontWeight;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StandingsResponseDataGraphRangeSelectorButtonThemeStyle standingsResponseDataGraphRangeSelectorButtonThemeStyle = (StandingsResponseDataGraphRangeSelectorButtonThemeStyle) o;
    return Objects.equals(this.color, standingsResponseDataGraphRangeSelectorButtonThemeStyle.color) &&
        Objects.equals(this.fontWeight, standingsResponseDataGraphRangeSelectorButtonThemeStyle.fontWeight);
  }

  @Override
  public int hashCode() {
    return Objects.hash(color, fontWeight);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StandingsResponseDataGraphRangeSelectorButtonThemeStyle {\n");
    sb.append("    color: ").append(toIndentedString(color)).append("\n");
    sb.append("    fontWeight: ").append(toIndentedString(fontWeight)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

