/*
 * GPRO App Public API
 * # Introduction  GPRO App API is a development meant to serve GPRO Applications Frontend. This document curates a selection of endpoints from the GPRO App API to show GPRO managers how to call these selected endpoints to optimize their data collection, providing response schemas and extensive examples. 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.jlobato.gpro.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.jlobato.gpro.model.TyreSuppliersResponseClickedSupplier;
import org.jlobato.gpro.model.TyreSuppliersResponseSeasonsInner;
import org.jlobato.gpro.model.TyreSuppliersResponseShowSignConfirm;
import org.jlobato.gpro.model.TyreSuppliersResponseSuppliersInner;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * TyreSuppliersResponse
 */
@JsonPropertyOrder({
  TyreSuppliersResponse.JSON_PROPERTY_LOADING_DATA_STATE,
  TyreSuppliersResponse.JSON_PROPERTY_CUR_SUPPLIER_ID,
  TyreSuppliersResponse.JSON_PROPERTY_CAN_SIGN_CONTRACT,
  TyreSuppliersResponse.JSON_PROPERTY_SEASON_NB,
  TyreSuppliersResponse.JSON_PROPERTY_SELECTED_SEASON,
  TyreSuppliersResponse.JSON_PROPERTY_CLICKED_SUPPLIER,
  TyreSuppliersResponse.JSON_PROPERTY_SHOW_SIGN_CONFIRM,
  TyreSuppliersResponse.JSON_PROPERTY_SEASONS,
  TyreSuppliersResponse.JSON_PROPERTY_SUPPLIERS,
  TyreSuppliersResponse.JSON_PROPERTY_API_REQUESTS_REMAINING
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class TyreSuppliersResponse {
  public static final String JSON_PROPERTY_LOADING_DATA_STATE = "loadingDataState";
  @jakarta.annotation.Nullable
  private Integer loadingDataState;

  public static final String JSON_PROPERTY_CUR_SUPPLIER_ID = "curSupplierId";
  @jakarta.annotation.Nullable
  private Integer curSupplierId;

  public static final String JSON_PROPERTY_CAN_SIGN_CONTRACT = "canSignContract";
  @jakarta.annotation.Nullable
  private Integer canSignContract;

  public static final String JSON_PROPERTY_SEASON_NB = "seasonNb";
  @jakarta.annotation.Nullable
  private Integer seasonNb;

  public static final String JSON_PROPERTY_SELECTED_SEASON = "selectedSeason";
  @jakarta.annotation.Nullable
  private Integer selectedSeason;

  public static final String JSON_PROPERTY_CLICKED_SUPPLIER = "clickedSupplier";
  @jakarta.annotation.Nullable
  private TyreSuppliersResponseClickedSupplier clickedSupplier;

  public static final String JSON_PROPERTY_SHOW_SIGN_CONFIRM = "showSignConfirm";
  @jakarta.annotation.Nullable
  private TyreSuppliersResponseShowSignConfirm showSignConfirm;

  public static final String JSON_PROPERTY_SEASONS = "seasons";
  @jakarta.annotation.Nullable
  private List<TyreSuppliersResponseSeasonsInner> seasons = new ArrayList<>();

  public static final String JSON_PROPERTY_SUPPLIERS = "suppliers";
  @jakarta.annotation.Nullable
  private List<TyreSuppliersResponseSuppliersInner> suppliers = new ArrayList<>();

  public static final String JSON_PROPERTY_API_REQUESTS_REMAINING = "apiRequestsRemaining";
  @jakarta.annotation.Nullable
  private Integer apiRequestsRemaining;

  public TyreSuppliersResponse() {
  }

  public TyreSuppliersResponse loadingDataState(@jakarta.annotation.Nullable Integer loadingDataState) {
    
    this.loadingDataState = loadingDataState;
    return this;
  }

  /**
   * Get loadingDataState
   * @return loadingDataState
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOADING_DATA_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getLoadingDataState() {
    return loadingDataState;
  }


  @JsonProperty(JSON_PROPERTY_LOADING_DATA_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLoadingDataState(@jakarta.annotation.Nullable Integer loadingDataState) {
    this.loadingDataState = loadingDataState;
  }

  public TyreSuppliersResponse curSupplierId(@jakarta.annotation.Nullable Integer curSupplierId) {
    
    this.curSupplierId = curSupplierId;
    return this;
  }

  /**
   * Get curSupplierId
   * @return curSupplierId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CUR_SUPPLIER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCurSupplierId() {
    return curSupplierId;
  }


  @JsonProperty(JSON_PROPERTY_CUR_SUPPLIER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurSupplierId(@jakarta.annotation.Nullable Integer curSupplierId) {
    this.curSupplierId = curSupplierId;
  }

  public TyreSuppliersResponse canSignContract(@jakarta.annotation.Nullable Integer canSignContract) {
    
    this.canSignContract = canSignContract;
    return this;
  }

  /**
   * Get canSignContract
   * @return canSignContract
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CAN_SIGN_CONTRACT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCanSignContract() {
    return canSignContract;
  }


  @JsonProperty(JSON_PROPERTY_CAN_SIGN_CONTRACT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCanSignContract(@jakarta.annotation.Nullable Integer canSignContract) {
    this.canSignContract = canSignContract;
  }

  public TyreSuppliersResponse seasonNb(@jakarta.annotation.Nullable Integer seasonNb) {
    
    this.seasonNb = seasonNb;
    return this;
  }

  /**
   * Get seasonNb
   * @return seasonNb
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEASON_NB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSeasonNb() {
    return seasonNb;
  }


  @JsonProperty(JSON_PROPERTY_SEASON_NB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeasonNb(@jakarta.annotation.Nullable Integer seasonNb) {
    this.seasonNb = seasonNb;
  }

  public TyreSuppliersResponse selectedSeason(@jakarta.annotation.Nullable Integer selectedSeason) {
    
    this.selectedSeason = selectedSeason;
    return this;
  }

  /**
   * Get selectedSeason
   * @return selectedSeason
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SELECTED_SEASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSelectedSeason() {
    return selectedSeason;
  }


  @JsonProperty(JSON_PROPERTY_SELECTED_SEASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSelectedSeason(@jakarta.annotation.Nullable Integer selectedSeason) {
    this.selectedSeason = selectedSeason;
  }

  public TyreSuppliersResponse clickedSupplier(@jakarta.annotation.Nullable TyreSuppliersResponseClickedSupplier clickedSupplier) {
    
    this.clickedSupplier = clickedSupplier;
    return this;
  }

  /**
   * Get clickedSupplier
   * @return clickedSupplier
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CLICKED_SUPPLIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TyreSuppliersResponseClickedSupplier getClickedSupplier() {
    return clickedSupplier;
  }


  @JsonProperty(JSON_PROPERTY_CLICKED_SUPPLIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClickedSupplier(@jakarta.annotation.Nullable TyreSuppliersResponseClickedSupplier clickedSupplier) {
    this.clickedSupplier = clickedSupplier;
  }

  public TyreSuppliersResponse showSignConfirm(@jakarta.annotation.Nullable TyreSuppliersResponseShowSignConfirm showSignConfirm) {
    
    this.showSignConfirm = showSignConfirm;
    return this;
  }

  /**
   * Get showSignConfirm
   * @return showSignConfirm
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHOW_SIGN_CONFIRM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TyreSuppliersResponseShowSignConfirm getShowSignConfirm() {
    return showSignConfirm;
  }


  @JsonProperty(JSON_PROPERTY_SHOW_SIGN_CONFIRM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShowSignConfirm(@jakarta.annotation.Nullable TyreSuppliersResponseShowSignConfirm showSignConfirm) {
    this.showSignConfirm = showSignConfirm;
  }

  public TyreSuppliersResponse seasons(@jakarta.annotation.Nullable List<TyreSuppliersResponseSeasonsInner> seasons) {
    
    this.seasons = seasons;
    return this;
  }

  public TyreSuppliersResponse addSeasonsItem(TyreSuppliersResponseSeasonsInner seasonsItem) {
    if (this.seasons == null) {
      this.seasons = new ArrayList<>();
    }
    this.seasons.add(seasonsItem);
    return this;
  }

  /**
   * Get seasons
   * @return seasons
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEASONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<TyreSuppliersResponseSeasonsInner> getSeasons() {
    return seasons;
  }


  @JsonProperty(JSON_PROPERTY_SEASONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeasons(@jakarta.annotation.Nullable List<TyreSuppliersResponseSeasonsInner> seasons) {
    this.seasons = seasons;
  }

  public TyreSuppliersResponse suppliers(@jakarta.annotation.Nullable List<TyreSuppliersResponseSuppliersInner> suppliers) {
    
    this.suppliers = suppliers;
    return this;
  }

  public TyreSuppliersResponse addSuppliersItem(TyreSuppliersResponseSuppliersInner suppliersItem) {
    if (this.suppliers == null) {
      this.suppliers = new ArrayList<>();
    }
    this.suppliers.add(suppliersItem);
    return this;
  }

  /**
   * Get suppliers
   * @return suppliers
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUPPLIERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<TyreSuppliersResponseSuppliersInner> getSuppliers() {
    return suppliers;
  }


  @JsonProperty(JSON_PROPERTY_SUPPLIERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSuppliers(@jakarta.annotation.Nullable List<TyreSuppliersResponseSuppliersInner> suppliers) {
    this.suppliers = suppliers;
  }

  public TyreSuppliersResponse apiRequestsRemaining(@jakarta.annotation.Nullable Integer apiRequestsRemaining) {
    
    this.apiRequestsRemaining = apiRequestsRemaining;
    return this;
  }

  /**
   * Get apiRequestsRemaining
   * @return apiRequestsRemaining
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_API_REQUESTS_REMAINING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getApiRequestsRemaining() {
    return apiRequestsRemaining;
  }


  @JsonProperty(JSON_PROPERTY_API_REQUESTS_REMAINING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApiRequestsRemaining(@jakarta.annotation.Nullable Integer apiRequestsRemaining) {
    this.apiRequestsRemaining = apiRequestsRemaining;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TyreSuppliersResponse tyreSuppliersResponse = (TyreSuppliersResponse) o;
    return Objects.equals(this.loadingDataState, tyreSuppliersResponse.loadingDataState) &&
        Objects.equals(this.curSupplierId, tyreSuppliersResponse.curSupplierId) &&
        Objects.equals(this.canSignContract, tyreSuppliersResponse.canSignContract) &&
        Objects.equals(this.seasonNb, tyreSuppliersResponse.seasonNb) &&
        Objects.equals(this.selectedSeason, tyreSuppliersResponse.selectedSeason) &&
        Objects.equals(this.clickedSupplier, tyreSuppliersResponse.clickedSupplier) &&
        Objects.equals(this.showSignConfirm, tyreSuppliersResponse.showSignConfirm) &&
        Objects.equals(this.seasons, tyreSuppliersResponse.seasons) &&
        Objects.equals(this.suppliers, tyreSuppliersResponse.suppliers) &&
        Objects.equals(this.apiRequestsRemaining, tyreSuppliersResponse.apiRequestsRemaining);
  }

  @Override
  public int hashCode() {
    return Objects.hash(loadingDataState, curSupplierId, canSignContract, seasonNb, selectedSeason, clickedSupplier, showSignConfirm, seasons, suppliers, apiRequestsRemaining);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TyreSuppliersResponse {\n");
    sb.append("    loadingDataState: ").append(toIndentedString(loadingDataState)).append("\n");
    sb.append("    curSupplierId: ").append(toIndentedString(curSupplierId)).append("\n");
    sb.append("    canSignContract: ").append(toIndentedString(canSignContract)).append("\n");
    sb.append("    seasonNb: ").append(toIndentedString(seasonNb)).append("\n");
    sb.append("    selectedSeason: ").append(toIndentedString(selectedSeason)).append("\n");
    sb.append("    clickedSupplier: ").append(toIndentedString(clickedSupplier)).append("\n");
    sb.append("    showSignConfirm: ").append(toIndentedString(showSignConfirm)).append("\n");
    sb.append("    seasons: ").append(toIndentedString(seasons)).append("\n");
    sb.append("    suppliers: ").append(toIndentedString(suppliers)).append("\n");
    sb.append("    apiRequestsRemaining: ").append(toIndentedString(apiRequestsRemaining)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

